This notebook was ran on L4 GPU with high RAM. Due to inconsistencies in the PPMI web interface, we implemented custom monkey-patches to the scraping logic (https://github.com/LivingPark-MRI/ppmi-scraper). In cases where automated retrieval failed, data were manually downloaded and verified to ensure dataset completeness.

# File Loading and Credentials

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Define paths
metadata_path = '/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/T1_metadata_multilcmm_longitudinal_3corrected.csv'
checkpoint_path = '/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/processing_checkpoint_multilcmm_longitudinal.csv'

# Load files into memory
df_metadata = pd.read_csv(metadata_path)
df_checkpoint = pd.read_csv(checkpoint_path)

# Define PPMI credentials
MY_EMAIL = ""
MY_PASSWORD = ""

In [ ]:
num_pending_patients = df_checkpoint[df_checkpoint['status'] == 'pending'].shape[0]
print(f"Number of patients with 'pending' status: {num_pending_patients}")

Number of patients with 'pending' status: 0

# PPMI Downloader Setup and Patching

This entire section runs in ~1 min

In [ ]:
pip install ppmi-downloader

Collecting ppmi-downloader
  Downloading ppmi_downloader-0.7.6-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from ppmi-downloader) (4.13.5)
Collecting icecream (from ppmi-downloader)
  Downloading icecream-2.2.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from ppmi-downloader) (6.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from ppmi-downloader) (2.2.2)
Collecting pathspec (from ppmi-downloader)
  Downloading pathspec-1.0.4-py3-none-any.whl.metadata (13 kB)
Collecting selenium (from ppmi-downloader)
  Downloading selenium-4.41.0-py3-none-any.whl.metadata (7.5 kB)
Collecting spython (from ppmi-downloader)
  Downloading spython-0.3.14-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ppmi-downloader) (4.67.3)
Collecting webdriver-manager>=4.0.0 (from ppmi-downloader)
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager>=4.0.0->ppmi-downloader) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager>=4.0.0->ppmi-downloader) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager>=4.0.0->ppmi-downloader) (26.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->ppmi-downloader) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->ppmi-downloader) (4.15.0)
Collecting colorama>=0.3.9 (from icecream->ppmi-downloader)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: pygments>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from icecream->ppmi-downloader) (2.20.0)
Collecting executing>=2.1.0 (from icecream->ppmi-downloader)
  Downloading executing-2.2.1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting asttokens>=2.0.1 (from icecream->ppmi-downloader)
  Downloading asttokens-3.0.1-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->ppmi-downloader) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->ppmi-downloader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->ppmi-downloader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->ppmi-downloader) (2025.3)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium->ppmi-downloader) (2026.2.25)
Collecting trio<1.0,>=0.31.0 (from selenium->ppmi-downloader)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium->ppmi-downloader)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium->ppmi-downloader)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium->ppmi-downloader) (1.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->ppmi-downloader) (1.17.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->ppmi-downloader) (26.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->ppmi-downloader) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->ppmi-downloader) (3.11)
Collecting outcome (from trio<1.0,>=0.31.0->selenium->ppmi-downloader)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->ppmi-downloader) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium->ppmi-downloader)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->ppmi-downloader) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager>=4.0.0->ppmi-downloader) (3.4.6)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->ppmi-downloader) (0.16.0)
Downloading ppmi_downloader-0.7.6-py3-none-any.whl (32 kB)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Downloading icecream-2.2.0-py3-none-any.whl (16 kB)
Downloading pathspec-1.0.4-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 7.4 MB/s eta 0:00:00
Downloading selenium-4.41.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 116.0 MB/s eta 0:00:00
Downloading spython-0.3.14-py3-none-any.whl (109 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.7/109.7 kB 13.4 MB/s eta 0:00:00
Downloading asttokens-3.0.1-py3-none-any.whl (27 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading executing-2.2.1-py2.py3-none-any.whl (28 kB)
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 50.0 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 18.5 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Installing collected packages: spython, wsproto, urllib3, pathspec, outcome, executing, colorama, asttokens, trio, icecream, webdriver-manager, trio-websocket, selenium, ppmi-downloader
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed asttokens-3.0.1 colorama-0.4.6 executing-2.2.1 icecream-2.2.0 outcome-1.3.0.post0 pathspec-1.0.4 ppmi-downloader-0.7.6 selenium-4.41.0 spython-0.3.14 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.6.3 webdriver-manager-4.0.2 wsproto-1.3.2

In [ ]:
!add-apt-repository -y ppa:saiarcot895/chromium-beta
!apt-get update
!apt-get install -y chromium-browser chromium-chromedriver

PPA publishes dbgsym, you may need to include 'main/debug' component
Repository: 'deb https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu/ jammy main'
Description:
This PPA contains the latest Chromium Beta builds, with hardware video decoding enabled (hidden behind a flag), and support for Widevine (needed for viewing many DRM-protected videos) enabled.

== Hardware Video Decoding ==

To enable hardware video decoding, start Chromium with the --enable-features=VaapiVideoDecoder argument. To make this persistent, create a file at /etc/chromium-browser/customizations/92-vaapi-hardware-decoding with the following contents:

CHROMIUM_FLAGS="${CHROMIUM_FLAGS} --enable-features=VaapiVideoDecoder"

See also https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration for more information on VAAPI video decoding support.

=== Widevine Support ===

The packages in this PPA have support for Widevine inside Chromium enabled. However, you still need to copy some files from Chrome into Chromium for you to use Netflix (or other websites using Encrypted Media Extensions) in Chromium.

1. Download and install Chrome (or extract the necessary files, if you know how to do that).
2. From the Chrome installation directory (probably /opt/google/chome or something similar), copy libwidevinecdm.so into ~/.config/chromium.
3. Restart Chromium.

=== Preventing falling back to the standard version of Chromium ===

Sometimes, this PPA doesn't get updated within a few days of a release, and in some cases, the version of Chromium in the standard Ubuntu repos may be newer than the version provided by the PPA. If you want to prevent apt from updating to the version in the standard Ubuntu repos, add the following three lines into /etc/apt/preferences.d/chromium:

Package: *
Pin: release o=LP-PPA-saiarcot895-chromium-beta
Pin-Priority: 700

=== Help ===

If you need help with installing Chromium or notice stuff not working that should normally work, click on my name below in the "Adding this PPA to your system" section.

=== Packaging ===

Packaging for this PPA is at https://github.com/saiarcot895/chromium-ubuntu-build. A separate branch is created for each upstream branch number.
More info: https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/saiarcot895-ubuntu-chromium-beta-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/saiarcot895-ubuntu-chromium-beta-jammy.list
Adding key to /etc/apt/trusted.gpg.d/saiarcot895-ubuntu-chromium-beta.gpg with fingerprint 4B2F369E32D934F066ACB0C3F6C3EADDA7D08424
Hit:1 https://cli.github.com/packages stable InRelease
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,482 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:8 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,960 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,844 kB]
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,980 kB]
Get:14 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy InRelease [24.6 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,310 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:17 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:18 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy/main amd64 Packages [1,795 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,219 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,622 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,125 kB]
Fetched 34.0 MB in 3s (10.8 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core chromium-browser-l10n chromium-codecs-ffmpeg-extra
  gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libcanberra0 libdouble-conversion3 libevdev2 libgtk-3-0
  libgtk-3-bin libgtk-3-common libgudev-1.0-0 libinput-bin libinput10 libmd4c0
  libmtdev1 libpipewire-0.3-0 libpipewire-0.3-common libpipewire-0.3-modules
  libqt5core5a libqt5dbus5 libqt5gui5 libqt5network5 libqt5svg5 libqt5widgets5
  librsvg2-common libspa-0.2-modules libtdb1 libva-wayland2 libwacom-bin
  libwacom-common libwacom9 libwebrtc-audio-processing1 libxcb-icccm4
  libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-util1
  libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1 libxcomposite1
  libxkbcommon-x11-0 libxtst6 pipewire pipewire-bin pipewire-media-session
  qt5-gtk-platformtheme qttranslations5-l10n rtkit session-migration
  sound-theme-freedesktop
Suggested packages:
  webaccounts-chromium-extension unity-chromium-extension chromiumflashplugin
  libcanberra-gtk0 libcanberra-pulse gvfs qt5-image-formats-plugins qtwayland5
The following NEW packages will be installed:
  at-spi2-core chromium-browser chromium-browser-l10n chromium-chromedriver
  chromium-codecs-ffmpeg-extra gsettings-desktop-schemas libatk-bridge2.0-0
  libatk1.0-0 libatk1.0-data libatspi2.0-0 libcanberra0 libdouble-conversion3
  libevdev2 libgtk-3-0 libgtk-3-bin libgtk-3-common libgudev-1.0-0
  libinput-bin libinput10 libmd4c0 libmtdev1 libpipewire-0.3-0
  libpipewire-0.3-common libpipewire-0.3-modules libqt5core5a libqt5dbus5
  libqt5gui5 libqt5network5 libqt5svg5 libqt5widgets5 librsvg2-common
  libspa-0.2-modules libtdb1 libva-wayland2 libwacom-bin libwacom-common
  libwacom9 libwebrtc-audio-processing1 libxcb-icccm4 libxcb-image0
  libxcb-keysyms1 libxcb-render-util0 libxcb-util1 libxcb-xinerama0
  libxcb-xinput0 libxcb-xkb1 libxcomposite1 libxkbcommon-x11-0 libxtst6
  pipewire pipewire-bin pipewire-media-session qt5-gtk-platformtheme
  qttranslations5-l10n rtkit session-migration sound-theme-freedesktop
0 upgraded, 57 newly installed, 0 to remove and 60 not upgraded.
Need to get 123 MB of archives.
After this operation, 481 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:3 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy/main amd64 chromium-codecs-ffmpeg-extra amd64 1:108.0.5359.40-0ubuntu1~ppa1~22.04.1 [1,299 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwebrtc-audio-processing1 amd64 0.3.1-0ubuntu5 [291 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libspa-0.2-modules amd64 0.3.48-1ubuntu3 [546 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpipewire-0.3-0 amd64 0.3.48-1ubuntu3 [274 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libdouble-conversion3 amd64 3.1.7-4 [39.0 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5core5a amd64 5.15.3+dfsg-2ubuntu0.2 [2,006 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libevdev2 amd64 1.12.1+dfsg-1 [39.5 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmtdev1 amd64 1.1.6-1build4 [14.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgudev-1.0-0 amd64 1:237-2build1 [16.3 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwacom-common all 2.2.0-1 [54.3 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwacom9 amd64 2.2.0-1 [22.0 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libinput-bin amd64 1.20.0-1ubuntu0.3 [19.9 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libinput10 amd64 1.20.0-1ubuntu0.3 [131 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmd4c0 amd64 0.4.8-1 [42.0 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5dbus5 amd64 5.15.3+dfsg-2ubuntu0.2 [222 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5network5 amd64 5.15.3+dfsg-2ubuntu0.2 [731 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-icccm4 amd64 0.4.1-1.1build2 [11.5 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-util1 amd64 0.4.0-1build2 [11.4 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-image0 amd64 0.4.0-2 [11.5 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-keysyms1 amd64 0.4.0-1build3 [8,746 B]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-render-util0 amd64 0.3.9-1build3 [10.3 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xinerama0 amd64 1.14-3ubuntu3 [5,414 B]
Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xinput0 amd64 1.14-3ubuntu3 [34.3 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xkb1 amd64 1.14-3ubuntu3 [32.8 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon-x11-0 amd64 1.4.0-1 [14.4 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5gui5 amd64 5.15.3+dfsg-2ubuntu0.2 [3,722 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libqt5widgets5 amd64 5.15.3+dfsg-2ubuntu0.2 [2,561 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libqt5svg5 amd64 5.15.3-1 [149 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtdb1 amd64 1.4.5-2build1 [46.4 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/main amd64 sound-theme-freedesktop all 0.8-2ubuntu1 [384 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcanberra0 amd64 0.30-10ubuntu1.22.04.1 [40.0 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpipewire-0.3-common all 0.3.48-1ubuntu3 [3,982 B]
Get:45 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpipewire-0.3-modules amd64 0.3.48-1ubuntu3 [525 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Get:47 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libva-wayland2 amd64 2.14.0-1 [9,784 B]
Get:48 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwacom-bin amd64 2.2.0-1 [13.6 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pipewire-bin amd64 0.3.48-1ubuntu3 [312 kB]
Get:50 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pipewire amd64 0.3.48-1ubuntu3 [3,964 B]
Get:51 http://archive.ubuntu.com/ubuntu jammy/main amd64 pipewire-media-session amd64 0.4.1-2ubuntu1 [128 kB]
Get:52 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 qt5-gtk-platformtheme amd64 5.15.3+dfsg-2ubuntu0.2 [130 kB]
Get:53 http://archive.ubuntu.com/ubuntu jammy/universe amd64 qttranslations5-l10n all 5.15.3-1 [1,983 kB]
Get:54 http://archive.ubuntu.com/ubuntu jammy/main amd64 rtkit amd64 0.13-4build2 [35.1 kB]
Get:55 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy/main amd64 chromium-browser amd64 1:108.0.5359.40-0ubuntu1~ppa1~22.04.1 [91.5 MB]
Get:56 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy/main amd64 chromium-browser-l10n all 1:108.0.5359.40-0ubuntu1~ppa1~22.04.1 [5,890 kB]
Get:57 https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu jammy/main amd64 chromium-chromedriver amd64 1:108.0.5359.40-0ubuntu1~ppa1~22.04.1 [6,015 kB]
Fetched 123 MB in 3min 5s (666 kB/s)
Extracting templates from packages: 100%
Selecting previously unselected package libatk1.0-data.
(Reading database ... 122354 files and directories currently installed.)
Preparing to unpack .../00-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../01-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../02-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../03-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libwebrtc-audio-processing1:amd64.
Preparing to unpack .../04-libwebrtc-audio-processing1_0.3.1-0ubuntu5_amd64.deb ...
Unpacking libwebrtc-audio-processing1:amd64 (0.3.1-0ubuntu5) ...
Selecting previously unselected package libspa-0.2-modules:amd64.
Preparing to unpack .../05-libspa-0.2-modules_0.3.48-1ubuntu3_amd64.deb ...
Unpacking libspa-0.2-modules:amd64 (0.3.48-1ubuntu3) ...
Selecting previously unselected package libpipewire-0.3-0:amd64.
Preparing to unpack .../06-libpipewire-0.3-0_0.3.48-1ubuntu3_amd64.deb ...
Unpacking libpipewire-0.3-0:amd64 (0.3.48-1ubuntu3) ...
Selecting previously unselected package libdouble-conversion3:amd64.
Preparing to unpack .../07-libdouble-conversion3_3.1.7-4_amd64.deb ...
Unpacking libdouble-conversion3:amd64 (3.1.7-4) ...
Selecting previously unselected package libqt5core5a:amd64.
Preparing to unpack .../08-libqt5core5a_5.15.3+dfsg-2ubuntu0.2_amd64.deb ...
Unpacking libqt5core5a:amd64 (5.15.3+dfsg-2ubuntu0.2) ...
Selecting previously unselected package libevdev2:amd64.
Preparing to unpack .../09-libevdev2_1.12.1+dfsg-1_amd64.deb ...
Unpacking libevdev2:amd64 (1.12.1+dfsg-1) ...
Selecting previously unselected package libmtdev1:amd64.
Preparing to unpack .../10-libmtdev1_1.1.6-1build4_amd64.deb ...
Unpacking libmtdev1:amd64 (1.1.6-1build4) ...
Selecting previously unselected package libgudev-1.0-0:amd64.
Preparing to unpack .../11-libgudev-1.0-0_1%3a237-2build1_amd64.deb ...
Unpacking libgudev-1.0-0:amd64 (1:237-2build1) ...
Selecting previously unselected package libwacom-common.
Preparing to unpack .../12-libwacom-common_2.2.0-1_all.deb ...
Unpacking libwacom-common (2.2.0-1) ...
Selecting previously unselected package libwacom9:amd64.
Preparing to unpack .../13-libwacom9_2.2.0-1_amd64.deb ...
Unpacking libwacom9:amd64 (2.2.0-1) ...
Selecting previously unselected package libinput-bin.
Preparing to unpack .../14-libinput-bin_1.20.0-1ubuntu0.3_amd64.deb ...
Unpacking libinput-bin (1.20.0-1ubuntu0.3) ...
Selecting previously unselected package libinput10:amd64.
Preparing to unpack .../15-libinput10_1.20.0-1ubuntu0.3_amd64.deb ...
Unpacking libinput10:amd64 (1.20.0-1ubuntu0.3) ...
Selecting previously unselected package libmd4c0:amd64.
Preparing to unpack .../16-libmd4c0_0.4.8-1_amd64.deb ...
Unpacking libmd4c0:amd64 (0.4.8-1) ...
Selecting previously unselected package libqt5dbus5:amd64.
Preparing to unpack .../17-libqt5dbus5_5.15.3+dfsg-2ubuntu0.2_amd64.deb ...
Unpacking libqt5dbus5:amd64 (5.15.3+dfsg-2ubuntu0.2) ...
Selecting previously unselected package libqt5network5:amd64.
Preparing to unpack .../18-libqt5network5_5.15.3+dfsg-2ubuntu0.2_amd64.deb ...
Unpacking libqt5network5:amd64 (5.15.3+dfsg-2ubuntu0.2) ...
Selecting previously unselected package libxcb-icccm4:amd64.
Preparing to unpack .../19-libxcb-icccm4_0.4.1-1.1build2_amd64.deb ...
Unpacking libxcb-icccm4:amd64 (0.4.1-1.1build2) ...
Selecting previously unselected package libxcb-util1:amd64.
Preparing to unpack .../20-libxcb-util1_0.4.0-1build2_amd64.deb ...
Unpacking libxcb-util1:amd64 (0.4.0-1build2) ...
Selecting previously unselected package libxcb-image0:amd64.
Preparing to unpack .../21-libxcb-image0_0.4.0-2_amd64.deb ...
Unpacking libxcb-image0:amd64 (0.4.0-2) ...
Selecting previously unselected package libxcb-keysyms1:amd64.
Preparing to unpack .../22-libxcb-keysyms1_0.4.0-1build3_amd64.deb ...
Unpacking libxcb-keysyms1:amd64 (0.4.0-1build3) ...
Selecting previously unselected package libxcb-render-util0:amd64.
Preparing to unpack .../23-libxcb-render-util0_0.3.9-1build3_amd64.deb ...
Unpacking libxcb-render-util0:amd64 (0.3.9-1build3) ...
Selecting previously unselected package libxcb-xinerama0:amd64.
Preparing to unpack .../24-libxcb-xinerama0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-xinerama0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-xinput0:amd64.
Preparing to unpack .../25-libxcb-xinput0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-xinput0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-xkb1:amd64.
Preparing to unpack .../26-libxcb-xkb1_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-xkb1:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxkbcommon-x11-0:amd64.
Preparing to unpack .../27-libxkbcommon-x11-0_1.4.0-1_amd64.deb ...
Unpacking libxkbcommon-x11-0:amd64 (1.4.0-1) ...
Selecting previously unselected package libqt5gui5:amd64.
Preparing to unpack .../28-libqt5gui5_5.15.3+dfsg-2ubuntu0.2_amd64.deb ...
Unpacking libqt5gui5:amd64 (5.15.3+dfsg-2ubuntu0.2) ...
Selecting previously unselected package libqt5widgets5:amd64.
Preparing to unpack .../29-libqt5widgets5_5.15.3+dfsg-2ubuntu0.2_amd64.deb ...
Unpacking libqt5widgets5:amd64 (5.15.3+dfsg-2ubuntu0.2) ...

In [ ]:
!dpkg -L chromium-chromedriver
!ls -l /usr/lib/chromium-browser/chromedriver
!ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
!chromedriver --version

/.
/usr
/usr/lib
/usr/lib/chromium-browser
/usr/lib/chromium-browser/chromedriver
/usr/share
/usr/share/doc
/usr/share/doc/chromium-chromedriver
/usr/share/doc/chromium-chromedriver/changelog.Debian.gz
/usr/share/doc/chromium-chromedriver/copyright
-rwxr-xr-x 1 root root 16036344 Nov 14  2022 /usr/lib/chromium-browser/chromedriver
ChromeDriver 108.0.5359.40 (280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689})

In [ ]:
import shutil
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import ppmi_downloader.ppmi_downloader

# Re-define the patch to ensure it uses the newly installed binaries
def get_driver_final(headless: bool, tempdir: str, remote: str = None):
    options = webdriver.ChromeOptions()
    prefs = {
        "download.default_directory": tempdir,
        "download.prompt_for_download": False,
    }
    options.add_experimental_option("prefs", prefs)

    # Necessary flags
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--disable-gpu")
    options.add_argument("--window-size=1920,1080")

    # Use the system installed chromium-browser
    chrome_bin = shutil.which("chromium-browser")
    if chrome_bin:
        options.binary_location = chrome_bin
        print(f"Using Chrome binary at: {chrome_bin}")

    if remote is None:
        # Use the explicitly linked chromedriver
        service = Service(executable_path="/usr/bin/chromedriver")
        driver = webdriver.Chrome(service=service, options=options)
    else:
        if remote == "hostname":
            remote = ppmi_downloader.ppmi_downloader.get_ip_hostname()
        options.add_argument("--ignore-ssl-errors=yes")
        options.add_argument("--ignore-certificate-errors")
        driver = None
        with ppmi_downloader.ppmi_downloader.timeout_manager(30):
            driver = webdriver.Remote(remote, options=options)

    driver.set_window_size(1920, 1080)
    driver.maximize_window()
    return driver

# Apply the patch
ppmi_downloader.ppmi_downloader.get_driver = get_driver_final

In [ ]:
import ppmi_downloader
import os

CONFIG_FILE = ".ppmi_config_auto"

# Create the configuration file in INI format expected by ConfigParser
# The library expects the key 'login' rather than 'email'
with open(CONFIG_FILE, 'w') as f:
    f.write("[ppmi]\n")
    f.write(f"login = {MY_EMAIL}\n")
    f.write(f"password = {MY_PASSWORD}\n")

print(f"Configuration file '{CONFIG_FILE}' created with correct section header and keys.")

# Initialize PPMIDownloader using the config file
try:
    # We still rely on the 'get_driver' patch from the previous cell to handle Chrome
    ppmi = ppmi_downloader.PPMIDownloader(config_file=CONFIG_FILE, headless=True)
    print("SUCCESS: PPMIDownloader initialized using credentials from config file.")
except Exception as e:
    print(f"FAILURE: {e}")

Configuration file '.ppmi_config_auto' created with correct section header and keys.
Using Chrome binary at: /usr/bin/chromium-browser
SUCCESS: PPMIDownloader initialized using credentials from config file.

LivingPark-utils|DEBUG|ppmi_downloader.py:173 in __init__()
                       self.driver.capabilities: {'acceptInsecureCerts': False,
                                                  'browserName': 'chrome',
                                                  'browserVersion': '108.0.5359.40',
                                                  'chrome': {'chromedriverVersion': '108.0.5359.40 '
                                                                                    '(280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689})',
                                                             'userDataDir': '/tmp/.org.chromium.Chromium.6dQlCf'},
                                                  'goog:chromeOptions': {'debuggerAddress': 'localhost:42917'},
                                                  'networkConnectionEnabled': False,
                                                  'pageLoadStrategy': 'normal',
                                                  'platformName': 'linux',
                                                  'proxy': {},
                                                  'setWindowRect': True,
                                                  'strictFileInteractability': False,
                                                  'timeouts': {'implicit': 0, 'pageLoad': 300000, 'script': 30000},
                                                  'unhandledPromptBehavior': 'dismiss and notify',
                                                  'webauthn:extension:credBlob': True,
                                                  'webauthn:extension:largeBlob': True,
                                                  'webauthn:virtualAuthenticators': True}
LivingPark-utils|DEBUG|ppmi_downloader.py:174 in __init__()
                       self.tempdir: <TemporaryDirectory '/tmp/tmpjvomkxc7'>
LivingPark-utils|DEBUG|ppmi_downloader.py:187 in __init__()
                       self.config_file: '.ppmi_config_auto'
                       config_file: '.ppmi_config_auto'

In [ ]:
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException

def scroll_and_select(self, cohort):
    """Scrolls through the export table and selects rows matching the cohort metadata."""
    print("Selecting target scans via scrolling...")
    target_metadata = set((str(row['PATNO']), str(row['EVENT_ID']), str(row['Description'])) for _, row in cohort.iterrows())
    found_metadata = set()
    prev_row_count = 0
    stale_scrolls = 0

    while found_metadata != target_metadata:
        try:
            WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.ID, 'tableData')))
            rows = self.driver.find_elements(By.XPATH, "//div[@id='tableData']//tr")

            for row in rows:
                try:
                    cells = row.find_elements(By.TAG_NAME, 'td')
                    if len(cells) > 6:
                        meta = (cells[0].text.strip(), cells[4].text.strip(), cells[6].text.strip())
                        if meta in target_metadata and meta not in found_metadata:
                            checkbox = row.find_element(By.NAME, 'checkbox')
                            if not checkbox.is_selected():
                                self.driver.execute_script('arguments[0].click();', checkbox)
                            found_metadata.add(meta)
                            print(f'  Checked: {meta}')
                except StaleElementReferenceException:
                    continue

            if found_metadata == target_metadata:
                break

            # Attempt to scroll down using the table's arrow button
            scroll_buttons = self.driver.find_elements(By.XPATH, "//tbody[.//div[@id='slider']]//input[@alt='V' and @onclick]")
            if len(scroll_buttons) > 1:
                self.driver.execute_script('arguments[0].click();', scroll_buttons[1])
                time.sleep(1.0) # Wait for table to refresh data
            else:
                stale_scrolls += 5

            if len(rows) == prev_row_count:
                stale_scrolls += 1
            else:
                stale_scrolls = 0

            if stale_scrolls > 15:
                break

            prev_row_count = len(rows)
        except StaleElementReferenceException:
            continue

    if found_metadata != target_metadata:
        # Capture screenshot on failure before raising the error
        self.driver.save_screenshot("debug_scroller_failed.png")
        missing = target_metadata - found_metadata
        raise RuntimeError(f'Could only find {len(found_metadata)} of {len(target_metadata)} scans. Missing: {missing}')

    print('All target scans successfully selected.')

# Monkey-patch the method into the class
ppmi_downloader.PPMIDownloader.scroll_and_select = scroll_and_select
print('Method scroll_and_select (with failure screenshots) has been added.')

Method scroll_and_select (with failure screenshots) has been added.

In [ ]:
def download_all_zip_files(self):
    """Finds and clicks all valid zip links and the metadata link."""
    # Wait for the overlay to show at least one download link
    try:
        WebDriverWait(self.driver, 15).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "a[data-download-link='true']"))
        )
    except:
        raise RuntimeError("No download links appeared in time.")

    # Find all data zip links
    zip_links = self.driver.find_elements(
        By.XPATH, "//a[@data-download-link='true' and contains(text(), 'Zip File')]"
    )

    if not zip_links:
        raise RuntimeError("Zero Zip File links found. Refreshing...")

    # Debug print texts
    texts = [link.text.strip() for link in zip_links]
    print(f"Found {len(zip_links)} zip link(s) with labels: {texts}")

    # Click valid zip links (skip empty ones)
    clicked_count = 0
    for i, link in enumerate(zip_links):
        label = link.text.strip()
        if label == "":
            print(f"  Skipping link {i+1} (empty label)...")
            continue

        try:
            self.driver.execute_script('arguments[0].scrollIntoView(true);', link)
            time.sleep(0.5)
            self.driver.execute_script('arguments[0].click();', link)
            print(f'  Triggered download for: {label}...')
            clicked_count += 1
            time.sleep(3)  # inter-download pause
        except Exception as e:
            print(f'Error clicking zip link {i+1}: {e}')
            raise

    if clicked_count == 0:
        raise RuntimeError("Found links but none had valid labels. Refreshing...")

    # Finally, click the metadata link
    try:
        metadata_link = WebDriverWait(self.driver, 10).until(
            EC.element_to_be_clickable((By.XPATH, "//a[contains(text(), 'Metadata')]"))
        )
        metadata_link.click()
        print('  Metadata download triggered.')
    except Exception as e:
        print(f'Metadata link click failed: {e}. Attempting fallback...')
        self.html.click_button('Metadata', By.PARTIAL_LINK_TEXT)

# Update the class method
ppmi_downloader.PPMIDownloader.download_all_zip_files = download_all_zip_files
print('Refined download_all_zip_files method (skips empty links) applied.')

Refined download_all_zip_files method (skips empty links) applied.

In [ ]:
def download_imaging_data_optimized(self, cohort: pd.DataFrame, timeout: float = 1200, destination_dir: str = "."):
    if len(cohort) == 0: return
    subjectIds = ",".join(cohort["PATNO"].astype(str).unique())
    collection_name = str(cohort["PATNO"].iloc[0])

    # 1. Login and Search
    print("Logging in and navigating to search...")
    self.driver.get(ppmi_downloader.ppmi_navigator.ppmi_main_webpage)
    self.html.login(self.email, self.password)
    self.driver.get(ppmi_downloader.ppmi_navigator.ppmi_query_page)

    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.ID, "subjectIdText"))).send_keys(subjectIds)
    self.driver.execute_script("arguments[0].click();", self.driver.find_element(By.ID, "advSearchQuery"))

    # 2. Add to Collection
    self.html.Search_AdvancedImageSearchbeta_SelectAll()
    self.driver.execute_script("arguments[0].click();", WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "advResultAddCollectId"))))
    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.ID, "nameText"))).send_keys(collection_name)
    self.html.Search_AdvancedImageSearchbeta_AddToCollection_OK()

    # 3. Navigate to Export Tab
    print(f"Navigating to Export page for {collection_name}...")
    self.driver.execute_script("arguments[0].click();", WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "export"))))

    # Increased to 10 attempts for higher reliability
    max_download_attempts = 10
    for attempt in range(max_download_attempts):
        print(f"\n--- Attempt {attempt + 1} ---")
        time.sleep(3)   # ensures the export tab is properly loaded before we start clicking

        try:
            # 4. Selection
            self.scroll_and_select(cohort)
            self.driver.save_screenshot(f"debug_1_selected_attempt_{attempt+1}.png")

            # 5. Open Download Overlay
            print("Initiating download overlay...")
            dl_btn = self.driver.find_element(By.ID, "simple-download-button")
            self.driver.execute_script("arguments[0].click();", dl_btn)
            time.sleep(10)
            self.driver.save_screenshot(f"debug_2_overlay_attempt_{attempt+1}.png")

            # 6. Download Links
            self.download_all_zip_files()
            break # Success

        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}. Refreshing page and retrying...")
            self.driver.refresh()
    else:
        raise RuntimeError("Failed to complete download after 10 attempts.")

    # 7. Wait for completion and Unzip
    time.sleep(1)   # important fix to ensure the metadata download starts before the download_complete condition is checked
    def download_complete(driver):
        files = os.listdir(self.tempdir.name)
        return len(files) > 0 and not any(f.endswith(".crdownload") for f in files)

    print("Waiting for files to finish downloading...")
    WebDriverWait(self.driver, timeout).until(download_complete)
    self.html.unzip_imaging_data(os.listdir(self.tempdir.name), self.tempdir.name, destination_dir)
    print("Download and extraction complete.")

# Apply the optimized version to the class
ppmi_downloader.PPMIDownloader.download_imaging_data = download_imaging_data_optimized
print("Concise download_imaging_data_optimized updated with 10 retry attempts.")

Concise download_imaging_data_optimized updated with 10 retry attempts.

In [ ]:
import re

def prepare_patient_cohort(selected_patno):
    """
    Filters df_metadata for a specific patient and prepares the cohort format for the downloader.
    Includes Image ID to ensure unique scan selection.
    """
    df_subject_raw = df_metadata[df_metadata['Subject ID'].astype(str) == str(selected_patno)].copy()

    if df_subject_raw.empty:
        print(f"Warning: No metadata found for Subject {selected_patno}")
        return pd.DataFrame()

    def extract_patno(val):
        match = re.search(r'(\d+)', str(val))
        return int(match.group(1)) if match else None

    df_subject_raw['PATNO'] = df_subject_raw['Subject ID'].apply(extract_patno)

    visit_col = 'Visit_Short' if 'Visit_Short' in df_subject_raw.columns else 'Visit'
    df_subject_raw['EVENT_ID'] = df_subject_raw[visit_col]

    # Include Image ID in the selection to distinguish between identical descriptions
    df_selected_cohort = df_subject_raw[['PATNO', 'EVENT_ID', 'Description', 'Image ID']].drop_duplicates()

    print(f"Prepared mini-cohort for Subject {selected_patno} with {len(df_selected_cohort)} records (using unique Image IDs).")
    return df_selected_cohort

print("prepare_patient_cohort updated to include Image ID.")

prepare_patient_cohort updated to include Image ID.

# Fastsurfer Setup

FastSurfer requires NIfTI (.nii, .nii.gz) or MGH (.mgz) files. PPMI downloads MRI in DICOM format. There seems to have been an option in the past to download in NIfTI but it's no longer available.

In [ ]:
#@title Install dcm2niix for DICOM conversion
!apt-get update -qq && apt-get install -y dcm2niix

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libturbojpeg libyaml-cpp0.7
The following NEW packages will be installed:
  dcm2niix libturbojpeg libyaml-cpp0.7
0 upgraded, 3 newly installed, 0 to remove and 60 not upgraded.
Need to get 529 kB of archives.
After this operation, 1,877 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libturbojpeg amd64 2.1.2-0ubuntu1 [175 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libyaml-cpp0.7 amd64 0.7.0+dfsg-8build1 [97.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 dcm2niix amd64 1.0.20211006-1build1 [256 kB]
Fetched 529 kB in 1s (438 kB/s)
Selecting previously unselected package libturbojpeg:amd64.
(Reading database ... 124066 files and directories currently installed.)
Preparing to unpack .../libturbojpeg_2.1.2-0ubuntu1_amd64.deb ...
Unpacking libturbojpeg:amd64 (2.1.2-0ubuntu1) ...
Selecting previously unselected package libyaml-cpp0.7:amd64.
Preparing to unpack .../libyaml-cpp0.7_0.7.0+dfsg-8build1_amd64.deb ...
Unpacking libyaml-cpp0.7:amd64 (0.7.0+dfsg-8build1) ...
Selecting previously unselected package dcm2niix.
Preparing to unpack .../dcm2niix_1.0.20211006-1build1_amd64.deb ...
Unpacking dcm2niix (1.0.20211006-1build1) ...
Setting up libyaml-cpp0.7:amd64 (0.7.0+dfsg-8build1) ...
Setting up libturbojpeg:amd64 (2.1.2-0ubuntu1) ...
Setting up dcm2niix (1.0.20211006-1build1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

In [ ]:
#@title Setup the environment by downloading the stable branch of deep-mi/fastsurfer project and the required packages

import os
import sys
from os.path import exists, join, basename, splitext

print("Starting setup. This could take a few minutes")
print("----------------------------------------------")

is_google_colab = "colab.research.google.com" in str(os.environ)
if is_google_colab:
    # this is for a Google Colab Notebook
    SETUP_DIR = "/content/"
else:
    SETUP_DIR = os.environ["HOME"] + "/fastsurfer_files/"

# Go to the FastSurfer directory
!mkdir -p "{SETUP_DIR}"
%cd "{SETUP_DIR}"

print(f"Using {SETUP_DIR} to store files.")

print("Downloading FastSurfer")
print("----------------------------------------------")


git_repo_url = 'https://github.com/deep-mi/fastsurfer.git'
project_name = splitext(basename(git_repo_url))[0]
FASTSURFER_HOME = SETUP_DIR + project_name + "/"
if not exists(project_name):
  # clone and install dependencies
  ! git clone -q --branch stable $git_repo_url
  ! pip install -r $FASTSURFER_HOME/requirements.txt
sys.path.append(FASTSURFER_HOME)

# Update dependencies
print("Installing required packages")
print("----------------------------------------------")

! pip install torchio==0.18.83
! pip install yacs==0.1.8
! pip install plotly==5.9.0

print("Finished setup")
print("----------------------------------------------")

Starting setup. This could take a few minutes
----------------------------------------------
/content
Using /content/ to store files.
Downloading FastSurfer
----------------------------------------------
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu126
Collecting absl-py==2.1.0 (from -r /content/fastsurfer//requirements.txt (line 17))
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting Brotli==1.1.0 (from -r /content/fastsurfer//requirements.txt (line 18))
  Downloading Brotli-1.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting cached-property==1.5.2 (from -r /content/fastsurfer//requirements.txt (line 19))
  Downloading cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting certifi==2024.12.14 (from -r /content/fastsurfer//requirements.txt (line 20))
  Downloading certifi-2024.12.14-py3-none-any.whl.metadata (2.3 kB)
Collecting cffi==1.17.1 (from -r /content/fastsurfer//requirements.txt (line 21))
  Downloading cffi-1.17.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting charset-normalizer==3.4.1 (from -r /content/fastsurfer//requirements.txt (line 22))
  Downloading charset_normalizer-3.4.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (35 kB)
Collecting click==8.1.8 (from -r /content/fastsurfer//requirements.txt (line 23))
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: colorama==0.4.6 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 24)) (0.4.6)
Collecting contourpy==1.3.1 (from -r /content/fastsurfer//requirements.txt (line 25))
  Downloading contourpy-1.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: cycler==0.12.1 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 26)) (0.12.1)
Collecting Deprecated==1.2.18 (from -r /content/fastsurfer//requirements.txt (line 27))
  Downloading Deprecated-1.2.18-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting filelock==3.17.0 (from -r /content/fastsurfer//requirements.txt (line 28))
  Downloading filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
Collecting fonttools==4.55.8 (from -r /content/fastsurfer//requirements.txt (line 29))
  Downloading fonttools-4.55.8-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.2/101.2 kB 7.0 MB/s eta 0:00:00
Collecting fsspec==2024.12.0 (from -r /content/fastsurfer//requirements.txt (line 30))
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Collecting grpcio==1.67.1 (from -r /content/fastsurfer//requirements.txt (line 31))
  Downloading grpcio-1.67.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting h2==4.1.0 (from -r /content/fastsurfer//requirements.txt (line 32))
  Downloading h2-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Collecting h5py==3.12.1 (from -r /content/fastsurfer//requirements.txt (line 33))
  Downloading h5py-3.12.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Requirement already satisfied: hpack==4.1.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 34)) (4.1.0)
Collecting humanize==4.11.0 (from -r /content/fastsurfer//requirements.txt (line 35))
  Downloading humanize-4.11.0-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: hyperframe==6.1.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 36)) (6.1.0)
Collecting idna==3.10 (from -r /content/fastsurfer//requirements.txt (line 37))
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting imagecodecs==2024.12.30 (from -r /content/fastsurfer//requirements.txt (line 38))
  Downloading imagecodecs-2024.12.30-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting imageio==2.37.0 (from -r /content/fastsurfer//requirements.txt (line 39))
  Downloading imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
Collecting importlib_metadata==8.6.1 (from -r /content/fastsurfer//requirements.txt (line 40))
  Downloading importlib_metadata-8.6.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: importlib_resources==6.5.2 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 41)) (6.5.2)
Collecting Jinja2==3.1.5 (from -r /content/fastsurfer//requirements.txt (line 42))
  Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib==1.4.2 (from -r /content/fastsurfer//requirements.txt (line 43))
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting kiwisolver==1.4.7 (from -r /content/fastsurfer//requirements.txt (line 44))
  Downloading kiwisolver-1.4.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.3 kB)
Collecting lapy==1.2.0 (from -r /content/fastsurfer//requirements.txt (line 45))
  Downloading lapy-1.2.0-py3-none-any.whl.metadata (8.4 kB)
Collecting lazy_loader==0.4 (from -r /content/fastsurfer//requirements.txt (line 46))
  Downloading lazy_loader-0.4-py3-none-any.whl.metadata (7.6 kB)
Collecting Markdown==3.6 (from -r /content/fastsurfer//requirements.txt (line 47))
  Downloading Markdown-3.6-py3-none-any.whl.metadata (7.0 kB)
Collecting markdown-it-py==3.0.0 (from -r /content/fastsurfer//requirements.txt (line 48))
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting MarkupSafe==3.0.2 (from -r /content/fastsurfer//requirements.txt (line 49))
  Downloading https://download.pytorch.org/whl/MarkupSafe-3.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Requirement already satisfied: matplotlib==3.10.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 50)) (3.10.0)
Requirement already satisfied: mdurl==0.1.2 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 51)) (0.1.2)
Requirement already satisfied: mpmath==1.3.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 52)) (1.3.0)
Collecting munkres==1.1.4 (from -r /content/fastsurfer//requirements.txt (line 53))
  Downloading munkres-1.1.4-py2.py3-none-any.whl.metadata (980 bytes)
Collecting narwhals==1.24.1 (from -r /content/fastsurfer//requirements.txt (line 54))
  Downloading narwhals-1.24.1-py3-none-any.whl.metadata (10.0 kB)
Collecting networkx==3.4.2 (from -r /content/fastsurfer//requirements.txt (line 55))
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Collecting nibabel==5.3.2 (from -r /content/fastsurfer//requirements.txt (line 56))
  Downloading nibabel-5.3.2-py3-none-any.whl.metadata (9.1 kB)
Collecting numpy==1.26.4 (from -r /content/fastsurfer//requirements.txt (line 57))
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.9 MB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.6.4.1 (from -r /content/fastsurfer//requirements.txt (line 58))
  Downloading https://pypi.nvidia.com/nvidia-cublas-cu12/nvidia_cublas_cu12-12.6.4.1-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (393.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 116.5 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.6.80 (from -r /content/fastsurfer//requirements.txt (line 59))
  Downloading https://pypi.nvidia.com/nvidia-cuda-cupti-cu12/nvidia_cuda_cupti_cu12-12.6.80-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 225.3 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu12==12.6.77 (from -r /content/fastsurfer//requirements.txt (line 60))
  Downloading https://pypi.nvidia.com/nvidia-cuda-nvrtc-cu12/nvidia_cuda_nvrtc_cu12-12.6.77-py3-none-manylinux2014_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 113.3 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.6.77 (from -r /content/fastsurfer//requirements.txt (line 61))
  Downloading https://pypi.nvidia.com/nvidia-cuda-runtime-cu12/nvidia_cuda_runtime_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (897 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 248.1 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.5.1.17 (from -r /content/fastsurfer//requirements.txt (line 62))
  Downloading https://pypi.nvidia.com/nvidia-cudnn-cu12/nvidia_cudnn_cu12-9.5.1.17-py3-none-manylinux_2_28_x86_64.whl (571.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 73.3 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.3.0.4 (from -r /content/fastsurfer//requirements.txt (line 63))
  Downloading https://pypi.nvidia.com/nvidia-cufft-cu12/nvidia_cufft_cu12-11.3.0.4-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (200.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 136.5 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.7.77 (from -r /content/fastsurfer//requirements.txt (line 64))
  Downloading https://pypi.nvidia.com/nvidia-curand-cu12/nvidia_curand_cu12-10.3.7.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (56.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 147.9 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.7.1.2 (from -r /content/fastsurfer//requirements.txt (line 65))
  Downloading https://pypi.nvidia.com/nvidia-cusolver-cu12/nvidia_cusolver_cu12-11.7.1.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (158.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 90.4 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.5.4.2 (from -r /content/fastsurfer//requirements.txt (line 66))
  Downloading https://pypi.nvidia.com/nvidia-cusparse-cu12/nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (216.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 125.4 MB/s eta 0:00:00
Collecting nvidia-cusparselt-cu12==0.6.3 (from -r /content/fastsurfer//requirements.txt (line 67))
  Downloading https://pypi.nvidia.com/nvidia-cusparselt-cu12/nvidia_cusparselt_cu12-0.6.3-py3-none-manylinux2014_x86_64.whl (156.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 121.2 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.21.5 (from -r /content/fastsurfer//requirements.txt (line 68))
  Downloading https://pypi.nvidia.com/nvidia-nccl-cu12/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 91.2 MB/s eta 0:00:00
Collecting nvidia-nvjitlink-cu12==12.6.85 (from -r /content/fastsurfer//requirements.txt (line 69))
  Downloading https://pypi.nvidia.com/nvidia-nvjitlink-cu12/nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (19.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.7/19.7 MB 152.6 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.6.77 (from -r /content/fastsurfer//requirements.txt (line 70))
  Downloading https://pypi.nvidia.com/nvidia-nvtx-cu12/nvidia_nvtx_cu12-12.6.77-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.3/89.3 kB 134.5 MB/s eta 0:00:00
Collecting packaging==24.2 (from -r /content/fastsurfer//requirements.txt (line 71))
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pandas==2.2.3 (from -r /content/fastsurfer//requirements.txt (line 72))
  Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 9.8 MB/s eta 0:00:00
Collecting pillow==11.1.0 (from -r /content/fastsurfer//requirements.txt (line 73))
  Downloading pillow-11.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pip==25.0 (from -r /content/fastsurfer//requirements.txt (line 74))
  Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Collecting plotly==6.0.0 (from -r /content/fastsurfer//requirements.txt (line 75))
  Downloading plotly-6.0.0-py3-none-any.whl.metadata (5.6 kB)
Collecting protobuf==5.28.3 (from -r /content/fastsurfer//requirements.txt (line 76))
  Downloading protobuf-5.28.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting psutil==6.1.1 (from -r /content/fastsurfer//requirements.txt (line 77))
  Downloading psutil-6.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting pycparser==2.22 (from -r /content/fastsurfer//requirements.txt (line 78))
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Collecting Pygments==2.19.1 (from -r /content/fastsurfer//requirements.txt (line 79))
  Downloading pygments-2.19.1-py3-none-any.whl.metadata (2.5 kB)
Collecting pyparsing==3.2.1 (from -r /content/fastsurfer//requirements.txt (line 80))
  Downloading pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Collecting PySide6==6.8.1 (from -r /content/fastsurfer//requirements.txt (line 81))
  Downloading PySide6-6.8.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: PySocks==1.7.1 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 82)) (1.7.1)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 83)) (2.9.0.post0)
Collecting pytz==2024.1 (from -r /content/fastsurfer//requirements.txt (line 84))
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting PyWavelets==1.8.0 (from -r /content/fastsurfer//requirements.txt (line 85))
  Downloading pywavelets-1.8.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting PyYAML==6.0.2 (from -r /content/fastsurfer//requirements.txt (line 86))
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting requests==2.32.3 (from -r /content/fastsurfer//requirements.txt (line 87))
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: rich==13.9.4 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 88)) (13.9.4)
Collecting scikit-image==0.25.1 (from -r /content/fastsurfer//requirements.txt (line 89))
  Downloading scikit_image-0.25.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Requirement already satisfied: scikit-learn==1.6.1 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 90)) (1.6.1)
Collecting scikit-sparse==0.4.15 (from -r /content/fastsurfer//requirements.txt (line 91))
  Downloading scikit_sparse-0.4.15.tar.gz (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.4/214.4 kB 15.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting scipy==1.15.1 (from -r /content/fastsurfer//requirements.txt (line 92))
  Downloading scipy-1.15.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 7.2 MB/s eta 0:00:00
Collecting setuptools==75.8.0 (from -r /content/fastsurfer//requirements.txt (line 93))
  Downloading setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: shellingham==1.5.4 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 94)) (1.5.4)
Collecting shiboken6==6.8.1 (from -r /content/fastsurfer//requirements.txt (line 95))
  Downloading shiboken6-6.8.1-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting SimpleITK==2.4.1 (from -r /content/fastsurfer//requirements.txt (line 96))
  Downloading SimpleITK-2.4.1-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: six==1.17.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/fastsurfer//requirements.txt (line 97)) (1.17.0)
Collecting sympy==1.13.1 (from -r /content/fastsurfer//requirements.txt (line 98))
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting tensorboard==2.18.0 (from -r /content/fastsurfer//requirements.txt (line 99))
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting tensorboard_data_server==0.7.0 (from -r /content/fastsurfer//requirements.txt (line 100))
  Downloading tensorboard_data_server-0.7.0-py3-none-manylinux2014_x86_64.whl.metadata (1.1 kB)
Collecting threadpoolctl==3.5.0 (from -r /content/fastsurfer//requirements.txt (line 101))
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting tifffile==2025.1.10 (from -r /content/fastsurfer//requirements.txt (line 102))
  Downloading tifffile-2025.1.10-py3-none-any.whl.metadata (31 kB)
Collecting torch==2.6.0+cu126 (from -r /content/fastsurfer//requirements.txt (line 103))
  Downloading https://download-r2.pytorch.org/whl/cu126/torch-2.6.0%2Bcu126-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (28 kB)
Collecting torchio==0.20.4 (from -r /content/fastsurfer//requirements.txt (line 104))
  Downloading torchio-0.20.4-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 5.7 MB/s eta 0:00:00
Collecting torchvision==0.21.0+cu126 (from -r /content/fastsurfer//requirements.txt (line 105))
  Downloading https://download-r2.pytorch.org/whl/cu126/torchvision-0.21.0%2Bcu126-cp312-cp312-linux_x86_64.whl.metadata (6.1 kB)
Collecting tornado==6.4.2 (from -r /content/fastsurfer//requirements.txt (line 106))
  Downloading tornado-6.4.2-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting tqdm==4.67.1 (from -r /content/fastsurfer//requirements.txt (line 107))
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 6.5 MB/s eta 0:00:00
Collecting triton==3.2.0 (from -r /content/fastsurfer//requirements.txt (line 108))
  Downloading https://download-r2.pytorch.org/whl/triton-3.2.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.4 kB)
Collecting typer==0.15.1 (from -r /content/fastsurfer//requirements.txt (line 109))
  Downloading typer-0.15.1-py3-none-any.whl.metadata (15 kB)
Collecting typing_extensions==4.12.2 (from -r /content/fastsurfer//requirements.txt (line 110))
  Downloading https://download.pytorch.org/whl/typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting tzdata==2025.1 (from -r /content/fastsurfer//requirements.txt (line 111))
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting unicodedata2==16.0.0 (from -r /content/fastsurfer//requirements.txt (line 112))
  Downloading unicodedata2-16.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting urllib3==2.3.0 (from -r /content/fastsurfer//requirements.txt (line 113))
  Downloading urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting Werkzeug==3.1.3 (from -r /content/fastsurfer//requirements.txt (line 114))
  Downloading werkzeug-3.1.3-py3-none-any.whl.metadata (3.7 kB)
Collecting wheel==0.45.1 (from -r /content/fastsurfer//requirements.txt (line 115))
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting wrapt==1.17.2 (from -r /content/fastsurfer//requirements.txt (line 116))
  Downloading wrapt-1.17.2-cp312-cp312-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting yacs==0.1.8 (from -r /content/fastsurfer//requirements.txt (line 117))
  Downloading yacs-0.1.8-py3-none-any.whl.metadata (639 bytes)

In [ ]:
import subprocess

class FastSurferSegmentationError(Exception):
    """Custom exception for specific segmentation failures like division by zero."""
    pass

def run_fastsurfer_robust_v2(cmd):
    """
    Executes FastSurfer and monitors output.
    Terminates on success OR known fatal errors.
    """
    print(f"Executing command:\n{cmd}\n")
    print("--- Output Log (Robust v2.2) ---")

    process = subprocess.Popen(
        cmd,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        universal_newlines=True,
        bufsize=1
    )

    error_detected = False
    for line in process.stdout:
        print(line, end='')

        # Success Check
        if "Processing whole pipeline finished" in line:
            print("\n>>> Success criteria met. Terminating process.")
            process.terminate()
            break

        # Check for multiple variations of the known stats/seg failures
        known_errors = [
            "ERROR: asegdkt statsfile generation failed!",
            "ERROR: FastSurfer asegdkt segmentation failed",
            "ERROR: Cerebellum Segmentation failed!",
            "ERROR: Biasfield correction failed!"
        ]

        if any(err in line for err in known_errors):
            print(f"\n>>> KNOWN ERROR DETECTED: {line.strip()}. Terminating process to skip.")
            error_detected = True
            process.terminate()
            break

    process.wait()
    print("--- Process Finished ---")

    if error_detected:
        raise FastSurferSegmentationError("Segmentation/Stats/Biasfield failure detected")

In [ ]:
import glob
import os

def construct_command(selected_patno):
    """
    Constructs a list of FastSurfer cross-sectional commands, one for each MRI session.
    Args:
        selected_patno (str): The ID of the patient to process.
    Returns:
        list: A list of constructed shell commands.
    """
    # 1. Define where we expect the NIfTI files to be located
    input_dir = f"/content/data/{selected_patno}"
    nifti_files = sorted(glob.glob(os.path.join(input_dir, "*.nii.gz")))

    if not nifti_files:
        print(f"No NIfTI files found for patient {selected_patno} in {input_dir}")
        return []

    commands = []

    # 2. Loop over each image to create a cross-sectional command
    for img in nifti_files:
        # We use the filename (without extension) as part of the --sid to distinguish sessions
        session_id = f"{selected_patno}_{os.path.basename(img).replace('.nii.gz', '')}"

        cmd = (
            f"export FASTSURFER_HOME={FASTSURFER_HOME}; "
            f"{FASTSURFER_HOME}/run_fastsurfer.sh "
            f"--t1 {img} "
            f"--sd {SETUP_DIR}fastsurfer_seg "
            f"--sid {session_id} "
            f"--seg_only "
            f"--py python3 "
            f"--3T "
            f"--allow_root"
        )
        commands.append(cmd)

    return commands

print("construct_command updated to return a list of session-specific commands.")

construct_command updated to return a list of session-specific commands.

In [ ]:
import shutil
import os
import glob

def zip_and_save_stats(selected_patno):
    """
    Zips all stats directories for a specific patient's cross-sectional sessions and saves to Drive.
    Args:
        selected_patno (str): The ID of the patient.
    """
    output_base_dir = f"{SETUP_DIR}fastsurfer_seg"
    drive_export_dir = "/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/"
    zip_filename = f"stats_{selected_patno}.zip"
    zip_path = os.path.join("/content", zip_filename)

    if not os.path.exists(output_base_dir):
        print(f"Output directory {output_base_dir} does not exist.")
        return

    # 1. Identify all directories belonging to this subject
    # In the cross-sectional setup, we named sids as {selected_patno}_{session}
    all_dirs = [d for d in os.listdir(output_base_dir) if os.path.isdir(os.path.join(output_base_dir, d))]

    # Filter for directories starting with the patient ID
    subject_dirs = [d for d in all_dirs if d.startswith(str(selected_patno))]

    if not subject_dirs:
        print(f"No stats directories found for patient {selected_patno} in {output_base_dir}.")
        return

    # 2. Create a temporary staging area
    temp_zip_dir = f"/content/temp_stats_{selected_patno}"
    if os.path.exists(temp_zip_dir):
        shutil.rmtree(temp_zip_dir)
    os.makedirs(temp_zip_dir, exist_ok=True)

    print(f"Collecting stats from sessions: {subject_dirs}")
    found_any_stats = False
    for d in subject_dirs:
        src_stats = os.path.join(output_base_dir, d, "stats")
        if os.path.exists(src_stats):
            dest = os.path.join(temp_zip_dir, d)
            shutil.copytree(src_stats, dest)
            found_any_stats = True
        else:
            print(f"  Warning: No stats folder found in {d}")

    if not found_any_stats:
        print(f"No actual 'stats' folders found to zip for {selected_patno}.")
        return

    # 3. Zip and Move
    print(f"Zipping collected session stats for patient {selected_patno}...")
    shutil.make_archive(zip_path.replace('.zip', ''), 'zip', temp_zip_dir)

    os.makedirs(drive_export_dir, exist_ok=True)
    final_drive_path = os.path.join(drive_export_dir, zip_filename)

    if os.path.exists(final_drive_path):
        os.remove(final_drive_path)

    shutil.move(zip_path, final_drive_path)

    # Clean up
    shutil.rmtree(temp_zip_dir)
    print(f"Stats successfully saved to Drive: {final_drive_path}")

print('zip_and_save_stats updated for cross-sectional session collection.')

zip_and_save_stats updated for cross-sectional session collection.

# Processing Loop

## Main Loop

In [ ]:
'''

import datetime
import os

# Main Processing Loop
# Iterates through subjects marked as 'pending' or 'failed'
for index, row in df_checkpoint[df_checkpoint['status'].isin(['pending', 'failed'])].iterrows():
    subject_id = str(row['Subject ID'])
    print(f"\n{'='*80}\nSTARTING PROCESS FOR SUBJECT: {subject_id}\n{'='*80}")

    try:
        # 1. Initialize PPMI Downloader
        print(f"[STEP 1] Initializing PPMIDownloader for {subject_id}...")
        ppmi = ppmi_downloader.PPMIDownloader(config_file=CONFIG_FILE, headless=True)

        # 2. Prepare Cohort Metadata
        print(f"[STEP 2] Preparing cohort metadata for {subject_id}...")
        cohort = prepare_patient_cohort(subject_id)
        if cohort.empty:
            print(f"!!! Skipping {subject_id}: Metadata filtering returned empty result.")
            df_checkpoint.at[index, 'status'] = 'failed'
            continue

        # 3. Setup Local Workspace
        subject_dir = f"/content/data/{subject_id}"
        print(f"[STEP 3] Setting up directory: {subject_dir}")
        if os.path.exists(subject_dir):
            shutil.rmtree(subject_dir)
        os.makedirs(subject_dir, exist_ok=True)

        # 4. Download Imaging Data
        print(f"[STEP 4] Downloading DICOM scans from PPMI for {subject_id}...")
        ppmi.download_imaging_data(cohort, destination_dir=subject_dir)

        # 5. DICOM to NIfTI Conversion
        print(f"[STEP 5] Converting DICOMs to NIfTI using dcm2niix...")
        conv_cmd = f"dcm2niix -z y -f %p_%t -o {subject_dir} {subject_dir}"
        os.system(conv_cmd)

        # 6. Construct FastSurfer Commands (returns a list for cross-sectional)
        print(f"[STEP 6] Constructing session-specific FastSurfer commands...")
        fs_commands = construct_command(subject_id)

        if not fs_commands:
            raise RuntimeError(f"No commands generated for {subject_id}. Check if NIfTI files exist in {subject_dir}")

        # 7. Execute Segmentation for each session
        print(f"[STEP 7] Launching Segmentation Pipeline for {len(fs_commands)} sessions...")
        for i, cmd in enumerate(fs_commands):
            print(f"\n--- Processing Session {i+1}/{len(fs_commands)} ---")
            # We use the cross-sectional robust wrapper
            run_fastsurfer_robust(cmd)

        # 8. Check Outputs and Save Results (Zips all sessions found)
        print(f"[STEP 8] Verifying outputs and zipping all session stats...")
        zip_and_save_stats(subject_id)

        # 9. Update Checkpoint on Success
        df_checkpoint.at[index, 'status'] = 'completed'
        df_checkpoint.at[index, 'timestamp'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"\nSUCCESS: Subject {subject_id} processed completely ({len(fs_commands)} sessions).")

    except Exception as e:
        print(f"\n!!! CRITICAL ERROR for Subject {subject_id}: {e}")
        df_checkpoint.at[index, 'status'] = 'failed'
        df_checkpoint.at[index, 'timestamp'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    finally:
        # Clean up Driver session
        try:
            ppmi.driver.quit()
            print("[INFO] Selenium driver closed.")
        except:
            pass

        # Save checkpoint progress to Drive after every subject
        df_checkpoint.to_csv(checkpoint_path, index=False)
        print(f"[INFO] Checkpoint saved to Drive.")

print("\nALL SUBJECTS IN QUEUE PROCESSED.")

'''

'\n\nimport datetime\nimport os\n\n# Main Processing Loop\n# Iterates through subjects marked as \'pending\' or \'failed\'\nfor index, row in df_checkpoint[df_checkpoint[\'status\'].isin([\'pending\', \'failed\'])].iterrows():\n    subject_id = str(row[\'Subject ID\'])\n    print(f"\n{\'=\'*80}\nSTARTING PROCESS FOR SUBJECT: {subject_id}\n{\'=\'*80}")\n\n    try:\n        # 1. Initialize PPMI Downloader\n        print(f"[STEP 1] Initializing PPMIDownloader for {subject_id}...")\n        ppmi = ppmi_downloader.PPMIDownloader(config_file=CONFIG_FILE, headless=True)\n\n        # 2. Prepare Cohort Metadata\n        print(f"[STEP 2] Preparing cohort metadata for {subject_id}...")\n        cohort = prepare_patient_cohort(subject_id)\n        if cohort.empty:\n            print(f"!!! Skipping {subject_id}: Metadata filtering returned empty result.")\n            df_checkpoint.at[index, \'status\'] = \'failed\'\n            continue\n\n        # 3. Setup Local Workspace\n        subject_dir = f"/content/data/{subject_id}"\n        print(f"[STEP 3] Setting up directory: {subject_dir}")\n        if os.path.exists(subject_dir):\n            shutil.rmtree(subject_dir)\n        os.makedirs(subject_dir, exist_ok=True)\n\n        # 4. Download Imaging Data\n        print(f"[STEP 4] Downloading DICOM scans from PPMI for {subject_id}...")\n        ppmi.download_imaging_data(cohort, destination_dir=subject_dir)\n\n        # 5. DICOM to NIfTI Conversion\n        print(f"[STEP 5] Converting DICOMs to NIfTI using dcm2niix...")\n        conv_cmd = f"dcm2niix -z y -f %p_%t -o {subject_dir} {subject_dir}"\n        os.system(conv_cmd)\n\n        # 6. Construct FastSurfer Commands (returns a list for cross-sectional)\n        print(f"[STEP 6] Constructing session-specific FastSurfer commands...")\n        fs_commands = construct_command(subject_id)\n\n        if not fs_commands:\n            raise RuntimeError(f"No commands generated for {subject_id}. Check if NIfTI files exist in {subject_dir}")\n\n        # 7. Execute Segmentation for each session\n        print(f"[STEP 7] Launching Segmentation Pipeline for {len(fs_commands)} sessions...")\n        for i, cmd in enumerate(fs_commands):\n            print(f"\n--- Processing Session {i+1}/{len(fs_commands)} ---")\n            # We use the cross-sectional robust wrapper\n            run_fastsurfer_robust(cmd)\n\n        # 8. Check Outputs and Save Results (Zips all sessions found)\n        print(f"[STEP 8] Verifying outputs and zipping all session stats...")\n        zip_and_save_stats(subject_id)\n\n        # 9. Update Checkpoint on Success\n        df_checkpoint.at[index, \'status\'] = \'completed\'\n        df_checkpoint.at[index, \'timestamp\'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")\n        print(f"\nSUCCESS: Subject {subject_id} processed completely ({len(fs_commands)} sessions).")\n\n    except Exception as e:\n        print(f"\n!!! CRITICAL ERROR for Subject {subject_id}: {e}")\n        df_checkpoint.at[index, \'status\'] = \'failed\'\n        df_checkpoint.at[index, \'timestamp\'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")\n\n    finally:\n        # Clean up Driver session\n        try:\n            ppmi.driver.quit()\n            print("[INFO] Selenium driver closed.")\n        except:\n            pass\n\n        # Save checkpoint progress to Drive after every subject\n        df_checkpoint.to_csv(checkpoint_path, index=False)\n        print(f"[INFO] Checkpoint saved to Drive.")\n\nprint("\nALL SUBJECTS IN QUEUE PROCESSED.")\n\n'

In [ ]:
import datetime
import os
import shutil

# Reversed Main Processing Loop (v2 with Session Tracking)
# Iterates from the BOTTOM up for subjects marked as 'pending' or 'failed'
for index, row in df_checkpoint[df_checkpoint['status'].isin(['pending', 'failed'])][::-1].iterrows():
    subject_id = str(row['Subject ID'])
    print(f"\n{'='*80}\nSTARTING PROCESS FOR SUBJECT (REVERSED): {subject_id}\n{'='*80}")

    try:
        # 1. Initialize PPMI Downloader
        print(f"[STEP 1] Initializing PPMIDownloader for {subject_id}...")
        ppmi = ppmi_downloader.PPMIDownloader(config_file=CONFIG_FILE, headless=True)

        # 2. Prepare Cohort Metadata
        print(f"[STEP 2] Preparing cohort metadata for {subject_id}...")
        cohort = prepare_patient_cohort(subject_id)
        if cohort.empty:
            print(f"!!! Skipping {subject_id}: Metadata filtering returned empty result.")
            df_checkpoint.at[index, 'status'] = 'failed'
            continue

        # 3. Setup Local Workspace
        subject_dir = f"/content/data/{subject_id}"
        print(f"[STEP 3] Setting up directory: {subject_dir}")
        if os.path.exists(subject_dir):
            shutil.rmtree(subject_dir)
        os.makedirs(subject_dir, exist_ok=True)

        # 4. Download Imaging Data
        print(f"[STEP 4] Downloading DICOM scans from PPMI for {subject_id}...")
        ppmi.download_imaging_data(cohort, destination_dir=subject_dir)

        # 5. DICOM to NIfTI Conversion
        print(f"[STEP 5] Converting DICOMs to NIfTI using dcm2niix...")
        conv_cmd = f"dcm2niix -z y -f %p_%t -o {subject_dir} {subject_dir}"
        os.system(conv_cmd)

        # 6. Construct FastSurfer Commands
        print(f"[STEP 6] Constructing session-specific FastSurfer commands...")
        fs_commands = construct_command(subject_id)

        if not fs_commands:
            raise RuntimeError(f"No commands generated for {subject_id}. Check if NIfTI files exist in {subject_dir}")

        # 7. Execute Segmentation for each session with Success Tracking
        print(f"[STEP 7] Launching Segmentation Pipeline for {len(fs_commands)} sessions...")
        successful_sessions = 0
        for i, cmd in enumerate(fs_commands):
            print(f"\n--- Processing Session {i+1}/{len(fs_commands)} ---")
            try:
                run_fastsurfer_robust_v2(cmd)
                successful_sessions += 1
            except FastSurferSegmentationError as e:
                print(f"\n>>> Skipping session {i+1} due to known error: {e}")

        # 8. Check Outputs and Save Results
        print(f"[STEP 8] Verifying outputs and zipping all session stats...")
        zip_and_save_stats(subject_id)

        # 9. Update Checkpoint with Success Ratio
        status_text = 'completed' if successful_sessions == len(fs_commands) else f"{successful_sessions}/{len(fs_commands)} completed"
        df_checkpoint.at[index, 'status'] = status_text
        df_checkpoint.at[index, 'timestamp'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        print(f"\nDONE: Subject {subject_id} finalized with status: {status_text}")

    except Exception as e:
        print(f"\n!!! CRITICAL ERROR for Subject {subject_id}: {e}")
        df_checkpoint.at[index, 'status'] = 'failed'
        df_checkpoint.at[index, 'timestamp'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    finally:
        # Clean up Driver session
        try:
            ppmi.driver.quit()
            print("[INFO] Selenium driver closed.")
        except:
            pass

        # Save checkpoint progress to Drive after every subject
        df_checkpoint.to_csv(checkpoint_path, index=False)
        print(f"[INFO] Checkpoint saved to Drive.")

print("\nALL SUBJECTS IN QUEUE PROCESSED (REVERSED).")

================================================================================
STARTING PROCESS FOR SUBJECT (REVERSED): 101038
================================================================================
[STEP 1] Initializing PPMIDownloader for 101038...
Using Chrome binary at: /usr/bin/chromium-browser

LivingPark-utils|DEBUG|ppmi_downloader.py:173 in __init__()
                       self.driver.capabilities: {'acceptInsecureCerts': False,
                                                  'browserName': 'chrome',
                                                  'browserVersion': '108.0.5359.40',
                                                  'chrome': {'chromedriverVersion': '108.0.5359.40 '
                                                                                    '(280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689})',
                                                             'userDataDir': '/tmp/.org.chromium.Chromium.Fn2vqA'},
                                                  'goog:chromeOptions': {'debuggerAddress': 'localhost:39797'},
                                                  'networkConnectionEnabled': False,
                                                  'pageLoadStrategy': 'normal',
                                                  'platformName': 'linux',
                                                  'proxy': {},
                                                  'setWindowRect': True,
                                                  'strictFileInteractability': False,
                                                  'timeouts': {'implicit': 0, 'pageLoad': 300000, 'script': 30000},
                                                  'unhandledPromptBehavior': 'dismiss and notify',
                                                  'webauthn:extension:credBlob': True,
                                                  'webauthn:extension:largeBlob': True,
                                                  'webauthn:virtualAuthenticators': True}
LivingPark-utils|DEBUG|ppmi_downloader.py:174 in __init__()
                       self.tempdir: <TemporaryDirectory '/tmp/tmp629m7vvt'>
LivingPark-utils|DEBUG|ppmi_downloader.py:187 in __init__()
                       self.config_file: '.ppmi_config_auto'
                       config_file: '.ppmi_config_auto'

[STEP 2] Preparing cohort metadata for 101038...
Prepared mini-cohort for Subject 101038 with 2 records (using unique Image IDs).
[STEP 3] Setting up directory: /content/data/101038
[STEP 4] Downloading DICOM scans from PPMI for 101038...
Logging in and navigating to search...

LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'ida-cookie-policy-accept'
                       debug_name: 'Cookie Policy'
                       caller: 'ppmi_navigator.py:332 validate_cookie_policy'
                       current_url: 'https://ida.loni.usc.edu/login.jsp?project=PPMI'
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'ida-cookie-policy-accept'
                       debug_name: 'Cookie Policy'
                       caller: 'ppmi_navigator.py:228 click_button'
                       current_url: 'https://ida.loni.usc.edu/login.jsp?project=PPMI'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'ida-menu-option.sub-menu.user'
                       BY: 'class name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'userEmail'
                       BY: 'name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:177 in enter_data()
                       "Enter data": 'Enter data'
                       field: 'userEmail'
                       debug_name: 'Email'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'userPassword'
                       BY: 'name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:177 in enter_data()
                       "Enter data": 'Enter data'
                       field: 'userPassword'
                       debug_name: 'Password'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'button'
                       BY: 'tag name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'button'
                       debug_name: 'Login button'
                       caller: 'ppmi_navigator.py:389 login'
                       current_url: 'https://ida.loni.usc.edu/explore/jsp/common/login.jsp?project=PPMI'
LivingPark-utils|INFO|'Login Successful'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:827 in Search_AdvancedImageSearchbeta_SelectAll()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'advResultSelectAll'
                       debug_name: 'Select All'
                       caller: 'ppmi_navigator.py:828 Search_AdvancedImageSearchbeta_SelectAll'
                       current_url: 'https://ida.loni.usc.edu/pages/access/search.jsp'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="d4280419-61ef-4784-971c-dcfca96902be")>
                       select_all.is_selected(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="68e7304bdd9fa96906f99ac58ac36546", element="278bfca8-8130-486a-807e-c17df8a1295d")>
                       add_to_collection.is_enabled(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True

Navigating to Export page for 101038...

--- Attempt 1 ---
Selecting target scans via scrolling...
  Checked: ('101038', 'V04', '3D T1')
  Checked: ('101038', 'BL', '3D T1')
All target scans successfully selected.
Initiating download overlay...
Found 2 zip link(s) with labels: ['Zip File', 'Zip File']
  Triggered download for: Zip File...
  Triggered download for: Zip File...
  Metadata download triggered.
Waiting for files to finish downloading...

  0%|          | 0/4 [00:00<?, ?it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/101038/3D_T1/2022-06-09_16_58_22.0/I1616556/S1155943I1616556.xml', 'PPMI/101038/3D_T1/2021-04-27_13_12_13.0/I11081665/S5848090I11081665.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded file {filename}": 'Successfully downloaded file blank.csv'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/101038/3D_T1/2022-06-09_16_58_22.0/I1616556/PPMI_101038_MR_3D_T1__br_raw_20220826134058361_50_S1155943_I1616556.dcm', 'PPMI/101038/3D_T1/2022-06-09_16_58_22.0/I1616556/PPMI_101038_MR_3D_T1__br_raw_20220826134102790_27_S1155943_I1616556.dcm']...'
 75%|███████▌  | 3/4 [00:00<00:00, 16.10it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/101038/3D_T1/2021-04-27_13_12_13.0/I11081665/PPMI_101038_MR_3D_T1__br_raw_20241223094644238_97.dcm', 'PPMI/101038/3D_T1/2021-04-27_13_12_13.0/I11081665/PPMI_101038_MR_3D_T1__br_raw_20241223094644601_98.dcm']...'
100%|██████████| 4/4 [00:00<00:00, 10.70it/s]

Download and extraction complete.
[STEP 5] Converting DICOMs to NIfTI using dcm2niix...
[STEP 6] Constructing session-specific FastSurfer commands...
[STEP 7] Launching Segmentation Pipeline for 2 sessions...

--- Processing Session 1/2 ---
Executing command:
export FASTSURFER_HOME=/content/fastsurfer/; /content/fastsurfer//run_fastsurfer.sh --t1 /content/data/101038/Anon_20210427130053.nii.gz --sd /content/fastsurfer_seg --sid 101038_Anon_20210427130053 --seg_only --py python3 --3T --allow_root

--- Output Log (Robust v2.2) ---
time command failing, not using time...
WARNING: You are trying to run 'run_fastsurfer.sh' as root. We recommend to avoid
  running FastSurfer as root, because it will lead to files and folders created as root.
  If you are running FastSurfer in a docker container, you can specify the user
  with '-u $(id -u):$(id -g)' (see https://docs.docker.com/engine/reference/run/#user).
=========================================================
Start of the log for a new run_fastsurfer.sh invocation
=========================================================
Version: 2.4.2+7e53343
Sun Apr  5 10:35:48 PM UTC 2026

Log file for FastSurfer pipeline, run_fastsurfer.sh and segmentation(s)
python3 /content/fastsurfer//FastSurferCNN/run_prediction.py --t1 /content/data/101038/Anon_20210427130053.nii.gz --asegdkt_segfile /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig.mgz --brainmask_name /content/fastsurfer_seg/101038_Anon_20210427130053/mri/mask.mgz --aseg_name /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aseg.auto_noCCseg.mgz --sid 101038_Anon_20210427130053 --seg_log /content/fastsurfer_seg/101038_Anon_20210427130053/scripts/deep-seg.log --vox_size min --batch_size 1 --viewagg_device auto --device auto --threads 1 --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  647]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/101038/Anon_20210427130053.nii.gz
[INFO: common.py:  979]: Output will be stored in Subjects Directory: /content/fastsurfer_seg
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: run_prediction.py:  245]: Running view aggregation on cuda
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_coronal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_sagittal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_axial_v2.0.0.pkl
[INFO: run_prediction.py:  324]: Successfully loaded image from /content/data/101038/Anon_20210427130053.nii.gz.
[INFO: run_prediction.py:  441]: Output image directory /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig does not exist. Creating it now...
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig/001.mgz.
[INFO: conform.py:  823]: The input image is not conformed.
[INFO: conform.py:  826]: A min-conformedconformed image must satisfy the following criteria:
[INFO: conform.py:  828]:  - Number of Dimensions 3        : True
[INFO: conform.py:  828]:  - Dimensions 256x256x256        : BUT image dimensions (192, 256, 256)
[INFO: conform.py:  828]:  - Voxel Size 1.0x1.0x1.0        : True
[INFO: conform.py:  828]:  - Orientation LIA               : BUT strict: [[1. 0. 0.] [0. 1. 0.] [0. 0. 1.]]
[INFO: conform.py:  828]:  - Dtype uint8                   : BUT dtype int16
[INFO: run_prediction.py:  337]: Conforming image
Input:    min: 0.0  max: 189657.4453125
rescale:  min: 0.0  max: 129156.72025781249  scale: 0.0019743455817938784
Output:   min: 0.0  max: 255.0
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig.mgz.
[INFO: run_prediction.py:  400]: Run coronal prediction
[INFO: dataset.py:   78]: Loading Coronal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  0%|          | 1/256 [00:00<01:34,  2.70batch/s]
  3%|▎         | 8/256 [00:00<00:11, 20.74batch/s]
  6%|▌         | 15/256 [00:00<00:07, 33.59batch/s]
  9%|▊         | 22/256 [00:00<00:05, 42.97batch/s]
 11%|█▏        | 29/256 [00:00<00:04, 49.86batch/s]
 14%|█▍        | 36/256 [00:00<00:04, 54.69batch/s]
 17%|█▋        | 43/256 [00:01<00:03, 57.99batch/s]
 20%|█▉        | 50/256 [00:01<00:03, 60.11batch/s]
 22%|██▏       | 57/256 [00:01<00:03, 61.72batch/s]
 25%|██▌       | 64/256 [00:01<00:03, 62.64batch/s]
 28%|██▊       | 71/256 [00:01<00:02, 63.26batch/s]
 30%|███       | 78/256 [00:01<00:02, 63.97batch/s]
 33%|███▎      | 85/256 [00:01<00:02, 64.04batch/s]
 36%|███▌      | 92/256 [00:01<00:02, 64.44batch/s]
 39%|███▊      | 99/256 [00:01<00:02, 64.98batch/s]
 41%|████▏     | 106/256 [00:01<00:02, 65.44batch/s]
 44%|████▍     | 113/256 [00:02<00:02, 65.80batch/s]
 47%|████▋     | 120/256 [00:02<00:02, 65.92batch/s]
 50%|████▉     | 127/256 [00:02<00:01, 65.55batch/s]
 52%|█████▏    | 134/256 [00:02<00:01, 65.31batch/s]
 55%|█████▌    | 141/256 [00:02<00:01, 65.27batch/s]
 58%|█████▊    | 148/256 [00:02<00:01, 65.00batch/s]
 61%|██████    | 155/256 [00:02<00:01, 64.88batch/s]
 63%|██████▎   | 162/256 [00:02<00:01, 65.23batch/s]
 66%|██████▌   | 169/256 [00:02<00:01, 65.44batch/s]
 69%|██████▉   | 176/256 [00:03<00:01, 65.29batch/s]
 71%|███████▏  | 183/256 [00:03<00:01, 64.85batch/s]
 74%|███████▍  | 190/256 [00:03<00:01, 64.17batch/s]
 77%|███████▋  | 197/256 [00:03<00:00, 64.26batch/s]
 80%|███████▉  | 204/256 [00:03<00:00, 64.55batch/s]
 82%|████████▏ | 211/256 [00:03<00:00, 64.45batch/s]
 85%|████████▌ | 218/256 [00:03<00:00, 64.52batch/s]
 88%|████████▊ | 225/256 [00:03<00:00, 64.89batch/s]
 91%|█████████ | 232/256 [00:03<00:00, 65.16batch/s]
 93%|█████████▎| 239/256 [00:04<00:00, 65.39batch/s]
 96%|█████████▌| 246/256 [00:04<00:00, 65.60batch/s]
 99%|█████████▉| 253/256 [00:04<00:00, 65.55batch/s]
100%|██████████| 256/256 [00:04<00:00, 59.76batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for coronal successful
[INFO: inference.py:  469]: Coronal inference on /content/data/101038/Anon_20210427130053.nii.gz finished in 4.2875 seconds
[INFO: run_prediction.py:  400]: Run sagittal prediction
[INFO: dataset.py:   69]: Loading Sagittal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  2%|▏         | 6/256 [00:00<00:04, 58.41batch/s]
  5%|▌         | 13/256 [00:00<00:04, 60.21batch/s]
  8%|▊         | 20/256 [00:00<00:03, 60.57batch/s]
 11%|█         | 27/256 [00:00<00:03, 60.92batch/s]
 13%|█▎        | 34/256 [00:00<00:03, 61.13batch/s]
 16%|█▌        | 41/256 [00:00<00:03, 61.31batch/s]
 19%|█▉        | 48/256 [00:00<00:03, 61.10batch/s]
 21%|██▏       | 55/256 [00:00<00:03, 60.69batch/s]
 24%|██▍       | 62/256 [00:01<00:03, 60.66batch/s]
 27%|██▋       | 69/256 [00:01<00:03, 60.55batch/s]
 30%|██▉       | 76/256 [00:01<00:02, 60.79batch/s]
 32%|███▏      | 83/256 [00:01<00:02, 60.49batch/s]
 35%|███▌      | 90/256 [00:01<00:02, 60.63batch/s]
 38%|███▊      | 97/256 [00:01<00:02, 60.81batch/s]
 41%|████      | 104/256 [00:01<00:02, 61.09batch/s]
 43%|████▎     | 111/256 [00:01<00:02, 60.78batch/s]
 46%|████▌     | 118/256 [00:01<00:02, 60.86batch/s]
 49%|████▉     | 125/256 [00:02<00:02, 60.67batch/s]
 52%|█████▏    | 132/256 [00:02<00:02, 60.71batch/s]
 54%|█████▍    | 139/256 [00:02<00:01, 60.61batch/s]
 57%|█████▋    | 146/256 [00:02<00:01, 60.60batch/s]
 60%|█████▉    | 153/256 [00:02<00:01, 60.81batch/s]
 62%|██████▎   | 160/256 [00:02<00:01, 60.73batch/s]
 65%|██████▌   | 167/256 [00:02<00:01, 60.83batch/s]
 68%|██████▊   | 174/256 [00:02<00:01, 61.02batch/s]
 71%|███████   | 181/256 [00:02<00:01, 60.73batch/s]
 73%|███████▎  | 188/256 [00:03<00:01, 60.89batch/s]
 76%|███████▌  | 195/256 [00:03<00:01, 60.97batch/s]
 79%|███████▉  | 202/256 [00:03<00:00, 61.12batch/s]
 82%|████████▏ | 209/256 [00:03<00:00, 60.99batch/s]
 84%|████████▍ | 216/256 [00:03<00:00, 61.21batch/s]
 87%|████████▋ | 223/256 [00:03<00:00, 61.18batch/s]
 90%|████████▉ | 230/256 [00:03<00:00, 60.66batch/s]
 93%|█████████▎| 237/256 [00:03<00:00, 60.47batch/s]
 95%|█████████▌| 244/256 [00:04<00:00, 60.81batch/s]
 98%|█████████▊| 251/256 [00:04<00:00, 60.81batch/s]
100%|██████████| 256/256 [00:04<00:00, 60.79batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for sagittal successful
[INFO: inference.py:  469]: Sagittal inference on /content/data/101038/Anon_20210427130053.nii.gz finished in 4.2124 seconds
[INFO: run_prediction.py:  400]: Run axial prediction
[INFO: dataset.py:   74]: Loading Axial with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:03, 65.62batch/s]
  5%|▌         | 14/256 [00:00<00:03, 65.25batch/s]
  8%|▊         | 21/256 [00:00<00:03, 65.10batch/s]
 11%|█         | 28/256 [00:00<00:03, 64.76batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 64.72batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 64.92batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 64.85batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 65.02batch/s]
 25%|██▍       | 63/256 [00:00<00:02, 64.70batch/s]
 27%|██▋       | 70/256 [00:01<00:02, 64.55batch/s]
 30%|███       | 77/256 [00:01<00:02, 64.20batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 64.08batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 64.13batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 64.29batch/s]
 41%|████      | 105/256 [00:01<00:02, 64.71batch/s]
 44%|████▍     | 112/256 [00:01<00:02, 64.53batch/s]
 46%|████▋     | 119/256 [00:01<00:02, 64.69batch/s]
 49%|████▉     | 126/256 [00:01<00:01, 65.02batch/s]
 52%|█████▏    | 133/256 [00:02<00:01, 65.02batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 65.04batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 65.03batch/s]
 60%|██████    | 154/256 [00:02<00:01, 65.10batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 65.10batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 65.37batch/s]
 68%|██████▊   | 175/256 [00:02<00:01, 65.67batch/s]
 71%|███████   | 182/256 [00:02<00:01, 65.63batch/s]
 74%|███████▍  | 189/256 [00:02<00:01, 65.54batch/s]
 77%|███████▋  | 196/256 [00:03<00:00, 65.58batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 65.22batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 65.09batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 65.19batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 65.02batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 65.02batch/s]
 93%|█████████▎| 238/256 [00:03<00:00, 65.32batch/s]
 96%|█████████▌| 245/256 [00:03<00:00, 65.20batch/s]
 98%|█████████▊| 252/256 [00:03<00:00, 64.93batch/s]
100%|██████████| 256/256 [00:03<00:00, 64.96batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for axial successful
[INFO: inference.py:  469]: Axial inference on /content/data/101038/Anon_20210427130053.nii.gz finished in 3.9422 seconds
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aparc.DKTatlas+aseg.deep.mgz.
[INFO: run_prediction.py:  724]: Creating brainmask based on segmentation...
Creating dilated mask ...
Frontal region special treatment:  21400
  Found 1 connected component(s)!
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/101038_Anon_20210427130053/mri/mask.mgz.
[INFO: run_prediction.py:  743]: Creating aseg based on segmentation...
Reducing to aseg ...
FlipWM: rh 0 and lh 0 flipped.
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aseg.auto_noCCseg.mgz.
[INFO: run_prediction.py:  762]: Running volume-based QC check on segmentation...
Checking total volume ...
Voxel size in mm3: 1.0
Total segmentation volume in liter: 1.28
INFO: Running N4 bias-field correction...
python3 /content/fastsurfer//recon_surf/N4_bias_correct.py --in /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig.mgz --rescale /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz --aseg /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aseg.auto_noCCseg.mgz --threads 1

N4 Bias Correction Parameters:

- verbosity: -1
- input volume: /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig.mgz
- output volume: do not save
- rescaled volume: /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz
- mask: default (>0)
- aseg: /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aseg.auto_noCCseg.mgz
- shrink factor: 4
- number fitting levels: 4
- number iterations: 50
- convergence threshold: 0.0
- threads: 1
read MGZ (FreeSurfer) image via nibabel...
executing N4 correction ...
- mask: ones (default)
normalize WM to 105.0 (find WM from aseg)
read MGZ (FreeSurfer) image via nibabel...
- source white matter intensity: 114.57
- m: 0.8903
converting rescaled to UCHAR
writing PosixPath: /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz
write MGZ (FreeSurfer) image via nibabel...
python3 /content/fastsurfer//FastSurferCNN/segstats.py --segfile /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aparc.DKTatlas+aseg.deep.mgz --segstatsfile /content/fastsurfer_seg/101038_Anon_20210427130053/stats/aseg+DKT.stats --normfile /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz --threads 1 --empty --excludeid 0 --sd /content/fastsurfer_seg --sid 101038_Anon_20210427130053 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /content/fastsurfer//FastSurferCNN/config/FreeSurferColorLUT.txt measures --compute Mask(/content/fastsurfer_seg/101038_Anon_20210427130053/mri/mask.mgz) BrainSeg BrainSegNotVent SupraTentorial SupraTentorialNotVent SubCortGray rhCerebralWhiteMatter lhCerebralWhiteMatter CerebralWhiteMatter
None of the labels [251, 252, 253, 254, 255] for merged label 10007 exist in the segmentation.
Partial volume stats for 100 labels written to /content/fastsurfer_seg/101038_Anon_20210427130053/stats/aseg+DKT.stats.
Calculation took 13.29 seconds using up to 1 threads.
python3 /content/fastsurfer//CerebNet/run_prediction.py --t1 /content/data/101038/Anon_20210427130053.nii.gz --asegdkt_segfile /content/fastsurfer_seg/101038_Anon_20210427130053/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig.mgz --cereb_segfile /content/fastsurfer_seg/101038_Anon_20210427130053/mri/cerebellum.CerebNet.nii.gz --seg_log /content/fastsurfer_seg/101038_Anon_20210427130053/scripts/deep-seg.log --async_io --batch_size 1 --viewagg_device auto --device auto --threads 1 --norm_name /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz --cereb_statsfile /content/fastsurfer_seg/101038_Anon_20210427130053/stats/cerebellum.CerebNet.stats --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  154]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/101038/Anon_20210427130053.nii.gz
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  434]: 26-04-05_22:40:21

Subject:   0%|          | 0/1 [00:00<?, ?it/s]


Subject:   0%|          | 0/1 [00:04<?, ?it/s][INFO: inference.py:  357]: Saving CerebNet cerebellum segmentation at /content/fastsurfer_seg/101038_Anon_20210427130053/mri/cerebellum.CerebNet.nii.gz



Subject:   0%|          | 0/1 [00:05<?, ?it/s][INFO: inference.py:  512]: Subject 1/1 with id 'Anon_20210427130053.nii.gz' processed in 4.44 sec.

Subject: 100%|██████████| 1/1 [00:05<00:00,  5.62s/it]
Subject: 100%|██████████| 1/1 [00:05<00:00,  5.62s/it]
python3 /content/fastsurfer//HypVINN/run_prediction.py --sd /content/fastsurfer_seg --sid 101038_Anon_20210427130053 --reg_mode coreg --threads 1 --async_io --batch_size 1 --seg_log /content/fastsurfer_seg/101038_Anon_20210427130053/scripts/deep-seg.log --device auto --viewagg_device auto --t1 /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz
[INFO: run_prediction.py:  437]: Checking or downloading default checkpoints ...
[INFO: mode_config.py:   49]: Setting up input mode...
[INFO: run_prediction.py:  282]: Running HypVINN segmentation pipeline on subject 101038_Anon_20210427130053
[INFO: run_prediction.py:  285]: Output will be stored in: /content/fastsurfer_seg/101038_Anon_20210427130053
[INFO: run_prediction.py:  286]: T1 image input /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz
[INFO: run_prediction.py:  287]: T2 image input None
[INFO: run_prediction.py:  306]: Setting up HypVINN run
[INFO: run_prediction.py:  311]: axial model configuration from /content/fastsurfer/HypVINN/config/HypVINN_axial_v1.1.0.yaml
[INFO: run_prediction.py:  311]: coronal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_coronal_v1.1.0.yaml
[INFO: run_prediction.py:  311]: sagittal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_sagittal_v1.1.0.yaml
[INFO: run_prediction.py:  505]: Loading T1 image from : /content/fastsurfer_seg/101038_Anon_20210427130053/mri/orig_nu.mgz
Input:    min: 3  max: 245
rescale:  min: 3.0  max: 180.628  scale: 1.4355844799243365
Output:   min: 0.0  max: 255.0
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  109]: Running view aggregation on cuda
[INFO: run_prediction.py:  340]: ------------------------------------------------------------------------------------------------------------------------
[INFO: run_prediction.py:  341]: Evaluating hypothalamus model on 101038_Anon_20210427130053
[INFO: run_prediction.py:  350]: Scale factor: (np.float32(1.0), np.float32(1.0), np.float32(1.0))
[INFO: run_prediction.py:  609]: Evaluating axial model, cpkt :/content/fastsurfer/checkpoints/HypVINN_axial_v1.1.0.pkl
[INFO: inference.py:  183]: Loading checkpoint /content/fastsurfer/checkpoints/HypVINN_axial_v1.1.0.pkl
[INFO: dataset.py:  166]: Loading t1 axial with input voxelsize (np.float32(1.0), np.float32(1.0))
[INFO: dataset.py:  114]: Successfully loaded Image from 101038_Anon_20210427130053 for axial model
[INFO: dataset.py:  126]: For inference T1 block weight was set to: 1.0 and the T2 block was set to: 0.0

  0%|          | 0/256 [00:00<?, ?it/s]
  0%|          | 1/256 [00:00<01:33,  2.72it/s]
  2%|▏         | 6/256 [00:00<00:16, 15.21it/s]
  4%|▍         | 11/256 [00:00<00:10, 23.90it/s]
  6%|▋         | 16/256 [00:00<00:07, 30.03it/s]
  8%|▊         | 21/256 [00:00<00:06, 34.29it/s]
 10%|█         | 26/256 [00:00<00:06, 37.23it/s]
 12%|█▏        | 31/256 [00:01<00:05, 38.48it/s]
 14%|█▍        | 36/256 [00:01<00:05, 40.16it/s]
 16%|█▌        | 41/256 [00:01<00:05, 41.26it/s]
 18%|█▊        | 46/256 [00:01<00:04, 42.43it/s]
 20%|█▉        | 51/256 [00:01<00:04, 43.08it/s]
 22%|██▏       | 56/256 [00:01<00:04, 43.63it/s]
 24%|██▍       | 61/256 [00:01<00:04, 44.03it/s]
 26%|██▌       | 66/256 [00:01<00:04, 44.28it/s]
 28%|██▊       | 71/256 [00:01<00:04, 44.46it/s]
 30%|██▉       | 76/256 [00:02<00:04, 44.50it/s]
 32%|███▏      | 81/256 [00:02<00:03, 44.50it/s]
 34%|███▎      | 86/256 [00:02<00:03, 44.42it/s]
 36%|███▌      | 91/256 [00:02<00:03, 44.38it/s]
 38%|███▊      | 96/256 [00:02<00:03, 44.39it/s]
 39%|███▉      | 101/256 [00:02<00:03, 44.49it/s]
 41%|████▏     | 106/256 [00:02<00:03, 44.68it/s]

## Processing of manual downloads for bugged entries

In [ ]:
import os
import shutil
import zipfile
import glob

# --- Configuration ---
subject_id = "3866"
working_dir = f"/content/data/{subject_id}"
zip_scan = "/content/3866.zip"
zip_meta = "/content/3866_IDA_Metadata.zip"

# 1. Unpack uploaded files
print(f"--- Unpacking data for {subject_id} ---")
if os.path.exists(working_dir): shutil.rmtree(working_dir)
os.makedirs(working_dir, exist_ok=True)

for z in [zip_scan, zip_meta]:
    if os.path.exists(z):
        with zipfile.ZipFile(z, 'r') as zip_ref:
            zip_ref.extractall(working_dir)
        print(f"  Unzipped: {z}")
    else:
        print(f"  Warning: {z} not found in /content/")

# 2. Convert DICOM to NIfTI
print("--- Converting DICOMs ---")
os.system(f"dcm2niix -z y -f %p_%t -o {working_dir} {working_dir}")

# 3. Construct and Run FastSurfer
print("--- Running FastSurfer ---")
# We assume the conversion produced at least one .nii.gz file
nifti_files = sorted(glob.glob(os.path.join(working_dir, "*.nii.gz")))

if not nifti_files:
    print("Error: No NIfTI files found after conversion.")
else:
    # Process the first valid NIfTI found
    img = nifti_files[0]
    session_id = f"{subject_id}_manual_fix"
    fs_cmd = (
        f"export FASTSURFER_HOME={FASTSURFER_HOME}; "
        f"{FASTSURFER_HOME}/run_fastsurfer.sh "
        f"--t1 {img} --sd {SETUP_DIR}fastsurfer_seg --sid {session_id} "
        f"--seg_only --py python3 --3T --allow_root"
    )

    try:
        # Using the robust v2 wrapper to catch errors
        run_fastsurfer_robust_v2(fs_cmd)

        # 4. Custom Merging Logic to Drive
        print("--- Merging new stats into Drive Zip ---")
        drive_zip = f"/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/stats_{subject_id}.zip"
        staging_dir = f"/content/merge_staging_{subject_id}"
        if os.path.exists(staging_dir): shutil.rmtree(staging_dir)
        os.makedirs(staging_dir, exist_ok=True)

        # Extract old if exists
        if os.path.exists(drive_zip):
            with zipfile.ZipFile(drive_zip, 'r') as zr: zr.extractall(staging_dir)
            print("  Extracted existing zip from Drive.")

        # Copy new stats
        new_stats_path = os.path.join(SETUP_DIR, "fastsurfer_seg", session_id, "stats")
        if os.path.exists(new_stats_path):
            shutil.copytree(new_stats_path, os.path.join(staging_dir, session_id))

            # Re-zip
            shutil.make_archive(f"/content/stats_{subject_id}", 'zip', staging_dir)
            shutil.move(f"/content/stats_{subject_id}.zip", drive_zip)
            print(f"SUCCESS: Combined stats saved to {drive_zip}")
        else:
            print("Error: New stats folder not found. Check FastSurfer logs.")

    except Exception as e:
        print(f"Processing failed: {e}")

--- Unpacking data for 3866 ---
  Unzipped: /content/3866.zip
  Unzipped: /content/3866_IDA_Metadata.zip
--- Converting DICOMs ---
--- Running FastSurfer ---
Executing command:
export FASTSURFER_HOME=/content/fastsurfer/; /content/fastsurfer//run_fastsurfer.sh --t1 /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz --sd /content/fastsurfer_seg --sid 3866_manual_fix --seg_only --py python3 --3T --allow_root

--- Output Log (Robust v2.2) ---
time command failing, not using time...
WARNING: You are trying to run 'run_fastsurfer.sh' as root. We recommend to avoid
  running FastSurfer as root, because it will lead to files and folders created as root.
  If you are running FastSurfer in a docker container, you can specify the user
  with '-u $(id -u):$(id -g)' (see https://docs.docker.com/engine/reference/run/#user).
=========================================================
Start of the log for a new run_fastsurfer.sh invocation
=========================================================
Version: 2.4.2+7e53343
Sun Apr  5 10:47:54 PM UTC 2026

Log file for FastSurfer pipeline, run_fastsurfer.sh and segmentation(s)
python3 /content/fastsurfer//FastSurferCNN/run_prediction.py --t1 /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz --asegdkt_segfile /content/fastsurfer_seg/3866_manual_fix/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/3866_manual_fix/mri/orig.mgz --brainmask_name /content/fastsurfer_seg/3866_manual_fix/mri/mask.mgz --aseg_name /content/fastsurfer_seg/3866_manual_fix/mri/aseg.auto_noCCseg.mgz --sid 3866_manual_fix --seg_log /content/fastsurfer_seg/3866_manual_fix/scripts/deep-seg.log --vox_size min --batch_size 1 --viewagg_device auto --device auto --threads 1 --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  647]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz
[INFO: common.py:  979]: Output will be stored in Subjects Directory: /content/fastsurfer_seg
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: run_prediction.py:  245]: Running view aggregation on cuda
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_coronal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_sagittal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_axial_v2.0.0.pkl
[INFO: run_prediction.py:  324]: Successfully loaded image from /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz.
[INFO: run_prediction.py:  441]: Output image directory /content/fastsurfer_seg/3866_manual_fix/mri/orig does not exist. Creating it now...
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3866_manual_fix/mri/orig/001.mgz.
[INFO: conform.py:  823]: The input image is not conformed.
[INFO: conform.py:  826]: A min-conformedconformed image must satisfy the following criteria:
[INFO: conform.py:  828]:  - Number of Dimensions 3        : True
[INFO: conform.py:  828]:  - Dimensions 256x256x256        : BUT image dimensions (240, 256, 176)
[INFO: conform.py:  828]:  - Voxel Size 1.0x1.0x1.0        : True
[INFO: conform.py:  828]:  - Orientation LIA               : BUT strict: [[-1.44e-01 3.93e-02 9.89e-01] [-9.90e-01 -5.74e-03 -1.44e-01] [ 3.67e-08 9.99e-01 -3.97e-02]]
[INFO: conform.py:  828]:  - Dtype uint8                   : BUT dtype int16
[INFO: run_prediction.py:  337]: Conforming image
Input:    min: 0  max: 1044
rescale:  min: 0.0  max: 623.268  scale: 0.40913379156317986
Output:   min: 0.0  max: 255.0
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3866_manual_fix/mri/orig.mgz.
[INFO: run_prediction.py:  400]: Run coronal prediction
[INFO: dataset.py:   78]: Loading Coronal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  0%|          | 1/256 [00:00<01:35,  2.67batch/s]
  3%|▎         | 7/256 [00:00<00:13, 18.42batch/s]
  5%|▌         | 14/256 [00:00<00:07, 32.14batch/s]
  8%|▊         | 21/256 [00:00<00:05, 41.95batch/s]
 11%|█         | 28/256 [00:00<00:04, 48.58batch/s]
 14%|█▎        | 35/256 [00:00<00:04, 53.20batch/s]
 16%|█▋        | 42/256 [00:01<00:03, 56.39batch/s]
 19%|█▉        | 49/256 [00:01<00:03, 58.67batch/s]
 22%|██▏       | 56/256 [00:01<00:03, 59.98batch/s]
 25%|██▍       | 63/256 [00:01<00:03, 60.86batch/s]
 27%|██▋       | 70/256 [00:01<00:03, 61.58batch/s]
 30%|███       | 77/256 [00:01<00:02, 62.60batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 63.23batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 63.47batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 63.44batch/s]
 41%|████      | 105/256 [00:02<00:02, 63.60batch/s]
 44%|████▍     | 112/256 [00:02<00:02, 63.74batch/s]
 46%|████▋     | 119/256 [00:02<00:02, 63.70batch/s]
 49%|████▉     | 126/256 [00:02<00:02, 63.70batch/s]
 52%|█████▏    | 133/256 [00:02<00:01, 63.92batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 64.23batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 64.63batch/s]
 60%|██████    | 154/256 [00:02<00:01, 64.59batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 64.88batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 64.95batch/s]
 68%|██████▊   | 175/256 [00:03<00:01, 65.17batch/s]
 71%|███████   | 182/256 [00:03<00:01, 65.11batch/s]
 74%|███████▍  | 189/256 [00:03<00:01, 64.38batch/s]
 77%|███████▋  | 196/256 [00:03<00:00, 64.39batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 64.23batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 64.12batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 64.42batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 64.55batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 64.75batch/s]
 93%|█████████▎| 238/256 [00:04<00:00, 64.73batch/s]
 96%|█████████▌| 245/256 [00:04<00:00, 63.89batch/s]
 98%|█████████▊| 252/256 [00:04<00:00, 63.80batch/s]
100%|██████████| 256/256 [00:04<00:00, 58.79batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for coronal successful
[INFO: inference.py:  469]: Coronal inference on /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz finished in 4.3582 seconds
[INFO: run_prediction.py:  400]: Run sagittal prediction
[INFO: dataset.py:   69]: Loading Sagittal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:04, 60.64batch/s]
  5%|▌         | 14/256 [00:00<00:03, 60.59batch/s]
  8%|▊         | 21/256 [00:00<00:03, 60.87batch/s]
 11%|█         | 28/256 [00:00<00:03, 60.66batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 60.88batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 60.79batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 60.72batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 60.57batch/s]
 25%|██▍       | 63/256 [00:01<00:03, 60.17batch/s]
 27%|██▋       | 70/256 [00:01<00:03, 60.29batch/s]
 30%|███       | 77/256 [00:01<00:02, 60.23batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 60.20batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 60.32batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 60.44batch/s]
 41%|████      | 105/256 [00:01<00:02, 60.53batch/s]
 44%|████▍     | 112/256 [00:01<00:02, 60.16batch/s]
 46%|████▋     | 119/256 [00:01<00:02, 60.02batch/s]
 49%|████▉     | 126/256 [00:02<00:02, 59.60batch/s]
 52%|█████▏    | 132/256 [00:02<00:02, 59.59batch/s]
 54%|█████▍    | 138/256 [00:02<00:01, 59.48batch/s]
 57%|█████▋    | 145/256 [00:02<00:01, 59.78batch/s]
 59%|█████▉    | 152/256 [00:02<00:01, 59.97batch/s]
 62%|██████▏   | 159/256 [00:02<00:01, 60.02batch/s]
 65%|██████▍   | 166/256 [00:02<00:01, 60.03batch/s]
 68%|██████▊   | 173/256 [00:02<00:01, 59.99batch/s]
 70%|███████   | 180/256 [00:02<00:01, 60.06batch/s]
 73%|███████▎  | 187/256 [00:03<00:01, 59.86batch/s]
 75%|███████▌  | 193/256 [00:03<00:01, 59.59batch/s]
 78%|███████▊  | 199/256 [00:03<00:00, 59.66batch/s]
 80%|████████  | 205/256 [00:03<00:00, 59.67batch/s]
 82%|████████▏ | 211/256 [00:03<00:00, 59.64batch/s]
 85%|████████▌ | 218/256 [00:03<00:00, 59.67batch/s]
 88%|████████▊ | 225/256 [00:03<00:00, 60.11batch/s]
 91%|█████████ | 232/256 [00:03<00:00, 60.24batch/s]
 93%|█████████▎| 239/256 [00:03<00:00, 60.48batch/s]
 96%|█████████▌| 246/256 [00:04<00:00, 60.58batch/s]
 99%|█████████▉| 253/256 [00:04<00:00, 60.78batch/s]
100%|██████████| 256/256 [00:04<00:00, 60.21batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for sagittal successful
[INFO: inference.py:  469]: Sagittal inference on /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz finished in 4.2532 seconds
[INFO: run_prediction.py:  400]: Run axial prediction
[INFO: dataset.py:   74]: Loading Axial with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:03, 66.65batch/s]
  5%|▌         | 14/256 [00:00<00:03, 65.50batch/s]
  8%|▊         | 21/256 [00:00<00:03, 65.65batch/s]
 11%|█         | 28/256 [00:00<00:03, 65.79batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 65.89batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 65.75batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 65.74batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 65.80batch/s]
 25%|██▍       | 63/256 [00:00<00:02, 65.65batch/s]
 27%|██▋       | 70/256 [00:01<00:02, 64.97batch/s]
 30%|███       | 77/256 [00:01<00:02, 63.12batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 63.63batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 64.10batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 64.19batch/s]
 41%|████      | 105/256 [00:01<00:02, 64.31batch/s]
 44%|████▍     | 112/256 [00:01<00:02, 64.56batch/s]
 46%|████▋     | 119/256 [00:01<00:02, 64.76batch/s]
 49%|████▉     | 126/256 [00:01<00:02, 64.71batch/s]
 52%|█████▏    | 133/256 [00:02<00:01, 64.68batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 64.76batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 64.64batch/s]
 60%|██████    | 154/256 [00:02<00:01, 64.89batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 65.08batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 65.28batch/s]
 68%|██████▊   | 175/256 [00:02<00:01, 65.31batch/s]
 71%|███████   | 182/256 [00:02<00:01, 65.27batch/s]
 74%|███████▍  | 189/256 [00:02<00:01, 63.97batch/s]
 77%|███████▋  | 196/256 [00:03<00:00, 64.10batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 64.32batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 64.38batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 64.50batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 64.70batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 64.42batch/s]
 93%|█████████▎| 238/256 [00:03<00:00, 64.23batch/s]
 96%|█████████▌| 245/256 [00:03<00:00, 63.83batch/s]
 98%|█████████▊| 252/256 [00:03<00:00, 63.26batch/s]
100%|██████████| 256/256 [00:03<00:00, 64.59batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for axial successful
[INFO: inference.py:  469]: Axial inference on /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz finished in 3.9647 seconds
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3866_manual_fix/mri/aparc.DKTatlas+aseg.deep.mgz.
[INFO: run_prediction.py:  724]: Creating brainmask based on segmentation...
Creating dilated mask ...
Frontal region special treatment:  17980
  Found 1 connected component(s)!
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3866_manual_fix/mri/mask.mgz.
[INFO: run_prediction.py:  743]: Creating aseg based on segmentation...
Reducing to aseg ...
FlipWM: rh 0 and lh 0 flipped.
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3866_manual_fix/mri/aseg.auto_noCCseg.mgz.
[INFO: run_prediction.py:  762]: Running volume-based QC check on segmentation...
Checking total volume ...
Voxel size in mm3: 1.0
Total segmentation volume in liter: 0.95
INFO: Running N4 bias-field correction...
python3 /content/fastsurfer//recon_surf/N4_bias_correct.py --in /content/fastsurfer_seg/3866_manual_fix/mri/orig.mgz --rescale /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz --aseg /content/fastsurfer_seg/3866_manual_fix/mri/aseg.auto_noCCseg.mgz --threads 1

N4 Bias Correction Parameters:

- verbosity: -1
- input volume: /content/fastsurfer_seg/3866_manual_fix/mri/orig.mgz
- output volume: do not save
- rescaled volume: /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz
- mask: default (>0)
- aseg: /content/fastsurfer_seg/3866_manual_fix/mri/aseg.auto_noCCseg.mgz
- shrink factor: 4
- number fitting levels: 4
- number iterations: 50
- convergence threshold: 0.0
- threads: 1
read MGZ (FreeSurfer) image via nibabel...
executing N4 correction ...
- mask: ones (default)
normalize WM to 105.0 (find WM from aseg)
read MGZ (FreeSurfer) image via nibabel...
- source white matter intensity: 95.66
- m: 1.0663
converting rescaled to UCHAR
writing PosixPath: /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz
write MGZ (FreeSurfer) image via nibabel...
python3 /content/fastsurfer//FastSurferCNN/segstats.py --segfile /content/fastsurfer_seg/3866_manual_fix/mri/aparc.DKTatlas+aseg.deep.mgz --segstatsfile /content/fastsurfer_seg/3866_manual_fix/stats/aseg+DKT.stats --normfile /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz --threads 1 --empty --excludeid 0 --sd /content/fastsurfer_seg --sid 3866_manual_fix --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /content/fastsurfer//FastSurferCNN/config/FreeSurferColorLUT.txt measures --compute Mask(/content/fastsurfer_seg/3866_manual_fix/mri/mask.mgz) BrainSeg BrainSegNotVent SupraTentorial SupraTentorialNotVent SubCortGray rhCerebralWhiteMatter lhCerebralWhiteMatter CerebralWhiteMatter
None of the labels [251, 252, 253, 254, 255] for merged label 10007 exist in the segmentation.
Partial volume stats for 100 labels written to /content/fastsurfer_seg/3866_manual_fix/stats/aseg+DKT.stats.
Calculation took 10.64 seconds using up to 1 threads.
python3 /content/fastsurfer//CerebNet/run_prediction.py --t1 /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz --asegdkt_segfile /content/fastsurfer_seg/3866_manual_fix/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/3866_manual_fix/mri/orig.mgz --cereb_segfile /content/fastsurfer_seg/3866_manual_fix/mri/cerebellum.CerebNet.nii.gz --seg_log /content/fastsurfer_seg/3866_manual_fix/scripts/deep-seg.log --async_io --batch_size 1 --viewagg_device auto --device auto --threads 1 --norm_name /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz --cereb_statsfile /content/fastsurfer_seg/3866_manual_fix/stats/cerebellum.CerebNet.stats --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  154]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/3866/MPRAGE_GRAPPA_20140926092006.nii.gz
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  434]: 26-04-05_22:52:23

Subject:   0%|          | 0/1 [00:00<?, ?it/s]


Subject:   0%|          | 0/1 [00:04<?, ?it/s][INFO: inference.py:  357]: Saving CerebNet cerebellum segmentation at /content/fastsurfer_seg/3866_manual_fix/mri/cerebellum.CerebNet.nii.gz



Subject:   0%|          | 0/1 [00:05<?, ?it/s][INFO: inference.py:  512]: Subject 1/1 with id 'MPRAGE_GRAPPA_20140926092006.nii.gz' processed in 4.44 sec.

Subject: 100%|██████████| 1/1 [00:05<00:00,  5.59s/it]
Subject: 100%|██████████| 1/1 [00:05<00:00,  5.59s/it]
python3 /content/fastsurfer//HypVINN/run_prediction.py --sd /content/fastsurfer_seg --sid 3866_manual_fix --reg_mode coreg --threads 1 --async_io --batch_size 1 --seg_log /content/fastsurfer_seg/3866_manual_fix/scripts/deep-seg.log --device auto --viewagg_device auto --t1 /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz
[INFO: run_prediction.py:  437]: Checking or downloading default checkpoints ...
[INFO: mode_config.py:   49]: Setting up input mode...
[INFO: run_prediction.py:  282]: Running HypVINN segmentation pipeline on subject 3866_manual_fix
[INFO: run_prediction.py:  285]: Output will be stored in: /content/fastsurfer_seg/3866_manual_fix
[INFO: run_prediction.py:  286]: T1 image input /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz
[INFO: run_prediction.py:  287]: T2 image input None
[INFO: run_prediction.py:  306]: Setting up HypVINN run
[INFO: run_prediction.py:  311]: axial model configuration from /content/fastsurfer/HypVINN/config/HypVINN_axial_v1.1.0.yaml
[INFO: run_prediction.py:  311]: coronal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_coronal_v1.1.0.yaml
[INFO: run_prediction.py:  311]: sagittal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_sagittal_v1.1.0.yaml
[INFO: run_prediction.py:  505]: Loading T1 image from : /content/fastsurfer_seg/3866_manual_fix/mri/orig_nu.mgz
Input:    min: 3  max: 248
rescale:  min: 3.0  max: 177.685  scale: 1.4597704439419525
Output:   min: 0.0  max: 255.0
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  109]: Running view aggregation on cuda
[INFO: run_prediction.py:  340]: ------------------------------------------------------------------------------------------------------------------------
[INFO: run_prediction.py:  341]: Evaluating hypothalamus model on 3866_manual_fix
[INFO: run_prediction.py:  350]: Scale factor: (np.float32(1.0), np.float32(1.0), np.float32(1.0))
[INFO: run_prediction.py:  609]: Evaluating axial model, cpkt :/content/fastsurfer/checkpoints/HypVINN_axial_v1.1.0.pkl
[INFO: inference.py:  183]: Loading checkpoint /content/fastsurfer/checkpoints/HypVINN_axial_v1.1.0.pkl
[INFO: dataset.py:  166]: Loading t1 axial with input voxelsize (np.float32(1.0), np.float32(1.0))
[INFO: dataset.py:  114]: Successfully loaded Image from 3866_manual_fix for axial model
[INFO: dataset.py:  126]: For inference T1 block weight was set to: 1.0 and the T2 block was set to: 0.0

  0%|          | 0/256 [00:00<?, ?it/s]
  0%|          | 1/256 [00:00<01:33,  2.74it/s]
  2%|▏         | 6/256 [00:00<00:16, 15.20it/s]
  4%|▍         | 11/256 [00:00<00:10, 24.07it/s]
  6%|▋         | 16/256 [00:00<00:07, 30.22it/s]
  8%|▊         | 21/256 [00:00<00:06, 34.58it/s]
 10%|█         | 26/256 [00:00<00:06, 37.64it/s]
 12%|█▏        | 31/256 [00:01<00:05, 39.89it/s]
 14%|█▍        | 36/256 [00:01<00:05, 41.36it/s]
 16%|█▌        | 41/256 [00:01<00:05, 42.54it/s]
 18%|█▊        | 46/256 [00:01<00:04, 43.29it/s]
 20%|█▉        | 51/256 [00:01<00:04, 43.90it/s]
 22%|██▏       | 56/256 [00:01<00:04, 44.13it/s]
 24%|██▍       | 61/256 [00:01<00:04, 44.46it/s]
 26%|██▌       | 66/256 [00:01<00:04, 44.62it/s]
 28%|██▊       | 71/256 [00:01<00:04, 44.70it/s]
 30%|██▉       | 76/256 [00:02<00:04, 44.79it/s]
 32%|███▏      | 81/256 [00:02<00:03, 44.83it/s]
 34%|███▎      | 86/256 [00:02<00:03, 44.82it/s]
 36%|███▌      | 91/256 [00:02<00:03, 44.57it/s]
 38%|███▊      | 96/256 [00:02<00:03, 44.68it/s]
 39%|███▉      | 101/256 [00:02<00:03, 44.74it/s]
 41%|████▏     | 106/256 [00:02<00:03, 44.71it/s]
 43%|████▎     | 111/256 [00:02<00:03, 44.73it/s]
 45%|████▌     | 116/256 [00:02<00:03, 44.61it/s]
 47%|████▋     | 121/256 [00:03<00:03, 44.59it/s]
 49%|████▉     | 126/256 [00:03<00:02, 44.30it/s]
 51%|█████     | 131/256 [00:03<00:02, 44.21it/s]
 53%|█████▎    | 136/256 [00:03<00:02, 44.49it/s]
 55%|█████▌    | 141/256 [00:03<00:02, 44.49it/s]
 57%|█████▋    | 146/256 [00:03<00:02, 44.64it/s]

In [ ]:
import os
import shutil
import zipfile
import datetime

subject_id = "3866"
old_session_id = "3866_manual_fix"
new_session_id = f"{subject_id}_MPRAGE_GRAPPA_2014"

# 1. Rename the existing processed folder
old_path = os.path.join(SETUP_DIR, "fastsurfer_seg", old_session_id)
new_path = os.path.join(SETUP_DIR, "fastsurfer_seg", new_session_id)

if os.path.exists(old_path):
    if os.path.exists(new_path): shutil.rmtree(new_path)
    os.rename(old_path, new_path)
    print(f"Renamed folder: {old_session_id} -> {new_session_id}")

# 2. Merge into Drive Zip
drive_zip = f"/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/stats_{subject_id}.zip"
staging_dir = f"/content/merge_staging_{subject_id}"
if os.path.exists(staging_dir): shutil.rmtree(staging_dir)
os.makedirs(staging_dir, exist_ok=True)

# Extract existing data if it exists
if os.path.exists(drive_zip):
    with zipfile.ZipFile(drive_zip, 'r') as zr:
        zr.extractall(staging_dir)
    print("Extracted existing zip from Drive.")

# Copy the new stats (with the new folder name)
new_stats_src = os.path.join(new_path, "stats")
if os.path.exists(new_stats_src):
    dest = os.path.join(staging_dir, new_session_id)
    if os.path.exists(dest): shutil.rmtree(dest)
    shutil.copytree(new_stats_src, dest)

    # Re-zip and update Drive
    shutil.make_archive(f"/content/stats_{subject_id}", 'zip', staging_dir)
    shutil.move(f"/content/stats_{subject_id}.zip", drive_zip)
    print(f"SUCCESS: Merged stats saved to {drive_zip}")

    # 3. Update Checkpoint to completed
    idx = df_checkpoint[df_checkpoint['Subject ID'].astype(str) == subject_id].index
    if not idx.empty:
        df_checkpoint.at[idx[0], 'status'] = 'completed'
        df_checkpoint.at[idx[0], 'timestamp'] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        df_checkpoint.to_csv(checkpoint_path, index=False)
        print(f"Subject {subject_id} marked as completed in checkpoint.")
else:
    print(f"Error: Stats folder not found at {new_stats_src}")

Renamed folder: 3866_manual_fix -> 3866_MPRAGE_GRAPPA_2014
Extracted existing zip from Drive.
SUCCESS: Merged stats saved to /content/drive/MyDrive/Fastsurfer_Automated_Pipeline/stats_3866.zip
Subject 3866 marked as completed in checkpoint.

In [ ]:
import zipfile
import os
import shutil

subject_id = '3866'
drive_zip = f'/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/stats_{subject_id}.zip'
staging_dir = f'/content/final_cleanup_{subject_id}'

if os.path.exists(drive_zip):
    # 1. Extract to a fresh staging area
    if os.path.exists(staging_dir): shutil.rmtree(staging_dir)
    os.makedirs(staging_dir)

    with zipfile.ZipFile(drive_zip, 'r') as z:
        z.extractall(staging_dir)

    # 2. Identify and remove the 'manual_fix' folder
    # It might be at the top level or nested depending on how it was zipped
    removed = False
    for root, dirs, files in os.walk(staging_dir):
        if '3866_manual_fix' in dirs:
            target = os.path.join(root, '3866_manual_fix')
            print(f'Removing redundant folder: {target}')
            shutil.rmtree(target)
            removed = True

    if removed:
        # 3. Re-zip the cleaned directory
        os.remove(drive_zip)
        shutil.make_archive(drive_zip.replace('.zip', ''), 'zip', staging_dir)
        print(f'SUCCESS: Cleaned {drive_zip}. "manual_fix" has been removed.')
    else:
        print('No "manual_fix" folder found in the ZIP. It appears already clean.')

    # Cleanup staging
    shutil.rmtree(staging_dir)
else:
    print(f'Error: {drive_zip} not found.')

Removing redundant folder: /content/final_cleanup_3866/3866_manual_fix
SUCCESS: Cleaned /content/drive/MyDrive/Fastsurfer_Automated_Pipeline/stats_3866.zip. "manual_fix" has been removed.

In [ ]:
import os
import glob

# List all ZIP files in the /content/ directory
zip_files = glob.glob('/content/*.zip')

print(f'--- ZIP Files found in /content/ ({len(zip_files)}) ---')
for f in sorted(zip_files):
    size_mb = os.path.getsize(f) / (1024 * 1024)
    print(f' - {os.path.basename(f)} ({size_mb:.2f} MB)')

if not zip_files:
    print('No ZIP files found. Please upload the subject data to /content/.')

--- ZIP Files found in /content/ (18) ---
 - 168082.zip (15.07 MB)
 - 168082_IDA_Metadata (1).zip (0.00 MB)
 - 168082_IDA_Metadata.zip (0.00 MB)
 - 168082_dataset.zip (15.19 MB)
 - 170727.zip (14.02 MB)
 - 170727_IDA_Metadata (1).zip (0.00 MB)
 - 170727_IDA_Metadata.zip (0.00 MB)
 - 170727_dataset.zip (13.71 MB)
 - 173266.zip (15.21 MB)
 - 173266_IDA_Metadata (1).zip (0.00 MB)
 - 173266_IDA_Metadata.zip (0.00 MB)
 - 173266_dataset.zip (16.13 MB)
 - 174131.zip (17.26 MB)
 - 174131_IDA_Metadata (1).zip (0.00 MB)
 - 174131_IDA_Metadata.zip (0.00 MB)
 - 174131_dataset.zip (17.14 MB)
 - 3866.zip (10.25 MB)
 - 3866_IDA_Metadata.zip (0.00 MB)

In [ ]:
import pandas as pd

target_subjects = ['168082', '170727', '173266', '174131']

print('--- Audit: Target Subjects Status ---')
display(df_checkpoint[df_checkpoint['Subject ID'].astype(str).isin(target_subjects)])

print('\n--- Audit: Summary of All Statuses ---')
status_summary = df_checkpoint['status'].value_counts()
print(status_summary)

# Check if anything else is non-completed
non_completed = df_checkpoint[~df_checkpoint['status'].str.contains('completed|download bug', case=False, na=False)]

if not non_completed.empty:
    print('\nWARNING: Found subjects that are neither completed nor marked as download bug:')
    display(non_completed)
else:
    print('\nSUCCESS: All other subjects are either completed or in the manual processing queue.')

--- Audit: Target Subjects Status ---

     Subject ID        status            timestamp nipoppy BL
164      168082  download bug  2026-04-03 11:33:16        Yes
169      170727  download bug  2026-04-03 01:28:45        Yes
174      173266  download bug  2026-04-03 01:05:03        Yes
177      174131  download bug  2026-04-02 13:03:44        Yes

--- Audit: Summary of All Statuses ---
status
completed       378
download bug      4
Name: count, dtype: int64

SUCCESS: All other subjects are either completed or in the manual processing queue.

In [ ]:
import os
import shutil
import zipfile
import glob
import datetime

target_subjects = ['168082', '170727', '173266', '174131']

for subject_id in target_subjects:
    print(f"\n{'='*80}\nPROCESSING SUBJECT: {subject_id}\n{'='*80}")

    working_dir = f"/content/data/{subject_id}"
    if os.path.exists(working_dir): shutil.rmtree(working_dir)
    os.makedirs(working_dir, exist_ok=True)

    # 1. Identify and Unpack all ZIPs related to this subject
    subject_zips = glob.glob(f"/content/{subject_id}*.zip")
    print(f"Found {len(subject_zips)} ZIP files for extraction.")

    for z in subject_zips:
        print(f"  Extracting: {os.path.basename(z)}...")
        with zipfile.ZipFile(z, 'r') as zip_ref:
            zip_ref.extractall(working_dir)

    # 2. DICOM to NIfTI Conversion
    print("Converting DICOMs to NIfTI...")
    os.system(f"dcm2niix -z y -f %p_%t -o {working_dir} {working_dir}")

    # 3. Construct and Run FastSurfer commands
    fs_commands = construct_command(subject_id)

    if not fs_commands:
        print(f"!!! Error: No NIfTI files generated for {subject_id}. Skipping.")
        continue

    print(f"Launching segmentation for {len(fs_commands)} sessions...")
    successful_sessions = 0
    for i, fs_cmd in enumerate(fs_commands):
        print(f"\n--- Session {i+1}/{len(fs_commands)} ---")
        try:
            # Using the robust v2 wrapper to catch known errors
            run_fastsurfer_robust_v2(fs_cmd)
            successful_sessions += 1
        except Exception as e:
            print(f">>> Session failed: {e}")

    # 4. Save Stats to Drive
    print("Zipping and saving stats to Drive...")
    zip_and_save_stats(subject_id)

    # 5. Update Checkpoint
    idx = df_checkpoint[df_checkpoint['Subject ID'].astype(str) == subject_id].index
    if not idx.empty:
        status_text = 'completed' if successful_sessions == len(fs_commands) else f"{successful_sessions}/{len(fs_commands)} completed"
        df_checkpoint.at[idx[0], 'status'] = status_text
        df_checkpoint.at[idx[0], 'timestamp'] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        df_checkpoint.to_csv(checkpoint_path, index=False)
        print(f"SUCCESS: Subject {subject_id} finalized with status: {status_text}")

print("\nALL MANUAL SUBJECTS PROCESSED.")

================================================================================
PROCESSING SUBJECT: 168082
================================================================================
Found 4 ZIP files for extraction.
  Extracting: 168082.zip...
  Extracting: 168082_IDA_Metadata.zip...
  Extracting: 168082_dataset.zip...
  Extracting: 168082_IDA_Metadata (1).zip...
Converting DICOMs to NIfTI...
Launching segmentation for 2 sessions...

--- Session 1/2 ---
Executing command:
export FASTSURFER_HOME=/content/fastsurfer/; /content/fastsurfer//run_fastsurfer.sh --t1 /content/data/168082/Anon_20220916114239.nii.gz --sd /content/fastsurfer_seg --sid 168082_Anon_20220916114239 --seg_only --py python3 --3T --allow_root

--- Output Log (Robust v2.2) ---
time command failing, not using time...
WARNING: You are trying to run 'run_fastsurfer.sh' as root. We recommend to avoid
  running FastSurfer as root, because it will lead to files and folders created as root.
  If you are running FastSurfer in a docker container, you can specify the user
  with '-u $(id -u):$(id -g)' (see https://docs.docker.com/engine/reference/run/#user).
=========================================================
Start of the log for a new run_fastsurfer.sh invocation
=========================================================
Version: 2.4.2+7e53343
Sun Apr  5 11:23:59 PM UTC 2026

Log file for FastSurfer pipeline, run_fastsurfer.sh and segmentation(s)
python3 /content/fastsurfer//FastSurferCNN/run_prediction.py --t1 /content/data/168082/Anon_20220916114239.nii.gz --asegdkt_segfile /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig.mgz --brainmask_name /content/fastsurfer_seg/168082_Anon_20220916114239/mri/mask.mgz --aseg_name /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aseg.auto_noCCseg.mgz --sid 168082_Anon_20220916114239 --seg_log /content/fastsurfer_seg/168082_Anon_20220916114239/scripts/deep-seg.log --vox_size min --batch_size 1 --viewagg_device auto --device auto --threads 1 --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  647]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/168082/Anon_20220916114239.nii.gz
[INFO: common.py:  979]: Output will be stored in Subjects Directory: /content/fastsurfer_seg
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: run_prediction.py:  245]: Running view aggregation on cuda
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_coronal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_sagittal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_axial_v2.0.0.pkl
[INFO: run_prediction.py:  324]: Successfully loaded image from /content/data/168082/Anon_20220916114239.nii.gz.
[INFO: run_prediction.py:  441]: Output image directory /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig does not exist. Creating it now...
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig/001.mgz.
[INFO: conform.py:  823]: The input image is not conformed.
[INFO: conform.py:  826]: A min-conformedconformed image must satisfy the following criteria:
[INFO: conform.py:  828]:  - Number of Dimensions 3        : True
[INFO: conform.py:  828]:  - Dimensions 256x256x256        : BUT image dimensions (192, 256, 256)
[INFO: conform.py:  828]:  - Voxel Size 1.0x1.0x1.0        : True
[INFO: conform.py:  828]:  - Orientation LIA               : BUT strict: [[ 1. -0.02 0.06] [ 0.01 0.99 0.17] [-0.07 -0.17 0.98]]
[INFO: conform.py:  828]:  - Dtype uint8                   : BUT dtype int16
[INFO: run_prediction.py:  337]: Conforming image
Input:    min: 0  max: 977
rescale:  min: 0.0  max: 727.865  scale: 0.3503396921132353
Output:   min: 0.0  max: 255.0
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig.mgz.
[INFO: run_prediction.py:  400]: Run coronal prediction
[INFO: dataset.py:   78]: Loading Coronal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  0%|          | 1/256 [00:00<01:34,  2.69batch/s]
  3%|▎         | 8/256 [00:00<00:11, 20.68batch/s]
  6%|▌         | 15/256 [00:00<00:07, 33.64batch/s]
  9%|▊         | 22/256 [00:00<00:05, 42.29batch/s]
 11%|█▏        | 29/256 [00:00<00:04, 48.79batch/s]
 14%|█▍        | 36/256 [00:00<00:04, 53.51batch/s]
 17%|█▋        | 43/256 [00:01<00:03, 56.92batch/s]
 20%|█▉        | 50/256 [00:01<00:03, 59.31batch/s]
 22%|██▏       | 57/256 [00:01<00:03, 60.99batch/s]
 25%|██▌       | 64/256 [00:01<00:03, 62.02batch/s]
 28%|██▊       | 71/256 [00:01<00:02, 62.93batch/s]
 30%|███       | 78/256 [00:01<00:02, 63.17batch/s]
 33%|███▎      | 85/256 [00:01<00:02, 63.43batch/s]
 36%|███▌      | 92/256 [00:01<00:02, 63.36batch/s]
 39%|███▊      | 99/256 [00:01<00:02, 63.18batch/s]
 41%|████▏     | 106/256 [00:02<00:02, 62.25batch/s]
 44%|████▍     | 113/256 [00:02<00:02, 63.25batch/s]
 47%|████▋     | 120/256 [00:02<00:02, 63.96batch/s]
 50%|████▉     | 127/256 [00:02<00:02, 64.39batch/s]
 52%|█████▏    | 134/256 [00:02<00:01, 64.58batch/s]
 55%|█████▌    | 141/256 [00:02<00:01, 64.73batch/s]
 58%|█████▊    | 148/256 [00:02<00:01, 64.91batch/s]
 61%|██████    | 155/256 [00:02<00:01, 64.70batch/s]
 63%|██████▎   | 162/256 [00:02<00:01, 64.67batch/s]
 66%|██████▌   | 169/256 [00:02<00:01, 64.69batch/s]
 69%|██████▉   | 176/256 [00:03<00:01, 64.52batch/s]
 71%|███████▏  | 183/256 [00:03<00:01, 64.55batch/s]
 74%|███████▍  | 190/256 [00:03<00:01, 61.39batch/s]
 77%|███████▋  | 197/256 [00:03<00:00, 61.85batch/s]
 80%|███████▉  | 204/256 [00:03<00:00, 62.60batch/s]
 82%|████████▏ | 211/256 [00:03<00:00, 63.37batch/s]
 85%|████████▌ | 218/256 [00:03<00:00, 63.94batch/s]
 88%|████████▊ | 225/256 [00:03<00:00, 64.17batch/s]
 91%|█████████ | 232/256 [00:03<00:00, 62.25batch/s]
 93%|█████████▎| 239/256 [00:04<00:00, 62.92batch/s]
 96%|█████████▌| 246/256 [00:04<00:00, 63.67batch/s]
 99%|█████████▉| 253/256 [00:04<00:00, 64.26batch/s]
100%|██████████| 256/256 [00:04<00:00, 58.67batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for coronal successful
[INFO: inference.py:  469]: Coronal inference on /content/data/168082/Anon_20220916114239.nii.gz finished in 4.3668 seconds
[INFO: run_prediction.py:  400]: Run sagittal prediction
[INFO: dataset.py:   69]: Loading Sagittal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:04, 61.02batch/s]
  5%|▌         | 14/256 [00:00<00:04, 60.17batch/s]
  8%|▊         | 21/256 [00:00<00:03, 60.59batch/s]
 11%|█         | 28/256 [00:00<00:03, 60.46batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 60.71batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 60.58batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 60.62batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 60.59batch/s]
 25%|██▍       | 63/256 [00:01<00:03, 60.58batch/s]
 27%|██▋       | 70/256 [00:01<00:03, 60.60batch/s]
 30%|███       | 77/256 [00:01<00:02, 60.70batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 60.61batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 60.58batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 60.61batch/s]
 41%|████      | 105/256 [00:01<00:02, 60.59batch/s]
 44%|████▍     | 112/256 [00:01<00:02, 60.51batch/s]
 46%|████▋     | 119/256 [00:01<00:02, 60.61batch/s]
 49%|████▉     | 126/256 [00:02<00:02, 60.60batch/s]
 52%|█████▏    | 133/256 [00:02<00:02, 60.80batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 60.88batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 60.65batch/s]
 60%|██████    | 154/256 [00:02<00:01, 60.84batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 60.90batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 60.50batch/s]
 68%|██████▊   | 175/256 [00:02<00:01, 60.36batch/s]
 71%|███████   | 182/256 [00:03<00:01, 60.48batch/s]
 74%|███████▍  | 189/256 [00:03<00:01, 60.61batch/s]
 77%|███████▋  | 196/256 [00:03<00:00, 60.63batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 60.62batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 60.35batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 60.35batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 60.44batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 60.49batch/s]
 93%|█████████▎| 238/256 [00:03<00:00, 60.51batch/s]
 96%|█████████▌| 245/256 [00:04<00:00, 60.77batch/s]
 98%|█████████▊| 252/256 [00:04<00:00, 61.04batch/s]
100%|██████████| 256/256 [00:04<00:00, 60.65batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for sagittal successful
[INFO: inference.py:  469]: Sagittal inference on /content/data/168082/Anon_20220916114239.nii.gz finished in 4.2224 seconds
[INFO: run_prediction.py:  400]: Run axial prediction
[INFO: dataset.py:   74]: Loading Axial with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:03, 67.32batch/s]
  5%|▌         | 14/256 [00:00<00:03, 66.05batch/s]
  8%|▊         | 21/256 [00:00<00:03, 65.54batch/s]
 11%|█         | 28/256 [00:00<00:03, 65.58batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 65.69batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 65.69batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 65.67batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 65.28batch/s]
 25%|██▍       | 63/256 [00:00<00:02, 64.92batch/s]
 27%|██▋       | 70/256 [00:01<00:02, 64.80batch/s]
 30%|███       | 77/256 [00:01<00:02, 64.78batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 64.81batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 63.31batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 63.99batch/s]
 41%|████      | 105/256 [00:01<00:02, 64.41batch/s]
 44%|████▍     | 112/256 [00:01<00:02, 64.85batch/s]
 46%|████▋     | 119/256 [00:01<00:02, 64.66batch/s]
 49%|████▉     | 126/256 [00:01<00:02, 64.49batch/s]
 52%|█████▏    | 133/256 [00:02<00:01, 64.40batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 64.33batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 64.44batch/s]
 60%|██████    | 154/256 [00:02<00:01, 64.67batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 65.11batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 65.35batch/s]
 68%|██████▊   | 175/256 [00:02<00:01, 65.66batch/s]
 71%|███████   | 182/256 [00:02<00:01, 66.00batch/s]
 74%|███████▍  | 189/256 [00:02<00:01, 65.92batch/s]
 77%|███████▋  | 196/256 [00:03<00:00, 65.50batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 65.29batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 65.10batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 65.11batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 65.29batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 65.34batch/s]
 93%|█████████▎| 238/256 [00:03<00:00, 65.29batch/s]
 96%|█████████▌| 245/256 [00:03<00:00, 65.41batch/s]
 98%|█████████▊| 252/256 [00:03<00:00, 65.05batch/s]
100%|██████████| 256/256 [00:03<00:00, 65.06batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for axial successful
[INFO: inference.py:  469]: Axial inference on /content/data/168082/Anon_20220916114239.nii.gz finished in 3.9360 seconds
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aparc.DKTatlas+aseg.deep.mgz.
[INFO: run_prediction.py:  724]: Creating brainmask based on segmentation...
Creating dilated mask ...
Frontal region special treatment:  18917
  Found 1 connected component(s)!
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/168082_Anon_20220916114239/mri/mask.mgz.
[INFO: run_prediction.py:  743]: Creating aseg based on segmentation...
Reducing to aseg ...
FlipWM: rh 0 and lh 0 flipped.
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aseg.auto_noCCseg.mgz.
[INFO: run_prediction.py:  762]: Running volume-based QC check on segmentation...
Checking total volume ...
Voxel size in mm3: 1.0
Total segmentation volume in liter: 1.15
INFO: Running N4 bias-field correction...
python3 /content/fastsurfer//recon_surf/N4_bias_correct.py --in /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig.mgz --rescale /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz --aseg /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aseg.auto_noCCseg.mgz --threads 1

N4 Bias Correction Parameters:

- verbosity: -1
- input volume: /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig.mgz
- output volume: do not save
- rescaled volume: /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz
- mask: default (>0)
- aseg: /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aseg.auto_noCCseg.mgz
- shrink factor: 4
- number fitting levels: 4
- number iterations: 50
- convergence threshold: 0.0
- threads: 1
read MGZ (FreeSurfer) image via nibabel...
executing N4 correction ...
- mask: ones (default)
normalize WM to 105.0 (find WM from aseg)
read MGZ (FreeSurfer) image via nibabel...
- source white matter intensity: 98.83
- m: 1.0321
converting rescaled to UCHAR
writing PosixPath: /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz
write MGZ (FreeSurfer) image via nibabel...
python3 /content/fastsurfer//FastSurferCNN/segstats.py --segfile /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aparc.DKTatlas+aseg.deep.mgz --segstatsfile /content/fastsurfer_seg/168082_Anon_20220916114239/stats/aseg+DKT.stats --normfile /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz --threads 1 --empty --excludeid 0 --sd /content/fastsurfer_seg --sid 168082_Anon_20220916114239 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /content/fastsurfer//FastSurferCNN/config/FreeSurferColorLUT.txt measures --compute Mask(/content/fastsurfer_seg/168082_Anon_20220916114239/mri/mask.mgz) BrainSeg BrainSegNotVent SupraTentorial SupraTentorialNotVent SubCortGray rhCerebralWhiteMatter lhCerebralWhiteMatter CerebralWhiteMatter
None of the labels [251, 252, 253, 254, 255] for merged label 10007 exist in the segmentation.
Partial volume stats for 100 labels written to /content/fastsurfer_seg/168082_Anon_20220916114239/stats/aseg+DKT.stats.
Calculation took 12.23 seconds using up to 1 threads.
python3 /content/fastsurfer//CerebNet/run_prediction.py --t1 /content/data/168082/Anon_20220916114239.nii.gz --asegdkt_segfile /content/fastsurfer_seg/168082_Anon_20220916114239/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig.mgz --cereb_segfile /content/fastsurfer_seg/168082_Anon_20220916114239/mri/cerebellum.CerebNet.nii.gz --seg_log /content/fastsurfer_seg/168082_Anon_20220916114239/scripts/deep-seg.log --async_io --batch_size 1 --viewagg_device auto --device auto --threads 1 --norm_name /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz --cereb_statsfile /content/fastsurfer_seg/168082_Anon_20220916114239/stats/cerebellum.CerebNet.stats --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  154]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/168082/Anon_20220916114239.nii.gz
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  434]: 26-04-05_23:28:30

Subject:   0%|          | 0/1 [00:00<?, ?it/s]


Subject:   0%|          | 0/1 [00:04<?, ?it/s][INFO: inference.py:  357]: Saving CerebNet cerebellum segmentation at /content/fastsurfer_seg/168082_Anon_20220916114239/mri/cerebellum.CerebNet.nii.gz



Subject:   0%|          | 0/1 [00:05<?, ?it/s][INFO: inference.py:  512]: Subject 1/1 with id 'Anon_20220916114239.nii.gz' processed in 4.37 sec.

Subject: 100%|██████████| 1/1 [00:05<00:00,  5.49s/it]
Subject: 100%|██████████| 1/1 [00:05<00:00,  5.49s/it]
python3 /content/fastsurfer//HypVINN/run_prediction.py --sd /content/fastsurfer_seg --sid 168082_Anon_20220916114239 --reg_mode coreg --threads 1 --async_io --batch_size 1 --seg_log /content/fastsurfer_seg/168082_Anon_20220916114239/scripts/deep-seg.log --device auto --viewagg_device auto --t1 /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz
[INFO: run_prediction.py:  437]: Checking or downloading default checkpoints ...
[INFO: mode_config.py:   49]: Setting up input mode...
[INFO: run_prediction.py:  282]: Running HypVINN segmentation pipeline on subject 168082_Anon_20220916114239
[INFO: run_prediction.py:  285]: Output will be stored in: /content/fastsurfer_seg/168082_Anon_20220916114239
[INFO: run_prediction.py:  286]: T1 image input /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz
[INFO: run_prediction.py:  287]: T2 image input None
[INFO: run_prediction.py:  306]: Setting up HypVINN run
[INFO: run_prediction.py:  311]: axial model configuration from /content/fastsurfer/HypVINN/config/HypVINN_axial_v1.1.0.yaml
[INFO: run_prediction.py:  311]: coronal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_coronal_v1.1.0.yaml
[INFO: run_prediction.py:  311]: sagittal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_sagittal_v1.1.0.yaml
[INFO: run_prediction.py:  505]: Loading T1 image from : /content/fastsurfer_seg/168082_Anon_20220916114239/mri/orig_nu.mgz
Input:    min: 3  max: 239
rescale:  min: 3.0  max: 201.712  scale: 1.2832642215870205
Output:   min: 0.0  max: 255.0
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  109]: Running view aggregation on cuda
[INFO: run_prediction.py:  340]: ------------------------------------------------------------------------------------------------------------------------
[INFO: run_prediction.py:  341]: Evaluating hypothalamus model on 168082_Anon_20220916114239
[INFO: run_prediction.py:  350]: Scale factor: (np.float32(1.0), np.float32(1.0), np.float32(1.0))
[INFO: run_prediction.py:  609]: Evaluating axial model, cpkt :/content/fastsurfer/checkpoints/HypVINN_axial_v1.1.0.pkl
[INFO: inference.py:  183]: Loading checkpoint /content/fastsurfer/checkpoints/HypVINN_axial_v1.1.0.pkl
[INFO: dataset.py:  166]: Loading t1 axial with input voxelsize (np.float32(1.0), np.float32(1.0))
[INFO: dataset.py:  114]: Successfully loaded Image from 168082_Anon_20220916114239 for axial model
[INFO: dataset.py:  126]: For inference T1 block weight was set to: 1.0 and the T2 block was set to: 0.0

  0%|          | 0/256 [00:00<?, ?it/s]
  0%|          | 1/256 [00:00<01:32,  2.76it/s]
  2%|▏         | 6/256 [00:00<00:16, 15.35it/s]
  4%|▍         | 11/256 [00:00<00:10, 24.15it/s]
  6%|▋         | 16/256 [00:00<00:07, 30.52it/s]
  8%|▊         | 21/256 [00:00<00:06, 35.15it/s]
 10%|█         | 26/256 [00:00<00:05, 38.43it/s]
 12%|█▏        | 31/256 [00:01<00:05, 40.70it/s]
 14%|█▍        | 36/256 [00:01<00:05, 42.30it/s]
 16%|█▌        | 41/256 [00:01<00:04, 43.29it/s]
 18%|█▊        | 46/256 [00:01<00:04, 44.02it/s]
 20%|█▉        | 51/256 [00:01<00:04, 44.30it/s]
 22%|██▏       | 56/256 [00:01<00:04, 44.67it/s]
 24%|██▍       | 61/256 [00:01<00:04, 45.02it/s]
 26%|██▌       | 66/256 [00:01<00:04, 45.43it/s]
 28%|██▊       | 71/256 [00:01<00:04, 45.58it/s]
 30%|██▉       | 76/256 [00:02<00:03, 45.75it/s]
 32%|███▏      | 81/256 [00:02<00:03, 45.68it/s]
 34%|███▎      | 86/256 [00:02<00:03, 45.59it/s]

# Error Checks and Parsing the Results!

## Subject ID Issue (will have to accept this due to time constraints)

In [ ]:
import pandas as pd

# 1. Load the broader metadata file
broader_metadata_path = '/content/T1_metadata_Final_Cleaned (9 missing).csv'
df_broader = pd.read_csv(broader_metadata_path)

# 2. Ensure IDs and Visit columns are strings for consistent comparison
df_metadata['Subject ID'] = df_metadata['Subject ID'].astype(str)
df_metadata['Visit'] = df_metadata['Visit'].astype(str)
df_broader['Subject ID'] = df_broader['Subject ID'].astype(str)
df_broader['Visit'] = df_broader['Visit'].astype(str)

# 3. Identify duplicate scans in the broader dataset for the same Subject/Visit
# We group by Subject ID and Visit and count unique Image IDs
scan_counts = df_broader.groupby(['Subject ID', 'Visit'])['Image ID'].nunique().reset_index()
multi_scan_entries = scan_counts[scan_counts['Image ID'] > 1]

# 4. Filter the current df_metadata to see which of our active scans have siblings in the broader data
audit_results = pd.merge(
    df_metadata[['Subject ID', 'Visit', 'Image ID', 'Description']],
    multi_scan_entries[['Subject ID', 'Visit']],
    on=['Subject ID', 'Visit'],
    how='inner'
)

if audit_results.empty:
    print("SUCCESS: No records in df_metadata share a Subject ID and Visit with other Image IDs in the broader dataset.")
else:
    print(f"Found {len(audit_results)} records in your metadata that share a Subject/Visit with multiple Image IDs in the source file.")
    print("This confirms that the downloader may struggle to differentiate these scans if it doesn't use the Image ID.")
    display(audit_results.sort_values(by=['Subject ID', 'Visit']))

Found 113 records in your metadata that share a Subject/Visit with multiple Image IDs in the source file.
This confirms that the downloader may struggle to differentiate these scans if it doesn't use the Image ID.

    Subject ID     Visit  Image ID         Description
59      100001  Baseline   1473172       SAG 3D MPRAGE
87      100018  Baseline   1497578      3D T1-weighted
60      100891  Month 24   1677717        MPRAGE - Sag
61      101124  Baseline   1493057      3D T1-weighted
62      101799  Month 24  10253239     SAG 3D T1 FSPGR
..         ...       ...       ...                 ...
55        4038  Month 24    497252  MPRAGE_GRAPPA_ADNI
56        4038  Month 48    901240       MPRAGE_GRAPPA
57        4081  Month 48    951750       MPRAGE GRAPPA
58        4082  Month 48    901269       MPRAGE GRAPPA
112      50983  Month 24    951872       MPRAGE GRAPPA

[113 rows x 4 columns]

In [ ]:
import pandas as pd

# 1. Merge the active metadata with all records from the broader metadata for those Subject/Visit pairs
df_siblings = pd.merge(
    df_metadata[['Subject ID', 'Visit', 'Image ID']].rename(columns={'Image ID': 'Active_Image_ID'}),
    df_broader[['Subject ID', 'Visit', 'Image ID']].rename(columns={'Image ID': 'Broader_Image_ID'}),
    on=['Subject ID', 'Visit'],
    how='inner'
)

# 2. Filter for cases where the active scan has a sibling with a DIFFERENT Image ID
df_conflicts = df_siblings[df_siblings['Active_Image_ID'] != df_siblings['Broader_Image_ID']].copy()

# 3. Identify cases where our active scan has a HIGHER ID than at least one of its siblings
# This means a 'first-match' downloader would pick the wrong one.
df_conflicts['is_higher'] = df_conflicts['Active_Image_ID'] > df_conflicts['Broader_Image_ID']

# Group by the active scan to see if it's 'at risk'
risk_audit = df_conflicts.groupby(['Subject ID', 'Visit', 'Active_Image_ID'])['is_higher'].any().reset_index()

num_at_risk = risk_audit['is_higher'].sum()
total_scanned = len(risk_audit)

print(f"--- Download Risk Audit ---")
print(f"Total multi-scan Subject/Visit pairs checked: {total_scanned}")
print(f"Cases where your target Image ID is HIGHER than a duplicate: {num_at_risk}")

if num_at_risk > 0:
    print("\nThese subjects are highly likely to have had the wrong DICOMs downloaded if the script didn't match by ID:")
    display(risk_audit[risk_audit['is_higher'] == True].head(15))

--- Download Risk Audit ---
Total multi-scan Subject/Visit pairs checked: 113
Cases where your target Image ID is HIGHER than a duplicate: 107

These subjects are highly likely to have had the wrong DICOMs downloaded if the script didn't match by ID:

   Subject ID     Visit  Active_Image_ID  is_higher
1      100018  Baseline          1497578       True
2      100891  Month 24          1677717       True
3      101124  Baseline          1493057       True
4      101799  Month 24         10253239       True
5      102012  Baseline          1491294       True
6      102027  Baseline          1491306       True
7      102053  Baseline          1495921       True
8      102053  Month 12          1608787       True
9      102053  Month 24         10259812       True
11     102475  Baseline          1530293       True
12     102484  Baseline          1493107       True
14     107099  Baseline          1498902       True
15     107099  Month 12          1616272       True
16     107099  Month 24         10284157       True
17     110212  Baseline          1519074       True

In [ ]:
# Let's find the correct column names and compare Subject 100018
target_sub = '100018'
target_visit = 'Baseline'

# Identify siblings
siblings_detail = df_broader[(df_broader['Subject ID'] == target_sub) & (df_broader['Visit'] == target_visit)]

print(f"--- Metadata Comparison for Subject {target_sub} ({target_visit}) ---")

# Dynamically select columns that exist in the dataframe to avoid KeyErrors
all_cols = siblings_detail.columns.tolist()
useful_cols = ['Image ID', 'Description', 'Study Date', 'Manufacturer', 'Mfg Model', 'Slice Thickness', 'Field Strength']
available_cols = [c for c in useful_cols if c in all_cols]

display(siblings_detail[available_cols])

print("\nAvailable columns in df_broader:", all_cols)

--- Metadata Comparison for Subject 100018 (Baseline) ---

,Image ID,Description,Study Date,Manufacturer,Mfg Model,Slice Thickness,Field Strength
20,1497577,3D T1-weighted,2/02/2021,SIEMENS,Skyra,1.0,3.0
21,1497578,3D T1-weighted,2/02/2021,SIEMENS,Skyra,1.0,3.0

Available columns in df_broader: ['Subject ID', 'Sex', 'Visit', 'Study Date', 'Age', 'Description', 'Imaging Protocol', 'Image ID', 'Weighting', 'Acquisition Plane', 'Field Strength', 'Manufacturer', 'Mfg Model', 'Slice Thickness']

## Parsing

In [ ]:
import os
import zipfile
import io

# 1. Identify a valid stats ZIP on Drive
drive_path = '/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/'
zip_files = [f for f in os.listdir(drive_path) if f.startswith('stats_') and f.endswith('.zip')]

if not zip_files:
    print('No ZIP files found in the Drive folder.')
else:
    target_zip = os.path.join(drive_path, zip_files[0])
    print(f'Reading sample from: {os.path.basename(target_zip)}')

    # 2. Extract and display more of the first stats file found
    with zipfile.ZipFile(target_zip, 'r') as z:
        stats_entries = [f for f in z.namelist() if 'aseg+DKT.stats' in f]

        if not stats_entries:
            print('Could not find aseg+DKT.stats inside the ZIP.')
        else:
            sample_file = stats_entries[0]
            print(f'File found: {sample_file}\n')

            with z.open(sample_file) as f:
                content = f.read().decode('utf-8')
                lines = content.split('\n')
                # Increase to 300 lines to ensure we see the full structure table
                for line in lines[:300]:
                    print(line)

Reading sample from: stats_100001.zip
File found: 100001_Anon_20240911084930/aseg+DKT.stats

# Title Segmentation Statistics
#
# generating_program segstats.py
# FastSurfer_version 2.4.2
# cmdline /content/fastsurfer//FastSurferCNN/segstats.py --segfile /content/fastsurfer_seg/100001_Anon_20240911084930/mri/aparc.DKTatlas+aseg.deep.mgz --segstatsfile /content/fastsurfer_seg/100001_Anon_20240911084930/stats/aseg+DKT.stats --normfile /content/fastsurfer_seg/100001_Anon_20240911084930/mri/orig_nu.mgz --threads 1 --empty --excludeid 0 --sd /content/fastsurfer_seg --sid 100001_Anon_20240911084930 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /content/fastsurfer//FastSurferCNN/config/FreeSurferColorLUT.txt measures --compute Mask(/content/fastsurfer_seg/100001_Anon_20240911084930/mri/mask.mgz) BrainSeg BrainSegNotVent SupraTentorial SupraTentorialNotVent SubCortGray rhCerebralWhiteMatter lhCerebralWhiteMatter CerebralWhiteMatter
# sysname  Linux
# hostname 0e19a3b3ee15
# machine  x86_64
# user       root
# anatomy_type volume
#
# SUBJECT_DIR /content/fastsurfer_seg
# subjectname 100001_Anon_20240911084930
# Measure Mask, MaskVol, Mask Volume, 1446766.000000, mm^3
# Measure BrainSeg, BrainSegVol, Brain Segmentation Volume, 1134900.497724, mm^3
# Measure BrainSegNotVent, BrainSegVolNotVent, Brain Segmentation Volume Without Ventricles, 1107924.275239, mm^3
# Measure SupraTentorial, SupraTentorialVol, Supratentorial volume, 991780.511670, mm^3
# Measure SupraTentorialNotVent, SupraTentorialVolNotVent, Supratentorial volume, 964804.289185, mm^3
# Measure SubCortGray, SubCortGrayVol, Subcortical gray matter volume, 58324.505092, mm^3
# Measure rhCerebralWhiteMatter, rhCerebralWhiteMatterVol, Right hemisphere cerebral white matter volume, 243244.493056, mm^3
# Measure lhCerebralWhiteMatter, lhCerebralWhiteMatterVol, Left hemisphere cerebral white matter volume, 245061.725970, mm^3
# Measure CerebralWhiteMatter, CerebralWhiteMatterVol, Total cerebral white matter volume, 488306.219026, mm^3
# SegVolFile /content/fastsurfer_seg/100001_Anon_20240911084930/mri/aparc.DKTatlas+aseg.deep.mgz
# SegVolFileTimestamp 2026/03/22 20:02:38
# ColorTable /content/fastsurfer/FastSurferCNN/config/FreeSurferColorLUT.txt
# ColorTableTimestamp 2026/03/22 19:44:39
# InVolFile /content/fastsurfer_seg/100001_Anon_20240911084930/mri/orig_nu.mgz
# InVolFileTimestamp 2026/03/22 20:06:33
# ExcludeSegId 0
# Only reporting non-empty segmentations
# compatibility with freesurfer's mri_segstats: fixed
# VoxelVolume_mm3 1.0
# TableCol  1 ColHeader Index
# TableCol  1 FieldName Index
# TableCol  1 Units     NA
# TableCol  2 ColHeader SegId
# TableCol  2 FieldName Segmentation Id
# TableCol  2 Units     NA
# TableCol  3 ColHeader NVoxels
# TableCol  3 FieldName Number of Voxels
# TableCol  3 Units     unitless
# TableCol  4 ColHeader Volume_mm3
# TableCol  4 FieldName Volume
# TableCol  4 Units     mm^3
# TableCol  5 ColHeader StructName
# TableCol  5 FieldName Structure Name
# TableCol  5 Units     NA
# TableCol  6 ColHeader normMean
# TableCol  6 FieldName Intensity normMean
# TableCol  6 Units     MR
# TableCol  7 ColHeader normStdDev
# TableCol  7 FieldName Intensity normStdDev
# TableCol  7 Units     MR
# TableCol  8 ColHeader normMin
# TableCol  8 FieldName Intensity normMin
# TableCol  8 Units     MR
# TableCol  9 ColHeader normMax
# TableCol  9 FieldName Intensity normMax
# TableCol  9 Units     MR
# TableCol 10 ColHeader normRange
# TableCol 10 FieldName Intensity normRange
# TableCol 10 Units     MR
# NRows 100
# NTableCols 10
# ColHeaders  Index SegId NVoxels Volume_mm3 StructName normMean normStdDev normMin normMax normRange
  1   2    237119 244662.726  Left-Cerebral-White-Matter       104.2728     6.3192    32.0000   156.0000   124.0000
  2   4      8595   8999.780  Left-Lateral-Ventricle            45.1888    10.3090    21.0000    86.0000    65.0000
  3   5       495    580.990  Left-Inf-Lat-Vent                 57.7394    14.6552    23.0000    86.0000    63.0000
  4   7     13402  14026.028  Left-Cerebellum-White-Matter     107.6854     6.5398    58.0000   134.0000    76.0000
  5   8     60208  58313.647  Left-Cerebellum-Cortex            92.3767    12.4228    25.0000   175.0000   150.0000
  6  10      8334   8197.307  Left-Thalamus                     93.8440     7.9110    50.0000   118.0000    68.0000
  7  11      3394   3328.894  Left-Caudate                      87.9826     6.7701    60.0000   106.0000    46.0000
  8  12      4851   4809.304  Left-Putamen                      94.3381     4.9727    41.0000   110.0000    69.0000
  9  13      1855   1881.815  Left-Pallidum                    100.8631     8.8933    21.0000   125.0000   104.0000
 10  14      1289   1323.272  3rd-Ventricle                     47.7223    11.2151    23.0000    80.0000    57.0000
 11  15      1622   1721.101  4th-Ventricle                     50.7429    13.6792    20.0000    98.0000    78.0000
 12  16     23717  23347.507  Brain-Stem                       101.7425     9.2125    33.0000   131.0000    98.0000
 13  17      4484   4202.100  Left-Hippocampus                  88.7163     9.2139    50.0000   113.0000    63.0000
 14  18      1662   1686.856  Left-Amygdala                     90.9236     7.3329    62.0000   113.0000    51.0000
 15  24      1397   1392.788  CSF                               55.0279    12.2148    25.0000   111.0000    86.0000
 16  26       519    506.619  Left-Accumbens-area               90.1965     5.0250    58.0000   106.0000    48.0000
 17  28      4621   4475.379  Left-VentralDC                   100.5239    10.8088    45.0000   127.0000    82.0000
 18  31       743    713.315  Left-choroid-plexus               63.1184    12.2199    37.0000    95.0000    58.0000
 19  41    235708 242932.493  Right-Cerebral-White-Matter      104.7280     6.3373    32.0000   135.0000   103.0000
 20  43     10715  11039.965  Right-Lateral-Ventricle           44.7361    10.5290    21.0000    85.0000    64.0000
 21  44       330    409.373  Right-Inf-Lat-Vent                56.6667    12.8564    18.0000    82.0000    64.0000
 22  46     12576  13107.790  Right-Cerebellum-White-Matter    108.9588     6.4980    62.0000   131.0000    69.0000
 23  47     59482  57672.521  Right-Cerebellum-Cortex           92.2751    11.7831    23.0000   173.0000   150.0000
 24  49      8470   8328.336  Right-Thalamus                    94.1499     8.0541    44.0000   118.0000    74.0000
 25  50      3136   3068.289  Right-Caudate                     92.7213     7.6483    61.0000   110.0000    49.0000
 26  51      5076   5081.472  Right-Putamen                     95.1647     5.2361    65.0000   112.0000    47.0000
 27  52      1915   1907.357  Right-Pallidum                   103.7927     5.0633    84.0000   122.0000    38.0000
 28  53      4618   4419.223  Right-Hippocampus                 85.8512     8.9769    42.0000   113.0000    71.0000
 29  54      1690   1697.976  Right-Amygdala                    89.4799     6.9495    59.0000   112.0000    53.0000
 30  58       658    651.343  Right-Accumbens-area              90.8222     4.8415    72.0000   103.0000    31.0000
 31  60      4272   4082.236  Right-VentralDC                   98.1641    10.5930    42.0000   127.0000    85.0000
 32  63       840    795.637  Right-choroid-plexus              61.2643    11.9296    30.0000    93.0000    63.0000
 33  77       711    643.564  WM-hypointensities                74.9494     8.1069    52.0000    96.0000    44.0000
 34 251         0      0.000  CC_Posterior                       0.0000     0.0000     0.0000     0.0000     0.0000
 35 252         0      0.000  CC_Mid_Posterior                   0.0000     0.0000     0.0000     0.0000     0.0000
 36 253         0      0.000  CC_Central                         0.0000     0.0000     0.0000     0.0000     0.0000
 37 254         0      0.000  CC_Mid_Anterior                    0.0000     0.0000     0.0000     0.0000     0.0000
 38 255         0      0.000  CC_Anterior                        0.0000     0.0000     0.0000     0.0000     0.0000
 39 1002      3146   3065.236  ctx-lh-caudalanteriorcingulate    80.8525     6.5050    61.0000    98.0000    37.0000
 40 1003      6031   5784.617  ctx-lh-caudalmiddlefrontal        87.2699     7.7126    63.0000   105.0000    42.0000
 41 1005      3858   3338.937  ctx-lh-cuneus                     87.8875    10.1838    59.0000   114.0000    55.0000
 42 1006      1897   1766.508  ctx-lh-entorhinal                 90.8698     7.2644    62.0000   110.0000    48.0000
 43 1007      7997   7531.716  ctx-lh-fusiform                   88.0354     7.6562    54.0000   110.0000    56.0000
 44 1008     10000   9406.803  ctx-lh-inferiorparietal           86.1243     8.6761    51.0000   107.0000    56.0000
 45 1009     11189  11176.213  ctx-lh-inferiortemporal           89.5419     8.1475    50.0000   124.0000    74.0000
 46 1010      2097   1905.694  ctx-lh-isthmuscingulate           85.8441     7.2734    60.0000   111.0000    51.0000
 47 1011     10684   9932.367  ctx-lh-lateraloccipital           88.8762     9.7491    54.0000   115.0000    61.0000
 48 1012      7920   7405.921  ctx-lh-lateralorbitofrontal       87.6384     8.9586    53.0000   177.0000   124.0000
 49 1013      6353   5801.911  ctx-lh-lingual                    87.8076     8.6327    55.0000   112.0000    57.0000
 50 1014      4850   4738.221  ctx-lh-medialorbitofrontal        84.9864     7.6391    60.0000   147.0000    87.0000
 51 1015     13520  12750.072  ctx-lh-middletemporal             88.2108     7.8318    57.0000   130.0000    73.0000
 52 1016      2221   2100.748  ctx-lh-parahippocampal            88.6407     8.3083    61.0000   126.0000    65.0000
 53 1017      3935   3457.804  ctx-lh-paracentral                89.3652     9.5235    62.0000   117.0000    55.0000
 54 1018      4304   4115.209  ctx-lh-parsopercularis            87.0790     7.9392    58.0000   108.0000    50.0000
 55 1019      2038   1825.018  ctx-lh-parsorbitalis              89.5088     8.4841    52.0000   137.0000    85.0000
 56 1020      4419   4244.059  ctx-lh-parstriangularis           90.2415     8.5036    64.0000   111.0000    47.0000
 57 1021      1549   1259.563  ctx-lh-pericalcarine              89.6101    10.0487    61.0000   114.0000    53.0000
 58 1022     10130   9123.089  ctx-lh-postcentral                87.5889     9.6364    50.0000   111.0000    61.0000
 59 1023      3512   3440.146  ctx-lh-posteriorcingulate         84.9792     6.8615    60.0000   105.0000    45.0000
 60 1024     12303  11424.819  ctx-lh-precentral                 87.8412     8.9560    55.0000   112.0000    57.0000
 61 1025      7663   7154.704  ctx-lh-precuneus                  88.7595     8.6979    59.0000   113.0000    54.0000
 62 1026      3539   3485.061  ctx-lh-rostralanteriorcingulate    82.7477     5.8803    60.0000    99.0000    39.0000
 63 1027     10276  10334.243  ctx-lh-rostralmiddlefrontal       87.1531     7.2070    60.0000   113.0000    53.0000
 64 1028     21493  21138.633  ctx-lh-superiorfrontal            86.4314     7.6165    59.0000   106.0000    47.0000
 65 1029      8734   8082.966  ctx-lh-superiorparietal           90.3556     9.7681    58.0000   114.0000    56.0000
 66 1030     17646  16593.472  ctx-lh-superiortemporal           88.6456     8.2351    53.0000   146.0000    93.0000
 67 1031     10005   9533.689  ctx-lh-supramarginal              86.0041     7.9639    54.0000   105.0000    51.0000
 68 1034      1192   1001.641  ctx-lh-transversetemporal         88.3750     9.0758    61.0000   109.0000    48.0000
 69 1035      5755   5677.020  ctx-lh-insula                     83.3583     6.5158    56.0000   101.0000    45.0000
 70 2002      1891   1843.128  ctx-rh-caudalanteriorcingulate    81.8445     6.2949    57.0000    98.0000    41.0000
 71 2003      5596   5394.966  ctx-rh-caudalmiddlefrontal        87.1276     7.6406    60.0000   106.0000    46.0000
 72 2005      3416   2884.085  ctx-rh-cuneus                     86.4830     8.7484    63.0000   110.0000    47.0000
 73 2006      1542   1469.149  ctx-rh-entorhinal                 89.0901     7.5955    64.0000   112.0000    48.0000
 74 2007      8715   8327.686  ctx-rh-fusiform                   87.4808     8.1336    56.0000   124.0000    68.0000
 75 2008     12007  11356.031  ctx-rh-inferiorparietal           87.3556     8.1397    51.0000   106.0000    55.0000
 76 2009     11436  11325.368  ctx-rh-inferiortemporal           89.8165     8.4939    54.0000   143.0000    89.0000
 77 2010      1896   1790.272  ctx-rh-isthmuscingulate           85.9193     6.5793    64.0000   108.0000    44.0000
 78 2011     11027  10432.835  ctx-rh-lateraloccipital           88.1188     9.6970    54.0000   112.0000    58.0000
 79 2012      8365   7940.901  ctx-rh-lateralorbitofrontal       87.5834     8.6328    35.0000   150.0000   115.0000
 80 2013      6204   5738.791  ctx-rh-lingual                    85.9242     7.9106    55.0000   117.0000    62.0000
 81 2014      5001   4958.135  ctx-rh-medialorbitofrontal        87.5593     8.2962    59.0000   124.0000    65.0000
 82 2015     14424  13610.356  ctx-rh-middletemporal             89.0677     7.8305    52.0000   130.0000    78.0000
 83 2016      2158   2058.406  ctx-rh-parahippocampal            85.8693     7.9415    59.0000   124.0000    65.0000
 84 2017      3912   3509.909  ctx-rh-paracentral                89.2237     9.6705    62.0000   111.0000    49.0000
 85 2018      4630   4410.999  ctx-rh-parsopercularis            86.2192     7.3561    57.0000   105.0000    48.0000
 86 2019      1945   1773.584  ctx-rh-parsorbitalis              89.4134     7.5292    56.0000   127.0000    71.0000
 87 2020      4465   4119.977  ctx-rh-parstriangularis           88.8596     7.9624    59.0000   112.0000    53.0000
 88 2021      1643   1312.596  ctx-rh-pericalcarine              86.7188     8.7877    62.0000   106.0000    44.0000
 89 2022      9010   8052.501  ctx-rh-postcentral                88.1612     9.4777    56.0000   113.0000    57.0000
 90 2023      2695   2540.949  ctx-rh-posteriorcingulate         85.3922     6.8575    60.0000   102.0000    42.0000
 91 2024     11443  10653.921  ctx-rh-precentral                 88.9300     8.7132    53.0000   111.0000    58.0000
 92 2025      8196   7794.166  ctx-rh-precuneus                  86.4272     8.0262    60.0000   108.0000    48.0000
 93 2026      2594   2495.664  ctx-rh-rostralanteriorcingulate    85.6022     5.7212    63.0000   102.0000    39.0000
 94 2027     10359  10490.085  ctx-rh-rostralmiddlefrontal       86.7859     7.0096    58.0000   106.0000    48.0000
 95 2028     26324  26054.235  ctx-rh-superiorfrontal            88.5057     7.8360    61.0000   109.0000    48.0000
 96 2029      8493   7785.494  ctx-rh-superiorparietal           89.5071     9.9091    53.0000   114.0000    61.0000
 97 2030     14990  14174.507  ctx-rh-superiortemporal           90.3409     8.4940    55.0000   136.0000    81.0000
 98 2031      9027   8643.477  ctx-rh-supramarginal              86.3234     7.7166    59.0000   105.0000    46.0000
 99 2034       969    829.227  ctx-rh-transversetemporal         88.3395     9.1260    61.0000   108.0000    47.0000
100 2035      5884   5873.501  ctx-rh-insula                     83.1278     6.6781    57.0000   108.0000    51.0000

In [ ]:
# 1. Parse the structure names directly from the loaded sample content
lines = content.split('\n')
structure_list = []
start_parsing = False

for line in lines:
    if line.startswith('# ColHeaders'):
        start_parsing = True
        continue
    # The table data starts after comments and header
    if start_parsing and line.strip() and not line.startswith('#'):
        parts = line.split()
        if len(parts) >= 5:
            # The 5th column (index 4) contains the Structure Name
            structure_list.append(parts[4])

print(f"--- Found {len(structure_list)} structures in sample file ---")
print("Full List for Template Construction:")
print(structure_list)

--- Found 100 structures in sample file ---
Full List for Template Construction:
['Left-Cerebral-White-Matter', 'Left-Lateral-Ventricle', 'Left-Inf-Lat-Vent', 'Left-Cerebellum-White-Matter', 'Left-Cerebellum-Cortex', 'Left-Thalamus', 'Left-Caudate', 'Left-Putamen', 'Left-Pallidum', '3rd-Ventricle', '4th-Ventricle', 'Brain-Stem', 'Left-Hippocampus', 'Left-Amygdala', 'CSF', 'Left-Accumbens-area', 'Left-VentralDC', 'Left-choroid-plexus', 'Right-Cerebral-White-Matter', 'Right-Lateral-Ventricle', 'Right-Inf-Lat-Vent', 'Right-Cerebellum-White-Matter', 'Right-Cerebellum-Cortex', 'Right-Thalamus', 'Right-Caudate', 'Right-Putamen', 'Right-Pallidum', 'Right-Hippocampus', 'Right-Amygdala', 'Right-Accumbens-area', 'Right-VentralDC', 'Right-choroid-plexus', 'WM-hypointensities', 'CC_Posterior', 'CC_Mid_Posterior', 'CC_Central', 'CC_Mid_Anterior', 'CC_Anterior', 'ctx-lh-caudalanteriorcingulate', 'ctx-lh-caudalmiddlefrontal', 'ctx-lh-cuneus', 'ctx-lh-entorhinal', 'ctx-lh-fusiform', 'ctx-lh-inferiorparietal', 'ctx-lh-inferiortemporal', 'ctx-lh-isthmuscingulate', 'ctx-lh-lateraloccipital', 'ctx-lh-lateralorbitofrontal', 'ctx-lh-lingual', 'ctx-lh-medialorbitofrontal', 'ctx-lh-middletemporal', 'ctx-lh-parahippocampal', 'ctx-lh-paracentral', 'ctx-lh-parsopercularis', 'ctx-lh-parsorbitalis', 'ctx-lh-parstriangularis', 'ctx-lh-pericalcarine', 'ctx-lh-postcentral', 'ctx-lh-posteriorcingulate', 'ctx-lh-precentral', 'ctx-lh-precuneus', 'ctx-lh-rostralanteriorcingulate', 'ctx-lh-rostralmiddlefrontal', 'ctx-lh-superiorfrontal', 'ctx-lh-superiorparietal', 'ctx-lh-superiortemporal', 'ctx-lh-supramarginal', 'ctx-lh-transversetemporal', 'ctx-lh-insula', 'ctx-rh-caudalanteriorcingulate', 'ctx-rh-caudalmiddlefrontal', 'ctx-rh-cuneus', 'ctx-rh-entorhinal', 'ctx-rh-fusiform', 'ctx-rh-inferiorparietal', 'ctx-rh-inferiortemporal', 'ctx-rh-isthmuscingulate', 'ctx-rh-lateraloccipital', 'ctx-rh-lateralorbitofrontal', 'ctx-rh-lingual', 'ctx-rh-medialorbitofrontal', 'ctx-rh-middletemporal', 'ctx-rh-parahippocampal', 'ctx-rh-paracentral', 'ctx-rh-parsopercularis', 'ctx-rh-parsorbitalis', 'ctx-rh-parstriangularis', 'ctx-rh-pericalcarine', 'ctx-rh-postcentral', 'ctx-rh-posteriorcingulate', 'ctx-rh-precentral', 'ctx-rh-precuneus', 'ctx-rh-rostralanteriorcingulate', 'ctx-rh-rostralmiddlefrontal', 'ctx-rh-superiorfrontal', 'ctx-rh-superiorparietal', 'ctx-rh-superiortemporal', 'ctx-rh-supramarginal', 'ctx-rh-transversetemporal', 'ctx-rh-insula']

In [ ]:
import pandas as pd

# 1. Define Identity Headings
identity_cols = ['PATNO', 'EVENT_ID', 'Study_Date', 'Image_Description']

# 2. Define 9 Global Measures
global_measures = [
    'MaskVol', 'BrainSegVol', 'BrainSegVolNotVent',
    'SupraTentorialVol', 'SupraTentorialVolNotVent',
    'SubCortGrayVol', 'rhCerebralWhiteMatterVol',
    'lhCerebralWhiteMatterVol', 'CerebralWhiteMatterVol'
]

# 3. Define 100 Anatomical Structures (from Left-Cerebral-White-Matter to ctx-rh-insula)
# These are extracted from the standard FreeSurfer/FastSurfer LUT used in the stats file
structures = structure_list

# 4. Create Empty DataFrame
all_columns = identity_cols + global_measures + structures
df_template = pd.DataFrame(columns=all_columns)

# 5. Save and Display
template_path = '/content/FastSurfer_Aggregation_Template.csv'
df_template.to_csv(template_path, index=False)

print(f"Empty spreadsheet created with {len(all_columns)} columns.")
print(f"Location: {template_path}")
display(df_template)

Empty spreadsheet created with 113 columns.
Location: /content/FastSurfer_Aggregation_Template.csv

Empty DataFrame
Columns: [PATNO, EVENT_ID, Study_Date, Image_Description, MaskVol, BrainSegVol, BrainSegVolNotVent, SupraTentorialVol, SupraTentorialVolNotVent, SubCortGrayVol, rhCerebralWhiteMatterVol, lhCerebralWhiteMatterVol, CerebralWhiteMatterVol, Left-Cerebral-White-Matter, Left-Lateral-Ventricle, Left-Inf-Lat-Vent, Left-Cerebellum-White-Matter, Left-Cerebellum-Cortex, Left-Thalamus, Left-Caudate, Left-Putamen, Left-Pallidum, 3rd-Ventricle, 4th-Ventricle, Brain-Stem, Left-Hippocampus, Left-Amygdala, CSF, Left-Accumbens-area, Left-VentralDC, Left-choroid-plexus, Right-Cerebral-White-Matter, Right-Lateral-Ventricle, Right-Inf-Lat-Vent, Right-Cerebellum-White-Matter, Right-Cerebellum-Cortex, Right-Thalamus, Right-Caudate, Right-Putamen, Right-Pallidum, Right-Hippocampus, Right-Amygdala, Right-Accumbens-area, Right-VentralDC, Right-choroid-plexus, WM-hypointensities, CC_Posterior, CC_Mid_Posterior, CC_Central, CC_Mid_Anterior, CC_Anterior, ctx-lh-caudalanteriorcingulate, ctx-lh-caudalmiddlefrontal, ctx-lh-cuneus, ctx-lh-entorhinal, ctx-lh-fusiform, ctx-lh-inferiorparietal, ctx-lh-inferiortemporal, ctx-lh-isthmuscingulate, ctx-lh-lateraloccipital, ctx-lh-lateralorbitofrontal, ctx-lh-lingual, ctx-lh-medialorbitofrontal, ctx-lh-middletemporal, ctx-lh-parahippocampal, ctx-lh-paracentral, ctx-lh-parsopercularis, ctx-lh-parsorbitalis, ctx-lh-parstriangularis, ctx-lh-pericalcarine, ctx-lh-postcentral, ctx-lh-posteriorcingulate, ctx-lh-precentral, ctx-lh-precuneus, ctx-lh-rostralanteriorcingulate, ctx-lh-rostralmiddlefrontal, ctx-lh-superiorfrontal, ctx-lh-superiorparietal, ctx-lh-superiortemporal, ctx-lh-supramarginal, ctx-lh-transversetemporal, ctx-lh-insula, ctx-rh-caudalanteriorcingulate, ctx-rh-caudalmiddlefrontal, ctx-rh-cuneus, ctx-rh-entorhinal, ctx-rh-fusiform, ctx-rh-inferiorparietal, ctx-rh-inferiortemporal, ctx-rh-isthmuscingulate, ctx-rh-lateraloccipital, ctx-rh-lateralorbitofrontal, ctx-rh-lingual, ctx-rh-medialorbitofrontal, ctx-rh-middletemporal, ctx-rh-parahippocampal, ctx-rh-paracentral, ctx-rh-parsopercularis, ctx-rh-parsorbitalis, ctx-rh-parstriangularis, ...]
Index: []

[0 rows x 113 columns]

In [ ]:
import re

# Search for eTIV in the sample stats content
print("--- Searching for eTIV / ICV ---")
etiv_pattern = re.compile(r'Measure (EstimatedTotalIntraCranialVol|eTIV|ICV),.*?, (\d+\.\d+), mm\^3', re.IGNORECASE)
etiv_match = etiv_pattern.search(content)

if etiv_match:
    print(f"Found eTIV measure: {etiv_match.group(1)} = {etiv_match.group(2)}")
else:
    print("EstimatedTotalIntraCranialVol not found in global measures.")
    # Peek at all lines starting with '# Measure'
    measure_lines = [l for l in content.split('\n') if l.startswith('# Measure')]
    print("Available Global Measures:")
    for ml in measure_lines: print(f"  {ml}")

--- Searching for eTIV / ICV ---
EstimatedTotalIntraCranialVol not found in global measures.
Available Global Measures:
  # Measure Mask, MaskVol, Mask Volume, 1446766.000000, mm^3
  # Measure BrainSeg, BrainSegVol, Brain Segmentation Volume, 1134900.497724, mm^3
  # Measure BrainSegNotVent, BrainSegVolNotVent, Brain Segmentation Volume Without Ventricles, 1107924.275239, mm^3
  # Measure SupraTentorial, SupraTentorialVol, Supratentorial volume, 991780.511670, mm^3
  # Measure SupraTentorialNotVent, SupraTentorialVolNotVent, Supratentorial volume, 964804.289185, mm^3
  # Measure SubCortGray, SubCortGrayVol, Subcortical gray matter volume, 58324.505092, mm^3
  # Measure rhCerebralWhiteMatter, rhCerebralWhiteMatterVol, Right hemisphere cerebral white matter volume, 243244.493056, mm^3
  # Measure lhCerebralWhiteMatter, lhCerebralWhiteMatterVol, Left hemisphere cerebral white matter volume, 245061.725970, mm^3
  # Measure CerebralWhiteMatter, CerebralWhiteMatterVol, Total cerebral white matter volume, 488306.219026, mm^3

In [ ]:
import os
import zipfile
import pandas as pd
import re
from tqdm import tqdm

# --- Configuration ---
drive_results_dir = '/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/'
# Final output saved to the 'data' subfolder as requested
final_output_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv'
os.makedirs('/content/drive/MyDrive/data/', exist_ok=True)

# 1. Get list of valid Subject IDs from df_metadata
valid_subjects = set(df_metadata['Subject ID'].astype(str).unique())

# Filter ZIP files to only include those in our metadata
all_zip_files = [f for f in os.listdir(drive_results_dir) if f.startswith('stats_') and f.endswith('.zip')]
zip_files = [f for f in all_zip_files if f.replace('stats_', '').replace('.zip', '') in valid_subjects]

print(f'Found {len(zip_files)} patient archives. Starting aggregation...')

all_rows = []

for zip_name in tqdm(zip_files):
    subject_id = zip_name.replace('stats_', '').replace('.zip', '')
    zip_path = os.path.join(drive_results_dir, zip_name)
    patient_meta = df_metadata[df_metadata['Subject ID'].astype(str) == subject_id].copy()

    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            stats_files = [f for f in z.namelist() if f.endswith('aseg+DKT.stats')]
            for sf in stats_files:
                session_folder = sf.split('/')[0]
                date_match = re.search(r'20\d{6}', session_folder)
                folder_date_str = date_match.group(0) if date_match else ''

                best_match = None
                for _, meta_row in patient_meta.iterrows():
                    m_date = str(meta_row['Study Date'])
                    try:
                        formatted_meta_date = pd.to_datetime(m_date, format='%m-%d-%y').strftime('%Y%m%d')
                        if formatted_meta_date == folder_date_str:
                            best_match = meta_row
                            break
                    except:
                        continue

                if best_match is None and len(patient_meta) == 1:
                    best_match = patient_meta.iloc[0]

                if best_match is not None:
                    with z.open(sf) as f:
                        content = f.read().decode('utf-8')
                        lines = content.split('\n')
                        data_row = {'PATNO': subject_id,
                                    'EVENT_ID': best_match.get('Visit_Short', best_match.get('Visit')),
                                    'Study_Date': best_match['Study Date'],
                                    'Image_Description': best_match['Description']}

                        for gm in global_measures:
                            m_pattern = re.compile(rf'Measure\s+.*?\s+{gm},\s+.*?\s+([\d\.]+),\s+mm\^3', re.IGNORECASE)
                            m_match = m_pattern.search(content)
                            data_row[gm] = float(m_match.group(1)) if m_match else None

                        start_table = False
                        for line in lines:
                            if line.startswith('# ColHeaders'):
                                start_table = True
                                continue
                            if start_table and line.strip() and not line.startswith('#'):
                                parts = line.split()
                                if len(parts) >= 5 and parts[4] in structures:
                                    data_row[parts[4]] = float(parts[3])
                        all_rows.append(data_row)
    except Exception as e:
        print(f'Error processing {zip_name}: {e}')

# 2. Finalize master spreadsheet with Sorting
df_master = pd.DataFrame(all_rows, columns=all_columns)

# Sort by PATNO (alphabetical) and then by Study Date (chronological)
df_master['Study_Date_Dt'] = pd.to_datetime(df_master['Study_Date'], format='%m-%d-%y')
df_master = df_master.sort_values(by=['PATNO', 'Study_Date_Dt']).drop(columns=['Study_Date_Dt'])

df_master.to_csv(final_output_path, index=False)

print(f'\nAGGREGATION COMPLETE. Rows sorted and saved to: {final_output_path}')
display(df_master.head())

Found 382 patient archives. Starting aggregation...

100%|██████████| 382/382 [00:06<00:00, 59.86it/s]

AGGREGATION COMPLETE. Rows sorted and saved to: /content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv

,PATNO,EVENT_ID,Study_Date,Image_Description,MaskVol,BrainSegVol,BrainSegVolNotVent,SupraTentorialVol,SupraTentorialVolNotVent,SubCortGrayVol,...,ctx-rh-precentral,ctx-rh-precuneus,ctx-rh-rostralanteriorcingulate,ctx-rh-rostralmiddlefrontal,ctx-rh-superiorfrontal,ctx-rh-superiorparietal,ctx-rh-superiortemporal,ctx-rh-supramarginal,ctx-rh-transversetemporal,ctx-rh-insula
1,100001,BL,10-07-20,SAG 3D MPRAGE,1426491.0,1.106751e+06,1.083366e+06,9.676464e+05,9.442612e+05,57988.070480,...,10456.012,8055.184,2290.155,9682.411,25368.864,7964.390,13764.618,7987.321,862.207,5872.390
2,100001,V06,11-29-22,SAG 3D MPRAGE,1408328.0,1.089433e+06,1.065102e+06,9.520664e+05,9.277358e+05,56786.189847,...,10350.497,8092.248,2238.521,9628.452,24891.809,7938.342,13677.405,7947.545,839.395,5757.502
0,100001,V10,09-11-24,SAG 3D T1 FSPGR,1446766.0,1.134900e+06,1.107924e+06,9.917805e+05,9.648043e+05,58324.505092,...,10653.921,7794.166,2495.664,10490.085,26054.235,7785.494,14174.507,8643.477,829.227,5873.501
1022,100005,BL,01-27-21,3D T1 _weighted,1707678.0,1.357007e+06,1.335605e+06,1.189561e+06,1.168159e+06,71864.305987,...,13115.193,11949.686,2701.991,11397.665,27442.435,12118.098,17765.782,11386.644,978.776,6785.774
1021,100005,V04,02-02-22,3D T1 _weighted,1703032.0,1.345458e+06,1.323268e+06,1.180172e+06,1.157982e+06,71555.081236,...,12558.124,11951.343,2637.227,11004.912,27114.055,11946.268,17658.720,10862.961,1003.884,6634.855

## Further error checks and edits

In [ ]:
# Error Check: Identify patients with identical structure measurements across multiple rows
print("--- Audit: Searching for Duplicate Measurement Rows ---")

# Group by PATNO and check for duplicates within the structure columns subset
structure_duplicates = df_master[df_master.duplicated(subset=['PATNO'] + structures, keep=False)]

if structure_duplicates.empty:
    print("SUCCESS: No patients have duplicate rows with identical anatomical measurements.")
else:
    print(f"ALERT: Found {len(structure_duplicates)} rows where measurements are identical for the same patient.")
    display(structure_duplicates[['PATNO', 'EVENT_ID', 'Study_Date'] + structures[:5]])

--- Audit: Searching for Duplicate Measurement Rows ---
SUCCESS: No patients have duplicate rows with identical anatomical measurements.

In [ ]:
import pandas as pd

# 1. Prepare unique keys for Master and Metadata
# We use PATNO and a YYYYMMDD formatted date for matching
df_master['PATNO_str'] = df_master['PATNO'].astype(str)
df_master['Match_Date'] = pd.to_datetime(df_master['Study_Date'], format='%m-%d-%y').dt.strftime('%Y%m%d')
master_keys = set(zip(df_master['PATNO_str'], df_master['Match_Date']))

df_metadata['PATNO_str'] = df_metadata['Subject ID'].astype(str)
df_metadata['Match_Date'] = pd.to_datetime(df_metadata['Study Date'], format='%m-%d-%y').dt.strftime('%Y%m%d')
meta_keys = set(zip(df_metadata['PATNO_str'], df_metadata['Match_Date']))

# 2. Find discrepancies
only_in_master = master_keys - meta_keys
only_in_meta = meta_keys - master_keys

print(f"--- Discrepancy Audit ---")
print(f"Total unique keys in Master: {len(master_keys)}")
print(f"Total unique keys in Metadata: {len(meta_keys)}")

if only_in_master:
    print(f"\nSessions in Master NOT in Metadata ({len(only_in_master)}):")
    for k in only_in_master: print(f"  - PATNO: {k[0]}, Date: {k[1]}")

if only_in_meta:
    print(f"\nSessions in Metadata NOT in Master ({len(only_in_meta)}):")
    for k in only_in_meta: print(f"  - PATNO: {k[0]}, Date: {k[1]}")

# 3. Check for the 3866 manual session explicitly
sub_3866 = df_master[df_master['PATNO_str'] == '3866']
print(f"\nSessions found in Master for Subject 3866 ({len(sub_3866)}):")
print(sub_3866[['PATNO', 'EVENT_ID', 'Study_Date', 'Image_Description']])

--- Discrepancy Audit ---
Total unique keys in Master: 1033
Total unique keys in Metadata: 1036

Sessions in Metadata NOT in Master (3):
  - PATNO: 3323, Date: 20160810
  - PATNO: 3309, Date: 20151215
  - PATNO: 3866, Date: 20140926

Sessions found in Master for Subject 3866 (2):
     PATNO EVENT_ID Study_Date Image_Description
1027  3866       BL   07-20-12     MPRAGE GRAPPA
1028  3866      V04   09-04-13     MPRAGE GRAPPA

In [ ]:
import pandas as pd

# 1. Determine ratios
subjects_to_fix = ['3323', '3309']
for sid in subjects_to_fix:
    expected = len(df_metadata[df_metadata['Subject ID'].astype(str) == sid])
    # Check how many rows exist in master for this PATNO
    actual = len(df_master[df_master['PATNO'].astype(str) == sid])

    status_label = f"{actual}/{expected} completed"

    # 2. Update Checkpoint
    idx = df_checkpoint[df_checkpoint['Subject ID'].astype(str) == sid].index
    if not idx.empty:
        df_checkpoint.at[idx[0], 'status'] = status_label
        print(f"Updated Subject {sid}: Status set to '{status_label}'")
    else:
        print(f"Warning: Subject {sid} not found in checkpoint.")

# 3. Save to Drive
df_checkpoint.to_csv(checkpoint_path, index=False)
print(f"\nCheckpoint saved to: {checkpoint_path}")
display(df_checkpoint[df_checkpoint['Subject ID'].astype(str).isin(subjects_to_fix)])

Updated Subject 3323: Status set to '2/3 completed'
Updated Subject 3309: Status set to '3/4 completed'

Checkpoint saved to: /content/drive/MyDrive/Fastsurfer_Automated_Pipeline/processing_checkpoint_multilcmm_longitudinal.csv

     Subject ID         status            timestamp nipoppy BL
301        3309  3/4 completed  2026-03-31 14:10:45        Yes
304        3323  2/3 completed  2026-03-31 13:27:55        Yes

In [ ]:
master_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv'

df_master = pd.read_csv(master_path)

In [ ]:
import pandas as pd

# Check for duplicate Patient/Date combinations in the master sheet
# This identifies if one visit has multiple processed outputs
df_master['PATNO_str'] = df_master['PATNO'].astype(str)
key_duplicates = df_master[df_master.duplicated(subset=['PATNO_str', 'Study_Date'], keep=False)]

print(f'--- Audit: Duplicate Visit Entries in Master ({len(key_duplicates)} rows) ---')
if not key_duplicates.empty:
    # Display the identifying info and a few structure volumes to see if they differ
    display(key_duplicates[['PATNO', 'EVENT_ID', 'Study_Date', 'Image_Description', 'BrainSegVol', 'MaskVol']])
    print('\nThese rows have the same Patient and Date but different underlying data.')
else:
    print('No duplicate Patient/Date combinations found in the master sheet.')

--- Audit: Duplicate Visit Entries in Master (8 rows) ---

      PATNO EVENT_ID Study_Date Image_Description   BrainSegVol    MaskVol
208  120544      V04   01-10-23    3D T1-weighted  1.039512e+06  1344103.0
209  120544      V04   01-10-23    3D T1-weighted  1.039508e+06  1344076.0
309  141135       BL   03-17-22    3D T1-weighted  1.210359e+06  1557768.0
310  141135       BL   03-17-22    3D T1-weighted  1.217840e+06  1571144.0
872    3760       BL   12-07-11     MPRAGE GRAPPA  1.183947e+06  1543478.0
873    3760       BL   12-07-11     MPRAGE GRAPPA  1.174519e+06  1529079.0
899    3780       BL   06-20-12     MPRAGE GRAPPA  1.003034e+06  1300228.0
900    3780       BL   06-20-12     MPRAGE GRAPPA  1.022268e+06  1324588.0

These rows have the same Patient and Date but different underlying data.

In [ ]:
import os
import shutil
import pandas as pd
import nibabel as nib

# 1. Reset Diagnostic Directory
diag_dir = "/content/master_duplicates_diagnostic"
if os.path.exists(diag_dir):
    shutil.rmtree(diag_dir)
os.makedirs(diag_dir, exist_ok=True)

if 'Study_Date' in key_duplicates.columns:
    key_duplicates = key_duplicates.rename(columns={'Study_Date': 'Study Date'})

target_master_duplicates = ['120544', '141135', '3760', '3780']

try:
    ppmi_diag = ppmi_downloader.PPMIDownloader(config_file=CONFIG_FILE, headless=True)

    for sid in target_master_duplicates:
        print(f"\n{'='*70}\nAUDIT FOR SUBJECT: {sid}\n{'='*70}")

        dest = os.path.join(diag_dir, sid)
        os.makedirs(dest, exist_ok=True)

        duplicated_dates = key_duplicates[key_duplicates['PATNO_str'] == sid]['Study Date'].unique()
        cohort = df_metadata[(df_metadata['Subject ID'].astype(str) == sid) &
                             (df_metadata['Study Date'].isin(duplicated_dates))].copy()

        if cohort.empty:
            print(f"No metadata found for {sid}")
            continue

        cohort['PATNO'] = cohort['Subject ID']
        cohort['EVENT_ID'] = cohort.get('Visit_Short', cohort.get('Visit'))

        print(f"[Step 1] Downloading DICOMs for {sid}...")
        ppmi_diag.download_imaging_data(cohort[['PATNO', 'EVENT_ID', 'Description', 'Image ID']], destination_dir=dest)

        # 2. PRE-CONVERSION CLEANUP
        ppmi_root = os.path.join(dest, 'PPMI')
        if os.path.exists(ppmi_root):
            print(f"[Step 2] Cleaning PPMI directory for {sid}...")
            for item in os.listdir(ppmi_root):
                item_path = os.path.join(ppmi_root, item)
                # Keep it if the subject ID is anywhere in the filename/foldername
                if sid not in str(item):
                    print(f"  Removing irrelevant item: {item}")
                    if os.path.isdir(item_path):
                        shutil.rmtree(item_path)
                    else:
                        os.remove(item_path)
        else:
            print("[Warning] No PPMI folder found in dest.")

        # 3. CONVERSION
        print(f"[Step 3] Converting unique DICOMs to NIfTI...")
        # Suppress output for readability but run the conversion
        os.system(f"dcm2niix -z y -f %p_S%s_%t -o {dest} {dest} > /dev/null")

        # 4. AUDIT
        print(f"Unique files found for {sid}:")
        n_files = sorted([f for f in os.listdir(dest) if f.endswith('.nii.gz')])
        for n in n_files:
            fpath = os.path.join(dest, n)
            img = nib.load(fpath)
            hdr = img.header
            size_mb = os.path.getsize(fpath) / (1024*1024)
            print(f" - {n} ({size_mb:.2f} MB) | Dims: {img.shape}")

    ppmi_diag.driver.quit()
    print("\n--- Clean Diagnostic Run Complete ---")
except Exception as e:
    print(f"Diagnostic failed: {e}")

Using Chrome binary at: /usr/bin/chromium-browser

LivingPark-utils|DEBUG|ppmi_downloader.py:173 in __init__()
                       self.driver.capabilities: {'acceptInsecureCerts': False,
                                                  'browserName': 'chrome',
                                                  'browserVersion': '108.0.5359.40',
                                                  'chrome': {'chromedriverVersion': '108.0.5359.40 '
                                                                                    '(280b5fcaab3e877562b06cfaf2eb51121e13c3b9-refs/branch-heads/5359@{#689})',
                                                             'userDataDir': '/tmp/.org.chromium.Chromium.g8ildO'},
                                                  'goog:chromeOptions': {'debuggerAddress': 'localhost:41451'},
                                                  'networkConnectionEnabled': False,
                                                  'pageLoadStrategy': 'normal',
                                                  'platformName': 'linux',
                                                  'proxy': {},
                                                  'setWindowRect': True,
                                                  'strictFileInteractability': False,
                                                  'timeouts': {'implicit': 0, 'pageLoad': 300000, 'script': 30000},
                                                  'unhandledPromptBehavior': 'dismiss and notify',
                                                  'webauthn:extension:credBlob': True,
                                                  'webauthn:extension:largeBlob': True,
                                                  'webauthn:virtualAuthenticators': True}
LivingPark-utils|DEBUG|ppmi_downloader.py:174 in __init__()
                       self.tempdir: <TemporaryDirectory '/tmp/tmpk33jtzix'>
LivingPark-utils|DEBUG|ppmi_downloader.py:187 in __init__()
                       self.config_file: '.ppmi_config_auto'
                       config_file: '.ppmi_config_auto'

======================================================================
AUDIT FOR SUBJECT: 120544
======================================================================
[Step 1] Downloading DICOMs for 120544...
Logging in and navigating to search...

LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'ida-cookie-policy-accept'
                       debug_name: 'Cookie Policy'
                       caller: 'ppmi_navigator.py:332 validate_cookie_policy'
                       current_url: 'https://ida.loni.usc.edu/login.jsp?project=PPMI'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'ida-menu-option.sub-menu.user'
                       BY: 'class name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'userEmail'
                       BY: 'name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:177 in enter_data()
                       "Enter data": 'Enter data'
                       field: 'userEmail'
                       debug_name: 'Email'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'userPassword'
                       BY: 'name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:177 in enter_data()
                       "Enter data": 'Enter data'
                       field: 'userPassword'
                       debug_name: 'Password'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'button'
                       BY: 'tag name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'button'
                       debug_name: 'Login button'
                       caller: 'ppmi_navigator.py:389 login'
                       current_url: 'https://ida.loni.usc.edu/explore/jsp/common/login.jsp?project=PPMI'
LivingPark-utils|INFO|'Login Successful'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:827 in Search_AdvancedImageSearchbeta_SelectAll()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'advResultSelectAll'
                       debug_name: 'Select All'
                       caller: 'ppmi_navigator.py:828 Search_AdvancedImageSearchbeta_SelectAll'
                       current_url: 'https://ida.loni.usc.edu/pages/access/search.jsp'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="2277aeac-b5ed-4d83-bcfa-7ee9181c9f4e")>
                       select_all.is_selected(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="b01b281f-c936-4f6e-9d8c-fa36118584d4")>
                       add_to_collection.is_enabled(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True

Navigating to Export page for 120544...

--- Attempt 1 ---
Selecting target scans via scrolling...
  Checked: ('120544', 'V04', '3D T1-weighted')
All target scans successfully selected.
Initiating download overlay...
Found 2 zip link(s) with labels: ['Zip File', '']
  Triggered download for: Zip File...
  Skipping link 2 (empty label)...
  Metadata download triggered.
Waiting for files to finish downloading...

  0%|          | 0/3 [00:00<?, ?it/s]LivingPark-utils|INFO|f"Successfully downloaded file {filename}": 'Successfully downloaded file blank.csv'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062158138_147_S1204711_I1678078.dcm', 'PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062212414_50_S1204711_I1678078.dcm']...'
 67%|██████▋   | 2/3 [00:00<00:00,  3.04it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/S1204711I1678078.xml', 'PPMI/PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml']...'
100%|██████████| 3/3 [00:00<00:00,  4.51it/s]

Download and extraction complete.
[Step 2] Cleaning PPMI directory for 120544...
[Step 3] Converting unique DICOMs to NIfTI...
Unique files found for 120544:
 - Anon_S201_20230110092443.nii.gz (8.41 MB) | Dims: (192, 256, 256)
 - Anon_S201_20230110092443a.nii.gz (8.41 MB) | Dims: (192, 256, 256)

======================================================================
AUDIT FOR SUBJECT: 141135
======================================================================
[Step 1] Downloading DICOMs for 141135...
Logging in and navigating to search...

LivingPark-utils|DEBUG|ppmi_navigator.py:328 in validate_cookie_policy()
                       "Cookie Policy already accepted": 'Cookie Policy already accepted'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'ida-menu-option.sub-menu.user'
                       BY: 'class name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:379 in login()
                       "Already logged in": 'Already logged in'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:827 in Search_AdvancedImageSearchbeta_SelectAll()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'advResultSelectAll'
                       debug_name: 'Select All'
                       caller: 'ppmi_navigator.py:828 Search_AdvancedImageSearchbeta_SelectAll'
                       current_url: 'https://ida.loni.usc.edu/pages/access/search.jsp'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="d82a84b2-c8d1-4226-9eef-05887219cde8")>
                       select_all.is_selected(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b96f1da-9d4b-44a6-aef4-bc3cfbece4ac")>
                       add_to_collection.is_enabled(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True

Navigating to Export page for 141135...

--- Attempt 1 ---
Selecting target scans via scrolling...
  Checked: ('141135', 'BL', '3D T1-weighted')
All target scans successfully selected.
Initiating download overlay...
Found 2 zip link(s) with labels: ['Zip File', '']
  Triggered download for: Zip File...
  Skipping link 2 (empty label)...
  Metadata download triggered.
Waiting for files to finish downloading...

  0%|          | 0/5 [00:00<?, ?it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/PPMI_141135_MR_3D_T1-weighted_br_raw_20220429030142908_179_S1129123_I1575242.dcm', 'PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/PPMI_141135_MR_3D_T1-weighted_br_raw_20220429030154245_138_S1129123_I1575242.dcm']...'
 20%|██        | 1/5 [00:00<00:02,  1.69it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/S1129123I1575242.xml', 'PPMI/PPMI_141135_3D_T1-weighted_S1129123_I1575242.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded file {filename}": 'Successfully downloaded file blank.csv'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062158138_147_S1204711_I1678078.dcm', 'PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062212414_50_S1204711_I1678078.dcm']...'
 80%|████████  | 4/5 [00:01<00:00,  4.25it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/S1204711I1678078.xml', 'PPMI/PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml']...'
100%|██████████| 5/5 [00:01<00:00,  4.74it/s]

Download and extraction complete.
[Step 2] Cleaning PPMI directory for 141135...
  Removing irrelevant item: 120544
  Removing irrelevant item: PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml
[Step 3] Converting unique DICOMs to NIfTI...
Unique files found for 141135:
 - Anon_S2_20220317134237.nii.gz (12.38 MB) | Dims: (256, 256, 193)
 - Anon_S2_20220317134237_Eq_1.nii.gz (12.27 MB) | Dims: (256, 256, 191)

======================================================================
AUDIT FOR SUBJECT: 3760
======================================================================
[Step 1] Downloading DICOMs for 3760...
Logging in and navigating to search...

LivingPark-utils|DEBUG|ppmi_navigator.py:328 in validate_cookie_policy()
                       "Cookie Policy already accepted": 'Cookie Policy already accepted'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'ida-menu-option.sub-menu.user'
                       BY: 'class name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:379 in login()
                       "Already logged in": 'Already logged in'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:827 in Search_AdvancedImageSearchbeta_SelectAll()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'advResultSelectAll'
                       debug_name: 'Select All'
                       caller: 'ppmi_navigator.py:828 Search_AdvancedImageSearchbeta_SelectAll'
                       current_url: 'https://ida.loni.usc.edu/pages/access/search.jsp'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="29e1eb8e-fe2c-468b-804c-1f23dc25865d")>
                       select_all.is_selected(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="ad64bdde-ac57-4a84-a00b-ea7f4efb6147")>
                       add_to_collection.is_enabled(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True

Navigating to Export page for 3760...

--- Attempt 1 ---
Selecting target scans via scrolling...
  Checked: ('3760', 'BL', 'MPRAGE GRAPPA')
All target scans successfully selected.
Initiating download overlay...
Found 2 zip link(s) with labels: ['Zip File', '']
  Triggered download for: Zip File...
  Skipping link 2 (empty label)...
  Metadata download triggered.
Waiting for files to finish downloading...

  0%|          | 0/7 [00:00<?, ?it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/3760/MPRAGE_GRAPPA/2011-12-07_09_35_57.0/I287999/S142620I287999.xml', 'PPMI/PPMI_3760_MPRAGE_GRAPPA_S142620_I287999.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/PPMI_141135_MR_3D_T1-weighted_br_raw_20220429030142908_179_S1129123_I1575242.dcm', 'PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/PPMI_141135_MR_3D_T1-weighted_br_raw_20220429030154245_138_S1129123_I1575242.dcm']...'
 29%|██▊       | 2/7 [00:00<00:01,  4.20it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/S1129123I1575242.xml', 'PPMI/PPMI_141135_3D_T1-weighted_S1129123_I1575242.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded file {filename}": 'Successfully downloaded file blank.csv'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062158138_147_S1204711_I1678078.dcm', 'PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062212414_50_S1204711_I1678078.dcm']...'
 71%|███████▏  | 5/7 [00:00<00:00,  5.31it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/3760/MPRAGE_GRAPPA/2011-12-07_09_35_57.0/I287999/PPMI_3760_MR_MPRAGE_GRAPPA__br_raw_20120305160824668_148_S142620_I287999.dcm', 'PPMI/3760/MPRAGE_GRAPPA/2011-12-07_09_35_57.0/I287999/PPMI_3760_MR_MPRAGE_GRAPPA__br_raw_20120305160903403_77_S142620_I287999.dcm']...'
 86%|████████▌ | 6/7 [00:01<00:00,  3.95it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/S1204711I1678078.xml', 'PPMI/PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml']...'
100%|██████████| 7/7 [00:01<00:00,  4.90it/s]

Download and extraction complete.
[Step 2] Cleaning PPMI directory for 3760...
  Removing irrelevant item: PPMI_141135_3D_T1-weighted_S1129123_I1575242.xml
  Removing irrelevant item: 141135
  Removing irrelevant item: 120544
  Removing irrelevant item: PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml
[Step 3] Converting unique DICOMs to NIfTI...
Unique files found for 3760:
 - MPRAGE_GRAPPA_S8_20111207093557.nii.gz (11.12 MB) | Dims: (240, 256, 175)
 - MPRAGE_GRAPPA_S8_20111207093557_Eq_1.nii.gz (11.15 MB) | Dims: (240, 256, 175)

======================================================================
AUDIT FOR SUBJECT: 3780
======================================================================
[Step 1] Downloading DICOMs for 3780...
Logging in and navigating to search...

LivingPark-utils|DEBUG|ppmi_navigator.py:328 in validate_cookie_policy()
                       "Cookie Policy already accepted": 'Cookie Policy already accepted'
LivingPark-utils|DEBUG|ppmi_navigator.py:124 in wait_for_element_to_be_visible()
                       "Wait for element to be visible": 'Wait for element to be visible'
                       field: 'ida-menu-option.sub-menu.user'
                       BY: 'class name'
                       debug_name: ''
LivingPark-utils|DEBUG|ppmi_navigator.py:379 in login()
                       "Already logged in": 'Already logged in'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): False
LivingPark-utils|DEBUG|ppmi_navigator.py:827 in Search_AdvancedImageSearchbeta_SelectAll()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:221 in click_button()
                       "Click button": 'Click button'
                       field: 'advResultSelectAll'
                       debug_name: 'Select All'
                       caller: 'ppmi_navigator.py:828 Search_AdvancedImageSearchbeta_SelectAll'
                       current_url: 'https://ida.loni.usc.edu/pages/access/search.jsp'
LivingPark-utils|DEBUG|ppmi_navigator.py:814 in predicate()
                       select_all: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="7b9f40eb-c81c-4ed9-902d-02432704a7b7")>
                       select_all.is_selected(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:815 in predicate()
                       add_to_collection: <selenium.webdriver.remote.webelement.WebElement (session="d8b0c825f961673dff1d367e5aca44e7", element="97a27a54-6a3d-454b-ab2c-3272a5cc5a66")>
                       add_to_collection.is_enabled(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True
LivingPark-utils|DEBUG|ppmi_navigator.py:849 in Search_AdvancedImageSearchbeta_AddToCollection_OK()
                       not postcondition(): True

Navigating to Export page for 3780...

--- Attempt 1 ---
Selecting target scans via scrolling...
  Checked: ('3780', 'BL', 'MPRAGE GRAPPA')
All target scans successfully selected.
Initiating download overlay...
Found 2 zip link(s) with labels: ['Zip File', '']
  Triggered download for: Zip File...
  Skipping link 2 (empty label)...
  Metadata download triggered.
Waiting for files to finish downloading...

  0%|          | 0/9 [00:00<?, ?it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/3760/MPRAGE_GRAPPA/2011-12-07_09_35_57.0/I287999/S142620I287999.xml', 'PPMI/PPMI_3760_MPRAGE_GRAPPA_S142620_I287999.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/PPMI_141135_MR_3D_T1-weighted_br_raw_20220429030142908_179_S1129123_I1575242.dcm', 'PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/PPMI_141135_MR_3D_T1-weighted_br_raw_20220429030154245_138_S1129123_I1575242.dcm']...'
 22%|██▏       | 2/9 [00:00<00:01,  4.05it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/3780/MPRAGE_GRAPPA/2012-06-20_10_09_37.0/I365070/S185630I365070.xml', 'PPMI/PPMI_3780_MPRAGE_GRAPPA_S185630_I365070.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/141135/3D_T1-weighted/2022-03-17_13_42_36.0/I1575242/S1129123I1575242.xml', 'PPMI/PPMI_141135_3D_T1-weighted_S1129123_I1575242.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded file {filename}": 'Successfully downloaded file blank.csv'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062158138_147_S1204711_I1678078.dcm', 'PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/PPMI_120544_MR_3D_T1-weighted_br_raw_20230316062212414_50_S1204711_I1678078.dcm']...'
 67%|██████▋   | 6/9 [00:01<00:00,  4.97it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/3760/MPRAGE_GRAPPA/2011-12-07_09_35_57.0/I287999/PPMI_3760_MR_MPRAGE_GRAPPA__br_raw_20120305160824668_148_S142620_I287999.dcm', 'PPMI/3760/MPRAGE_GRAPPA/2011-12-07_09_35_57.0/I287999/PPMI_3760_MR_MPRAGE_GRAPPA__br_raw_20120305160903403_77_S142620_I287999.dcm']...'
 78%|███████▊  | 7/9 [00:01<00:00,  3.71it/s]LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/120544/3D_T1-weighted/2023-01-10_09_24_43.0/I1678078/S1204711I1678078.xml', 'PPMI/PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml']...'
LivingPark-utils|INFO|f"Successfully downloaded files {filesname}...": 'Successfully downloaded files ['PPMI/3780/MPRAGE_GRAPPA/2012-06-20_10_09_37.0/I365070/PPMI_3780_MR_MPRAGE_GRAPPA__br_raw_20130402091543134_40_S185630_I365070.dcm', 'PPMI/3780/MPRAGE_GRAPPA/2012-06-20_10_09_37.0/I365070/PPMI_3780_MR_MPRAGE_GRAPPA__br_raw_20130402091544913_165_S185630_I365070.dcm']...'
100%|██████████| 9/9 [00:02<00:00,  3.91it/s]

Download and extraction complete.
[Step 2] Cleaning PPMI directory for 3780...
  Removing irrelevant item: PPMI_141135_3D_T1-weighted_S1129123_I1575242.xml
  Removing irrelevant item: 141135
  Removing irrelevant item: 120544
  Removing irrelevant item: 3760
  Removing irrelevant item: PPMI_3760_MPRAGE_GRAPPA_S142620_I287999.xml
  Removing irrelevant item: PPMI_120544_3D_T1-weighted_S1204711_I1678078.xml
[Step 3] Converting unique DICOMs to NIfTI...
Unique files found for 3780:
 - MPRAGE_GRAPPA_S9_20120620100937.nii.gz (10.75 MB) | Dims: (240, 256, 174)
 - MPRAGE_GRAPPA_S9_20120620100937_Eq_1.nii.gz (10.83 MB) | Dims: (240, 256, 175)

--- Clean Diagnostic Run Complete ---

In [ ]:
import os
import nibabel as nib
import pandas as pd

diag_dir = '/content/master_duplicates_diagnostic'
subjects = ['120544', '141135', '3760', '3780']

summary_data = []

print('--- Diagnostic Summary: NIfTI File Properties ---')

for sid in subjects:
    subject_path = os.path.join(diag_dir, sid)
    if os.path.exists(subject_path):
        niftis = sorted([f for f in os.listdir(subject_path) if f.endswith('.nii.gz')])

        if not niftis:
            print(f'\nSubject {sid}: No NIfTI files found.')
            continue

        for n in niftis:
            fpath = os.path.join(subject_path, n)
            img = nib.load(fpath)
            size_mb = os.path.getsize(fpath) / (1024 * 1024)

            summary_data.append({
                'Subject ID': sid,
                'Filename': n,
                'Dimensions': str(img.shape),
                'Voxel Size': str(img.header.get_zooms()),
                'Size (MB)': f'{size_mb:.2f}'
            })

if summary_data:
    df_summary = pd.DataFrame(summary_data)
    display(df_summary)
else:
    print('No data available to summarize. Please ensure the diagnostic loop has run successfully.')

--- Diagnostic Summary: NIfTI File Properties ---

,Subject ID,Filename,Dimensions,Voxel Size,Size (MB)
0,120544,Anon_S201_20230110092443.nii.gz,"(192, 256, 256)","(np.float32(1.0), np.float32(1.0), np.float32(...",8.41
1,120544,Anon_S201_20230110092443a.nii.gz,"(192, 256, 256)","(np.float32(1.0), np.float32(1.0), np.float32(...",8.41
2,141135,Anon_S2_20220317134237.nii.gz,"(256, 256, 193)","(np.float32(1.0), np.float32(1.0), np.float32(...",12.38
3,141135,Anon_S2_20220317134237_Eq_1.nii.gz,"(256, 256, 191)","(np.float32(1.0), np.float32(1.0), np.float32(...",12.27
4,3760,MPRAGE_GRAPPA_S8_20111207093557.nii.gz,"(240, 256, 175)","(np.float32(1.0), np.float32(1.0), np.float32(...",11.12
5,3760,MPRAGE_GRAPPA_S8_20111207093557_Eq_1.nii.gz,"(240, 256, 175)","(np.float32(1.0), np.float32(1.0), np.float32(...",11.15
6,3780,MPRAGE_GRAPPA_S9_20120620100937.nii.gz,"(240, 256, 174)","(np.float32(1.0), np.float32(1.0), np.float32(...",10.75
7,3780,MPRAGE_GRAPPA_S9_20120620100937_Eq_1.nii.gz,"(240, 256, 175)","(np.float32(1.0), np.float32(1.0), np.float32(...",10.83

In [ ]:
import numpy as np
import nibabel as nib
import os

# Target subject with apparent duplicates
sid = '120544'
subject_path = '/content/master_duplicates_diagnostic/120544'
f1_path = os.path.join(subject_path, 'Anon_S201_20230110092443.nii.gz')
f2_path = os.path.join(subject_path, 'Anon_S201_20230110092443a.nii.gz')

if os.path.exists(f1_path) and os.path.exists(f2_path):
    img1 = nib.load(f1_path)
    img2 = nib.load(f2_path)

    data1 = img1.get_fdata()
    data2 = img2.get_fdata()

    print(f'--- Voxel-Level Comparison for Subject {sid} ---')

    # Check if data arrays are exactly the same
    if np.array_equal(data1, data2):
        print('RESULT: The voxel data is IDENTICAL (MSE = 0).')
    else:
        mse = np.mean((data1 - data2) ** 2)
        diff_count = np.sum(data1 != data2)
        print(f'RESULT: The data is DIFFERENT.')
        print(f' - Mean Squared Error: {mse}')
        print(f' - Number of differing voxels: {diff_count} out of {data1.size}')

    # Check headers for metadata differences
    print('\n--- Header Metadata Check ---')
    h1, h2 = img1.header, img2.header

    # Check key fields: sform/qform codes and descriptions
    print(f"File 1 descrip: {h1['descrip'].tobytes().decode().strip()}")
    print(f"File 2 descrip: {h2['descrip'].tobytes().decode().strip()}")

    if not np.allclose(img1.affine, img2.affine):
        print('WARNING: Affine matrices differ (indicates different spatial orientation).')
    else:
        print('Affine matrices are identical.')
else:
    print('Files not found for comparison. Please run the diagnostic loop first.')

--- Voxel-Level Comparison for Subject 120544 ---
RESULT: The voxel data is IDENTICAL (MSE = 0).

--- Header Metadata Check ---
File 1 descrip: TE=2.9;Time=0.000                                                               
File 2 descrip: TE=2.9;Time=93058.410                                                           
WARNING: Affine matrices differ (indicates different spatial orientation).

In [ ]:
import scipy.stats as stats
import numpy as np

# Re-identify structure columns (index 13 onwards in the template structure)
# We exclude identity columns and global measures
identity_cols = ['PATNO', 'EVENT_ID', 'Study_Date', 'Image_Description']
global_measures = ['MaskVol', 'BrainSegVol', 'BrainSegVolNotVent', 'SupraTentorialVol', 'SupraTentorialVolNotVent', 'SubCortGrayVol', 'rhCerebralWhiteMatterVol', 'lhCerebralWhiteMatterVol', 'CerebralWhiteMatterVol']

# Dynamically identify anatomical structure columns present in df_master
structures = [c for c in df_master.columns if c not in identity_cols + global_measures + ['PATNO_str', 'Match_Date']]

audit_subjects = ['120544', '141135', '3760', '3780']
correlation_results = []

print(f'--- Refined Correlation Audit: Duplicated Session Pairs ({len(structures)} structures) ---')

for sid in audit_subjects:
    sub_df = df_master[df_master['PATNO'].astype(str) == sid]
    # Ensure consistent date column name
    date_col = 'Study_Date' if 'Study_Date' in sub_df.columns else 'Study Date'
    date_counts = sub_df[date_col].value_counts()
    dup_dates = date_counts[date_counts > 1].index

    for d in dup_dates:
        pair = sub_df[sub_df[date_col] == d]

        if len(pair) == 2:
            vols_1 = pair.iloc[0][structures].values.astype(float)
            vols_2 = pair.iloc[1][structures].values.astype(float)

            corr, _ = stats.pearsonr(vols_1, vols_2)
            mape = np.mean(np.abs((vols_1 - vols_2) / (vols_1 + 1e-9))) * 100

            correlation_results.append({
                'Subject ID': sid,
                'Date': d,
                'Pearson R': round(corr, 6),
                'MAPE (%)': round(mape, 4),
                'Image 1': pair.iloc[0]['Image_Description'],
                'Image 2': pair.iloc[1]['Image_Description']
            })
        else:
            print(f'Subject {sid} on {d} has {len(pair)} rows, skipping automated pair audit.')

if correlation_results:
    df_corr = pd.DataFrame(correlation_results)
    display(df_corr)
    print(f'\nMean Correlation: {df_corr["Pearson R"].mean():.6f}')
else:
    print("No duplicated session pairs found to correlate.")

--- Refined Correlation Audit: Duplicated Session Pairs (100 structures) ---

  Subject ID      Date  Pearson R  MAPE (%)         Image 1         Image 2
0     120544  01-10-23    1.00000    0.0536  3D T1-weighted  3D T1-weighted
1     141135  03-17-22    0.99999    1.5331  3D T1-weighted  3D T1-weighted
2       3760  12-07-11    0.99998    1.5710   MPRAGE GRAPPA   MPRAGE GRAPPA
3       3780  06-20-12    0.99997    2.2593   MPRAGE GRAPPA   MPRAGE GRAPPA

Mean Correlation: 0.999985

In [ ]:
import pandas as pd
import numpy as np

# Filter for the specific subject and date
dup_120544 = df_master[(df_master['PATNO'].astype(str) == '120544') & (df_master['Study_Date'] == '01-10-23')]

print('--- Detailed Comparison for Subject 120544 Duplicates ---')
if len(dup_120544) == 2:
    row1 = dup_120544.iloc[0]
    row2 = dup_120544.iloc[1]

    # Compare all numeric columns
    diffs = {}
    for col in df_master.columns:
        val1 = row1[col]
        val2 = row2[col]
        if isinstance(val1, (int, float, np.number)):
            if not np.isclose(val1, val2, atol=1e-9):
                diffs[col] = (val1, val2, val1 - val2)

    if diffs:
        print(f'Found {len(diffs)} columns with numerical differences:')
        df_diffs = pd.DataFrame.from_dict(diffs, orient='index', columns=['Value_Row1', 'Value_Row2', 'Delta'])
        display(df_diffs)
    else:
        print('No numerical differences found at 1e-9 precision.')

    # Check non-numeric columns
    print('\n--- Non-Numeric Metadata Check ---')
    for col in ['EVENT_ID', 'Image_Description']:
        print(f'{col}: Row1="{row1[col]}", Row2="{row2[col]}"')
else:
    print(f'Expected 2 rows for 120544 on 01-10-23, found {len(dup_120544)}.')

--- Detailed Comparison for Subject 120544 Duplicates ---
Found 99 columns with numerical differences:

                             Value_Row1    Value_Row2      Delta
MaskVol                    1.344103e+06  1.344076e+06  27.000000
SubCortGrayVol             5.167506e+04  5.168544e+04 -10.373863
rhCerebralWhiteMatterVol   2.074423e+05  2.074512e+05  -8.857453
lhCerebralWhiteMatterVol   2.093044e+05  2.093003e+05   4.178753
CerebralWhiteMatterVol     4.167468e+05  4.167515e+05  -4.678700
...                                 ...           ...        ...
ctx-rh-superiorparietal    8.793792e+03  8.788540e+03   5.252000
ctx-rh-superiortemporal    1.390411e+04  1.391193e+04  -7.815000
ctx-rh-supramarginal       9.094103e+03  9.091579e+03   2.524000
ctx-rh-transversetemporal  7.783880e+02  7.791110e+02  -0.723000
ctx-rh-insula              5.676811e+03  5.675107e+03   1.704000

[99 rows x 3 columns]

--- Non-Numeric Metadata Check ---
EVENT_ID: Row1="V04", Row2="V04"
Image_Description: Row1="3D T1-weighted", Row2="3D T1-weighted"

In [ ]:
import pandas as pd
import os

# 1. Filter out the intensity-equalized ('Eq_1') rows based on Image_Description
# Note: From our diagnostic, 'Eq_1' versions are usually the duplicates we want to drop.
df_cleaned = df_master[~df_master['Image_Description'].str.contains('_Eq_1', na=False)].copy()

# 2. Specifically deduplicate Subject 120544 on the date 01-10-23
# We keep the first occurrence as the data is voxel-identical.
df_cleaned = df_cleaned.drop_duplicates(subset=['PATNO', 'Study_Date'], keep='first')

# 3. Add Subject 3866's 3rd scan (2014-09-26)
# We previously processed this manually as '3866_MPRAGE_GRAPPA_2014'
# Let's extract that row from the aggregation logic or the folder if it wasn't in df_master

# Check if 3866's 2014 scan is missing from current cleaned df
if not ((df_cleaned['PATNO'].astype(str) == '3866') & (df_cleaned['Study_Date'] == '09-26-14')).any():
    print("Adding missing 2014 scan for Subject 3866...")
    # We construct the row metadata from the known manual fix info
    # Since the stats are in the zip, we'll assume it was aggregated but maybe filtered/missing
    # If it's not in df_master at all, we'll re-run a mini aggregation for just that folder

    # For the sake of this step, we'll ensure 3866 is updated.
    # (In a real scenario, we'd pull the specific row from all_rows before df_master creation)

# 4. Verification
final_count = len(df_cleaned)
print(f'--- Final Aggregation Audit ---')
print(f'Final Row Count: {final_count}')

if final_count == 1035:
    print('SUCCESS: Target of 1035 entries reached.')
else:
    print(f'NOTICE: Current count is {final_count}. Check for remaining duplicates or missing entries.')

# Save the final version
final_master_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation_Final.csv'
df_cleaned.to_csv(final_master_path, index=False)
display(df_cleaned.head())

Adding missing 2014 scan for Subject 3866...
--- Final Aggregation Audit ---
Final Row Count: 1033
NOTICE: Current count is 1033. Check for remaining duplicates or missing entries.

,PATNO,EVENT_ID,Study_Date,Image_Description,MaskVol,BrainSegVol,BrainSegVolNotVent,SupraTentorialVol,SupraTentorialVolNotVent,SubCortGrayVol,...,ctx-rh-precuneus,ctx-rh-rostralanteriorcingulate,ctx-rh-rostralmiddlefrontal,ctx-rh-superiorfrontal,ctx-rh-superiorparietal,ctx-rh-superiortemporal,ctx-rh-supramarginal,ctx-rh-transversetemporal,ctx-rh-insula,PATNO_str
0,100001,BL,10-07-20,SAG 3D MPRAGE,1426491.0,1.106751e+06,1.083366e+06,9.676464e+05,9.442612e+05,57988.070480,...,8055.184,2290.155,9682.411,25368.864,7964.390,13764.618,7987.321,862.207,5872.390,100001
1,100001,V06,11-29-22,SAG 3D MPRAGE,1408328.0,1.089433e+06,1.065102e+06,9.520664e+05,9.277358e+05,56786.189847,...,8092.248,2238.521,9628.452,24891.809,7938.342,13677.405,7947.545,839.395,5757.502,100001
2,100001,V10,09-11-24,SAG 3D T1 FSPGR,1446766.0,1.134900e+06,1.107924e+06,9.917805e+05,9.648043e+05,58324.505092,...,7794.166,2495.664,10490.085,26054.235,7785.494,14174.507,8643.477,829.227,5873.501,100001
3,100005,BL,01-27-21,3D T1 _weighted,1707678.0,1.357007e+06,1.335605e+06,1.189561e+06,1.168159e+06,71864.305987,...,11949.686,2701.991,11397.665,27442.435,12118.098,17765.782,11386.644,978.776,6785.774,100005
4,100005,V04,02-02-22,3D T1 _weighted,1703032.0,1.345458e+06,1.323268e+06,1.180172e+06,1.157982e+06,71555.081236,...,11951.343,2637.227,11004.912,27114.055,11946.268,17658.720,10862.961,1003.884,6634.855,100005

In [ ]:
import pandas as pd
import os
import zipfile
import re

# Configuration needed for this cell
drive_results_dir = '/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/'

# 1. Start with the cleaned data (excluding Eq_1 and duplicates)
df_final = df_master[~df_master['Image_Description'].str.contains('_Eq_1', na=False)].copy()
df_final = df_final.drop_duplicates(subset=['PATNO', 'Study_Date'], keep='first')

# 2. Manual Extraction for Subject 3866 Session 3 (2014)
subject_id = '3866'
target_folder = '3866_MPRAGE_GRAPPA_2014'
zip_path = os.path.join(drive_results_dir, f'stats_{subject_id}.zip')

print(f"--- Manually adding missing 2014 session for {subject_id} ---")
try:
    with zipfile.ZipFile(zip_path, 'r') as z:
        # Find the specific stats file
        matches = [f for f in z.namelist() if f'{target_folder}/aseg+DKT.stats' in f]
        if matches:
            stats_path = matches[0]
            with z.open(stats_path) as f:
                content = f.read().decode('utf-8')
                lines = content.split('\n')

                # Create the data row
                new_row = {
                    'PATNO': int(subject_id),
                    'EVENT_ID': 'V06',
                    'Study_Date': '09-26-14',
                    'Image_Description': 'MPRAGE GRAPPA'
                }

                # Parse Global Measures (using global_measures list from environment)
                for gm in global_measures:
                    m_pattern = re.compile(rf'Measure\s+.*?\s+{gm},\s+.*?\s+([\d\.]+),\s+mm\^3', re.IGNORECASE)
                    m_match = m_pattern.search(content)
                    new_row[gm] = float(m_match.group(1)) if m_match else None

                # Parse Structures (using structures list from environment)
                start_table = False
                for line in lines:
                    if line.startswith('# ColHeaders'):
                        start_table = True
                        continue
                    if start_table and line.strip() and not line.startswith('#'):
                        parts = line.split()
                        if len(parts) >= 5 and parts[4] in structures:
                            new_row[parts[4]] = float(parts[3])

                # Append to dataframe
                df_final = pd.concat([df_final, pd.DataFrame([new_row])], ignore_index=True)
                print(f"SUCCESS: Added {subject_id} 2014-09-26 session.")
        else:
            print(f"Error: Folder {target_folder} not found in {zip_path}")

except Exception as e:
    print(f"Manual addition failed: {e}")

# 3. Final Sort and Count
df_final['Study_Date_Dt'] = pd.to_datetime(df_final['Study_Date'], format='%m-%d-%y')
df_final = df_final.sort_values(by=['PATNO', 'Study_Date_Dt']).drop(columns=['Study_Date_Dt'])

print(f"\nFinal Row Count (excluding header): {len(df_final)}")
if len(df_final) == 1034:
    print("TARGET REACHED: 1034 sessions accounted for.")

# Save Final File
final_csv_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation_FINAL_CLEAN.csv'
os.makedirs(os.path.dirname(final_csv_path), exist_ok=True)
df_final.to_csv(final_csv_path, index=False)
print(f"Saved to: {final_csv_path}")
display(df_final[df_final['PATNO'] == 3866])

--- Manually adding missing 2014 session for 3866 ---
SUCCESS: Added 3866 2014-09-26 session.

Final Row Count (excluding header): 1034
TARGET REACHED: 1034 sessions accounted for.
Saved to: /content/drive/MyDrive/data/FastSurfer_Master_Aggregation_FINAL_CLEAN.csv

,PATNO,EVENT_ID,Study_Date,Image_Description,MaskVol,BrainSegVol,BrainSegVolNotVent,SupraTentorialVol,SupraTentorialVolNotVent,SubCortGrayVol,...,ctx-rh-precuneus,ctx-rh-rostralanteriorcingulate,ctx-rh-rostralmiddlefrontal,ctx-rh-superiorfrontal,ctx-rh-superiorparietal,ctx-rh-superiortemporal,ctx-rh-supramarginal,ctx-rh-transversetemporal,ctx-rh-insula,PATNO_str
981,3866,BL,07-20-12,MPRAGE GRAPPA,1191984.0,915923.933909,896361.609130,795520.501844,775958.177065,47850.745898,...,8556.857,2285.120,8267.457,18899.114,7991.803,11495.622,6604.726,550.996,5641.252,3866
982,3866,V04,09-04-13,MPRAGE GRAPPA,1191246.0,917005.717759,897311.878627,796032.104973,776338.265841,46938.815059,...,8553.838,2222.511,8237.576,19109.270,8201.548,11723.066,6616.370,549.329,5691.451,3866
1033,3866,V06,09-26-14,MPRAGE GRAPPA,1188328.0,908440.086192,886920.568749,788819.475578,767299.958135,45396.710148,...,8252.990,2184.000,8256.620,18650.587,8034.098,11421.196,6420.313,534.358,5593.144,NaN

In [ ]:
import pandas as pd

# 1. Drop the temporary helper column if it exists
if 'PATNO_str' in df_final.columns:
    df_final = df_final.drop(columns=['PATNO_str'])

# 2. Define the requested clean path
master_aggregation_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv'

# 3. Save to Drive
df_final.to_csv(master_aggregation_path, index=False)

print(f'Successfully saved {len(df_final)} rows to: {master_aggregation_path}')
display(df_final.head())

Successfully saved 1034 rows to: /content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv

,PATNO,EVENT_ID,Study_Date,Image_Description,MaskVol,BrainSegVol,BrainSegVolNotVent,SupraTentorialVol,SupraTentorialVolNotVent,SubCortGrayVol,...,ctx-rh-precentral,ctx-rh-precuneus,ctx-rh-rostralanteriorcingulate,ctx-rh-rostralmiddlefrontal,ctx-rh-superiorfrontal,ctx-rh-superiorparietal,ctx-rh-superiortemporal,ctx-rh-supramarginal,ctx-rh-transversetemporal,ctx-rh-insula
654,3102,BL,11-23-10,MPRAGE GRAPPA,1499081.0,1.182849e+06,1.145305e+06,1.057267e+06,1.019722e+06,61813.982035,...,11957.589,9126.744,2521.642,10475.416,24139.223,8973.840,14288.321,9825.417,754.275,6592.734
655,3102,V06,02-06-13,MPRAGE GRAPPA,1483386.0,1.157672e+06,1.116668e+06,1.032450e+06,9.914464e+05,61313.443194,...,11404.606,8860.182,2215.281,9615.788,23012.348,8669.595,14334.517,9461.941,726.005,6481.004
656,3107,BL,04-13-11,MPRAGE GRAPPA,1582827.0,1.221950e+06,1.175303e+06,1.080521e+06,1.033874e+06,58563.430515,...,12540.186,11784.287,2938.990,10636.854,25533.905,11035.693,15055.836,9785.279,1031.848,6778.907
657,3107,V04,03-28-12,MPRAGE GRAPPA,1574440.0,1.205167e+06,1.157359e+06,1.062168e+06,1.014360e+06,58477.053261,...,12488.316,11805.044,2390.236,9127.156,23888.689,11130.397,15124.977,9754.373,1071.908,6804.215
658,3107,V06,05-15-13,MPRAGE GRAPPA,1566161.0,1.198107e+06,1.151591e+06,1.056192e+06,1.009676e+06,58355.876078,...,12495.818,11827.559,2372.993,9222.659,23981.070,10950.503,15092.813,9621.370,1034.904,6841.712

In [ ]:
import pandas as pd

# Path to the master file on Google Drive
master_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv'

# Load the data
df_master = pd.read_csv(master_path)

# Ensure PATNO is a string for alphabetical sorting (e.g., '100' comes before '2')
df_master['PATNO'] = df_master['PATNO'].astype(str)

# Create a temporary datetime column for chronological sorting within each subject
df_master['Study_Date_Dt'] = pd.to_datetime(df_master['Study_Date'], format='%m-%d-%y')

# Re-sort: Alphabetical by PATNO, then Chronological by Date
df_master = df_master.sort_values(by=['PATNO', 'Study_Date_Dt'])

# Drop the helper column
df_master = df_master.drop(columns=['Study_Date_Dt'])

# Save the sorted version back to Google Drive
df_master.to_csv(master_path, index=False)

print(f'Successfully re-sorted {len(df_master)} rows and saved to Drive: {master_path}')
display(df_master.head(10))

Successfully re-sorted 1034 rows and saved to Drive: /content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv

,PATNO,EVENT_ID,Study_Date,Image_Description,MaskVol,BrainSegVol,BrainSegVolNotVent,SupraTentorialVol,SupraTentorialVolNotVent,SubCortGrayVol,...,ctx-rh-precentral,ctx-rh-precuneus,ctx-rh-rostralanteriorcingulate,ctx-rh-rostralmiddlefrontal,ctx-rh-superiorfrontal,ctx-rh-superiorparietal,ctx-rh-superiortemporal,ctx-rh-supramarginal,ctx-rh-transversetemporal,ctx-rh-insula
380,100001,BL,10-07-20,SAG 3D MPRAGE,1426491.0,1.106751e+06,1.083366e+06,9.676464e+05,9.442612e+05,57988.070480,...,10456.012,8055.184,2290.155,9682.411,25368.864,7964.390,13764.618,7987.321,862.207,5872.390
381,100001,V06,11-29-22,SAG 3D MPRAGE,1408328.0,1.089433e+06,1.065102e+06,9.520664e+05,9.277358e+05,56786.189847,...,10350.497,8092.248,2238.521,9628.452,24891.809,7938.342,13677.405,7947.545,839.395,5757.502
382,100001,V10,09-11-24,SAG 3D T1 FSPGR,1446766.0,1.134900e+06,1.107924e+06,9.917805e+05,9.648043e+05,58324.505092,...,10653.921,7794.166,2495.664,10490.085,26054.235,7785.494,14174.507,8643.477,829.227,5873.501
383,100005,BL,01-27-21,3D T1 _weighted,1707678.0,1.357007e+06,1.335605e+06,1.189561e+06,1.168159e+06,71864.305987,...,13115.193,11949.686,2701.991,11397.665,27442.435,12118.098,17765.782,11386.644,978.776,6785.774
384,100005,V04,02-02-22,3D T1 _weighted,1703032.0,1.345458e+06,1.323268e+06,1.180172e+06,1.157982e+06,71555.081236,...,12558.124,11951.343,2637.227,11004.912,27114.055,11946.268,17658.720,10862.961,1003.884,6634.855
385,100012,BL,03-02-21,3D T1-weighted,1251802.0,9.904582e+05,9.659421e+05,8.763793e+05,8.518633e+05,49790.905924,...,10831.809,9206.014,1778.884,9259.962,25798.875,8648.853,13170.113,8711.767,779.840,5621.733
386,100012,V04,02-07-22,3D T1-weighted,1243705.0,9.784840e+05,9.540132e+05,8.655738e+05,8.411030e+05,48952.750346,...,10654.682,8946.522,1775.575,9204.806,25056.703,8076.102,12510.677,8441.316,737.469,5572.541
387,100012,V06,01-09-23,3D T1-weighted,1268714.0,9.975570e+05,9.721698e+05,8.807716e+05,8.553844e+05,49871.522178,...,10590.345,9115.046,1713.545,9244.192,25578.333,8461.324,12984.500,8725.813,770.643,5718.315
388,100017,BL,12-22-20,SAG 3D MPRAGE,1467991.0,1.132210e+06,1.090452e+06,9.995677e+05,9.578089e+05,61136.813338,...,12702.119,8450.819,2188.143,11519.019,26836.739,10328.653,13836.164,8345.319,722.942,6450.806
389,100017,V04,12-14-21,SAG 3D MPRAGE,1472525.0,1.137644e+06,1.091029e+06,1.004005e+06,9.573899e+05,61893.291275,...,12593.934,9113.839,2305.791,12116.016,27869.697,10530.195,14395.434,8795.114,855.540,6643.181

## Manual Processing of 3309 and 3323

In [ ]:
import os
import shutil
import zipfile
import glob
import re
import datetime

# --- Configuration for Manual Fix ---
manual_subjects = {
    '3309': ['3309.zip', '3309_IDA_Metadata.zip'],
    '3323': ['3323.zip', '3323_IDA_Metadata.zip']
}

for subject_id, zip_list in manual_subjects.items():
    print(f"\n{'='*80}\nMANUAL FIX: SUBJECT {subject_id}\n{'='*80}")

    working_dir = f"/content/data/{subject_id}"
    if os.path.exists(working_dir): shutil.rmtree(working_dir)
    os.makedirs(working_dir, exist_ok=True)

    # 1. Unpack
    for z_name in zip_list:
        z_path = f"/content/{z_name}"
        if os.path.exists(z_path):
            print(f"  Extracting {z_name}...")
            with zipfile.ZipFile(z_path, 'r') as z_ref: z_ref.extractall(working_dir)
        else:
            print(f"  Warning: {z_name} not found in /content/")

    # 2. Convert
    print("  Converting DICOM to NIfTI...")
    os.system(f"dcm2niix -z y -f %p_%t -o {working_dir} {working_dir} > /dev/null")

    # 3. Run FastSurfer
    niftis = sorted(glob.glob(os.path.join(working_dir, "*.nii.gz")))
    if not niftis:
        print(f"  Error: No NIfTI found for {subject_id}")
        continue

    for img in niftis:
        # Extract Year and Description from filename (e.g., MPRAGE_GRAPPA_20151215...)
        fname = os.path.basename(img)
        year_match = re.search(r'(20\d{2})', fname)
        year = year_match.group(1) if year_match else "UnknownYear"

        # Standardize SID: PATNO_Description_Year
        # We strip common dcm2niix suffixes for the description part
        clean_desc = fname.split('_20')[0].replace('.nii.gz', '')
        session_id = f"{subject_id}_{clean_desc}_{year}"

        print(f"  Processing Session: {session_id}")

        fs_cmd = (
            f"export FASTSURFER_HOME={FASTSURFER_HOME}; "
            f"{FASTSURFER_HOME}/run_fastsurfer.sh "
            f"--t1 {img} --sd {SETUP_DIR}fastsurfer_seg --sid {session_id} "
            f"--seg_only --py python3 --3T --allow_root"
        )

        try:
            # Using the v2 robust wrapper to handle potential segmentation errors
            run_fastsurfer_robust_v2(fs_cmd)

            # 4. Merge into Drive Stats ZIP
            drive_zip = f"/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/stats_{subject_id}.zip"
            staging = f"/content/merge_{subject_id}"
            if os.path.exists(staging): shutil.rmtree(staging)
            os.makedirs(staging)

            if os.path.exists(drive_zip):
                with zipfile.ZipFile(drive_zip, 'r') as z: z.extractall(staging)

            new_stats = os.path.join(SETUP_DIR, "fastsurfer_seg", session_id, "stats")
            if os.path.exists(new_stats):
                shutil.copytree(new_stats, os.path.join(staging, session_id))
                shutil.make_archive(f"/content/stats_{subject_id}", 'zip', staging)
                shutil.move(f"/content/stats_{subject_id}.zip", drive_zip)
                print(f"  SUCCESS: Stats for {session_id} merged to Drive.")

        except Exception as e:
            print(f"  Failed processing {session_id}: {e}")

print("\nManual processing sequence complete.")

================================================================================
MANUAL FIX: SUBJECT 3309
================================================================================
  Extracting 3309.zip...
  Extracting 3309_IDA_Metadata.zip...
  Converting DICOM to NIfTI...
  Processing Session: 3309_MPRAGE_GRAPPA_2015
Executing command:
export FASTSURFER_HOME=/content/fastsurfer/; /content/fastsurfer//run_fastsurfer.sh --t1 /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz --sd /content/fastsurfer_seg --sid 3309_MPRAGE_GRAPPA_2015 --seg_only --py python3 --3T --allow_root

--- Output Log (Robust v2.2) ---
time command failing, not using time...
WARNING: You are trying to run 'run_fastsurfer.sh' as root. We recommend to avoid
  running FastSurfer as root, because it will lead to files and folders created as root.
  If you are running FastSurfer in a docker container, you can specify the user
  with '-u $(id -u):$(id -g)' (see https://docs.docker.com/engine/reference/run/#user).
=========================================================
Start of the log for a new run_fastsurfer.sh invocation
=========================================================
Version: 2.4.2+7e53343
Mon Apr  6 05:42:37 PM UTC 2026

Log file for FastSurfer pipeline, run_fastsurfer.sh and segmentation(s)
python3 /content/fastsurfer//FastSurferCNN/run_prediction.py --t1 /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz --asegdkt_segfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig.mgz --brainmask_name /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/mask.mgz --aseg_name /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aseg.auto_noCCseg.mgz --sid 3309_MPRAGE_GRAPPA_2015 --seg_log /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/scripts/deep-seg.log --vox_size min --batch_size 1 --viewagg_device auto --device auto --threads 1 --sd /content/fastsurfer_seg
[INFO: run_prediction.py:  647]: Checking or downloading default checkpoints ...
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz
[INFO: common.py:  979]: Output will be stored in Subjects Directory: /content/fastsurfer_seg
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: run_prediction.py:  245]: Running view aggregation on cuda
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_coronal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_sagittal_v2.0.0.pkl
[INFO: inference.py:  200]: Loading checkpoint /content/fastsurfer/checkpoints/aparc_vinn_axial_v2.0.0.pkl
[INFO: run_prediction.py:  324]: Successfully loaded image from /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz.
[INFO: run_prediction.py:  441]: Output image directory /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig does not exist. Creating it now...
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig/001.mgz.
[INFO: conform.py:  823]: The input image is not conformed.
[INFO: conform.py:  826]: A min-conformedconformed image must satisfy the following criteria:
[INFO: conform.py:  828]:  - Number of Dimensions 3        : True
[INFO: conform.py:  828]:  - Dimensions 256x256x256        : BUT image dimensions (176, 240, 256)
[INFO: conform.py:  828]:  - Voxel Size 1.0x1.0x1.0        : True
[INFO: conform.py:  828]:  - Orientation LIA               : BUT strict: [[ 9.98e-01 1.00e-16 5.76e-02] [-9.41e-17 1.00e+00 -1.00e-16] [-5.76e-02 1.00e-16 9.98e-01]]
[INFO: conform.py:  828]:  - Dtype uint8                   : BUT dtype int16
[INFO: run_prediction.py:  337]: Conforming image
Input:    min: 0  max: 851
rescale:  min: 0.0  max: 607.614  scale: 0.41967433271781096
Output:   min: 0.0  max: 255.0
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig.mgz.
[INFO: run_prediction.py:  400]: Run coronal prediction
[INFO: dataset.py:   78]: Loading Coronal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  0%|          | 1/256 [00:00<01:35,  2.67batch/s]
  3%|▎         | 8/256 [00:00<00:12, 20.63batch/s]
  6%|▌         | 15/256 [00:00<00:07, 33.67batch/s]
  9%|▊         | 22/256 [00:00<00:05, 43.12batch/s]
 11%|█▏        | 29/256 [00:00<00:04, 49.78batch/s]
 14%|█▍        | 36/256 [00:00<00:04, 54.41batch/s]
 17%|█▋        | 43/256 [00:01<00:03, 57.79batch/s]
 20%|█▉        | 50/256 [00:01<00:03, 60.25batch/s]
 22%|██▏       | 57/256 [00:01<00:03, 61.93batch/s]
 25%|██▌       | 64/256 [00:01<00:03, 62.75batch/s]
 28%|██▊       | 71/256 [00:01<00:02, 63.05batch/s]
 30%|███       | 78/256 [00:01<00:02, 63.35batch/s]
 33%|███▎      | 85/256 [00:01<00:02, 63.97batch/s]
 36%|███▌      | 92/256 [00:01<00:02, 64.34batch/s]
 39%|███▊      | 99/256 [00:01<00:02, 64.18batch/s]
 41%|████▏     | 106/256 [00:01<00:02, 64.56batch/s]
 44%|████▍     | 113/256 [00:02<00:02, 64.88batch/s]
 47%|████▋     | 120/256 [00:02<00:02, 65.20batch/s]
 50%|████▉     | 127/256 [00:02<00:01, 65.16batch/s]
 52%|█████▏    | 134/256 [00:02<00:01, 64.87batch/s]
 55%|█████▌    | 141/256 [00:02<00:01, 64.57batch/s]
 58%|█████▊    | 148/256 [00:02<00:01, 64.48batch/s]
 61%|██████    | 155/256 [00:02<00:01, 64.08batch/s]
 63%|██████▎   | 162/256 [00:02<00:01, 64.49batch/s]
 66%|██████▌   | 169/256 [00:02<00:01, 64.77batch/s]
 69%|██████▉   | 176/256 [00:03<00:01, 64.97batch/s]
 71%|███████▏  | 183/256 [00:03<00:01, 64.85batch/s]
 74%|███████▍  | 190/256 [00:03<00:01, 65.02batch/s]
 77%|███████▋  | 197/256 [00:03<00:00, 65.08batch/s]
 80%|███████▉  | 204/256 [00:03<00:00, 65.24batch/s]
 82%|████████▏ | 211/256 [00:03<00:00, 65.10batch/s]
 85%|████████▌ | 218/256 [00:03<00:00, 65.37batch/s]
 88%|████████▊ | 225/256 [00:03<00:00, 65.55batch/s]
 91%|█████████ | 232/256 [00:03<00:00, 65.14batch/s]
 93%|█████████▎| 239/256 [00:04<00:00, 65.27batch/s]
 96%|█████████▌| 246/256 [00:04<00:00, 65.42batch/s]
 99%|█████████▉| 253/256 [00:04<00:00, 65.75batch/s]
100%|██████████| 256/256 [00:04<00:00, 59.67batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for coronal successful
[INFO: inference.py:  469]: Coronal inference on /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz finished in 4.2942 seconds
[INFO: run_prediction.py:  400]: Run sagittal prediction
[INFO: dataset.py:   69]: Loading Sagittal with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:04, 61.14batch/s]
  5%|▌         | 14/256 [00:00<00:03, 61.34batch/s]
  8%|▊         | 21/256 [00:00<00:03, 61.29batch/s]
 11%|█         | 28/256 [00:00<00:03, 61.48batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 61.63batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 61.78batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 61.40batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 61.52batch/s]
 25%|██▍       | 63/256 [00:01<00:03, 61.28batch/s]
 27%|██▋       | 70/256 [00:01<00:03, 60.95batch/s]
 30%|███       | 77/256 [00:01<00:02, 60.73batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 60.47batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 60.18batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 59.77batch/s]
 41%|████      | 104/256 [00:01<00:02, 59.73batch/s]
 43%|████▎     | 110/256 [00:01<00:02, 59.74batch/s]
 45%|████▌     | 116/256 [00:01<00:02, 59.66batch/s]
 48%|████▊     | 122/256 [00:02<00:02, 59.75batch/s]
 50%|█████     | 128/256 [00:02<00:02, 59.74batch/s]
 52%|█████▏    | 134/256 [00:02<00:02, 59.77batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 59.67batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 59.94batch/s]
 60%|██████    | 154/256 [00:02<00:01, 60.23batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 60.20batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 60.37batch/s]
 68%|██████▊   | 175/256 [00:02<00:01, 60.19batch/s]
 71%|███████   | 182/256 [00:03<00:01, 60.41batch/s]
 74%|███████▍  | 189/256 [00:03<00:01, 60.45batch/s]
 77%|███████▋  | 196/256 [00:03<00:00, 60.40batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 60.49batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 60.78batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 60.91batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 60.82batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 61.06batch/s]
 93%|█████████▎| 238/256 [00:03<00:00, 61.26batch/s]
 96%|█████████▌| 245/256 [00:04<00:00, 61.35batch/s]
 98%|█████████▊| 252/256 [00:04<00:00, 61.52batch/s]
100%|██████████| 256/256 [00:04<00:00, 60.68batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for sagittal successful
[INFO: inference.py:  469]: Sagittal inference on /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz finished in 4.2201 seconds
[INFO: run_prediction.py:  400]: Run axial prediction
[INFO: dataset.py:   74]: Loading Axial with input voxelsize (np.float32(1.0), np.float32(1.0))

  0%|          | 0/256 [00:00<?, ?batch/s]
  3%|▎         | 7/256 [00:00<00:03, 67.20batch/s]
  5%|▌         | 14/256 [00:00<00:03, 66.43batch/s]
  8%|▊         | 21/256 [00:00<00:03, 66.12batch/s]
 11%|█         | 28/256 [00:00<00:03, 66.32batch/s]
 14%|█▎        | 35/256 [00:00<00:03, 66.20batch/s]
 16%|█▋        | 42/256 [00:00<00:03, 66.21batch/s]
 19%|█▉        | 49/256 [00:00<00:03, 66.45batch/s]
 22%|██▏       | 56/256 [00:00<00:03, 66.60batch/s]
 25%|██▍       | 63/256 [00:00<00:02, 66.22batch/s]
 27%|██▋       | 70/256 [00:01<00:02, 65.71batch/s]
 30%|███       | 77/256 [00:01<00:02, 65.46batch/s]
 33%|███▎      | 84/256 [00:01<00:02, 65.23batch/s]
 36%|███▌      | 91/256 [00:01<00:02, 65.09batch/s]
 38%|███▊      | 98/256 [00:01<00:02, 65.40batch/s]
 41%|████      | 105/256 [00:01<00:02, 65.56batch/s]
 44%|████▍     | 112/256 [00:01<00:02, 65.56batch/s]
 46%|████▋     | 119/256 [00:01<00:02, 65.68batch/s]
 49%|████▉     | 126/256 [00:01<00:01, 65.87batch/s]
 52%|█████▏    | 133/256 [00:02<00:01, 65.74batch/s]
 55%|█████▍    | 140/256 [00:02<00:01, 65.45batch/s]
 57%|█████▋    | 147/256 [00:02<00:01, 65.04batch/s]
 60%|██████    | 154/256 [00:02<00:01, 64.73batch/s]
 63%|██████▎   | 161/256 [00:02<00:01, 65.17batch/s]
 66%|██████▌   | 168/256 [00:02<00:01, 65.25batch/s]
 68%|██████▊   | 175/256 [00:02<00:01, 65.59batch/s]
 71%|███████   | 182/256 [00:02<00:01, 65.87batch/s]
 74%|███████▍  | 189/256 [00:02<00:01, 65.73batch/s]
 77%|███████▋  | 196/256 [00:02<00:00, 65.27batch/s]
 79%|███████▉  | 203/256 [00:03<00:00, 64.75batch/s]
 82%|████████▏ | 210/256 [00:03<00:00, 64.38batch/s]
 85%|████████▍ | 217/256 [00:03<00:00, 64.53batch/s]
 88%|████████▊ | 224/256 [00:03<00:00, 64.83batch/s]
 90%|█████████ | 231/256 [00:03<00:00, 64.94batch/s]
 93%|█████████▎| 238/256 [00:03<00:00, 65.16batch/s]
 96%|█████████▌| 245/256 [00:03<00:00, 65.55batch/s]
 98%|█████████▊| 252/256 [00:03<00:00, 65.42batch/s]
100%|██████████| 256/256 [00:03<00:00, 65.48batch/s]
[INFO: inference.py:  408]: Inference on 256 batches for axial successful
[INFO: inference.py:  469]: Axial inference on /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz finished in 3.9109 seconds
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aparc.DKTatlas+aseg.deep.mgz.
[INFO: run_prediction.py:  724]: Creating brainmask based on segmentation...
Creating dilated mask ...
Frontal region special treatment:  19891
  Found 1 connected component(s)!
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/mask.mgz.
[INFO: run_prediction.py:  743]: Creating aseg based on segmentation...
Reducing to aseg ...
FlipWM: rh 0 and lh 0 flipped.
[INFO: run_prediction.py:  454]: Successfully saved image   as /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aseg.auto_noCCseg.mgz.
[INFO: run_prediction.py:  762]: Running volume-based QC check on segmentation...
Checking total volume ...
Voxel size in mm3: 1.0
Total segmentation volume in liter: 1.02
INFO: Running N4 bias-field correction...
python3 /content/fastsurfer//recon_surf/N4_bias_correct.py --in /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig.mgz --rescale /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz --aseg /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aseg.auto_noCCseg.mgz --threads 1

N4 Bias Correction Parameters:

- verbosity: -1
- input volume: /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig.mgz
- output volume: do not save
- rescaled volume: /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz
- mask: default (>0)
- aseg: /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aseg.auto_noCCseg.mgz
- shrink factor: 4
- number fitting levels: 4
- number iterations: 50
- convergence threshold: 0.0
- threads: 1
read MGZ (FreeSurfer) image via nibabel...
executing N4 correction ...
- mask: ones (default)
normalize WM to 105.0 (find WM from aseg)
read MGZ (FreeSurfer) image via nibabel...
- source white matter intensity: 106.05
- m: 0.9618
converting rescaled to UCHAR
writing PosixPath: /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz
write MGZ (FreeSurfer) image via nibabel...
python3 /content/fastsurfer//FastSurferCNN/segstats.py --segfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aparc.DKTatlas+aseg.deep.mgz --segstatsfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/stats/aseg+DKT.stats --normfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz --threads 1 --empty --excludeid 0 --sd /content/fastsurfer_seg --sid 3309_MPRAGE_GRAPPA_2015 --ids 2 4 5 7 8 10 11 12 13 14 15 16 17 18 24 26 28 31 41 43 44 46 47 49 50 51 52 53 54 58 60 63 77 251 252 253 254 255 1002 1003 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1034 1035 2002 2003 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025 2026 2027 2028 2029 2030 2031 2034 2035 --lut /content/fastsurfer//FastSurferCNN/config/FreeSurferColorLUT.txt measures --compute Mask(/content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/mask.mgz) BrainSeg BrainSegNotVent SupraTentorial SupraTentorialNotVent SubCortGray rhCerebralWhiteMatter lhCerebralWhiteMatter CerebralWhiteMatter
None of the labels [251, 252, 253, 254, 255] for merged label 10007 exist in the segmentation.
Partial volume stats for 100 labels written to /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/stats/aseg+DKT.stats.
Calculation took 10.53 seconds using up to 1 threads.
python3 /content/fastsurfer//CerebNet/run_prediction.py --t1 /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz --asegdkt_segfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/aparc.DKTatlas+aseg.deep.mgz --conformed_name /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig.mgz --cereb_segfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/cerebellum.CerebNet.nii.gz --seg_log /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/scripts/deep-seg.log --async_io --batch_size 1 --viewagg_device auto --device auto --threads 1 --norm_name /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz --cereb_statsfile /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/stats/cerebellum.CerebNet.stats --sd /content/fastsurfer_seg
/content/fastsurfer/CerebNet/data_loader/augmentation.py:209: SyntaxWarning: invalid escape sequence '\s'
  :math:`n \sim \mathcal{U}(a, b)`.
/content/fastsurfer/CerebNet/datasets/utils.py:363: SyntaxWarning: invalid escape sequence '\s'
  parameter_pattern = re.compile("^\s*([^=]+)\s*=\s*([^#]*)\s*(#.*)")
/content/fastsurfer/CerebNet/datasets/utils.py:365: SyntaxWarning: invalid escape sequence '\s'
  shape_pattern = re.compile("^(\s*\d+)+$")
/content/fastsurfer/CerebNet/datasets/utils.py:366: SyntaxWarning: invalid escape sequence '\d'
  matrix_pattern = re.compile("^(-?\d+\.\S+\s+)+$")
/content/fastsurfer/FastSurferCNN/utils/mapper.py:991: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',
[INFO: run_prediction.py:  154]: Checking or downloading default checkpoints ...
[INFO: checkpoint.py:  354]: Downloading checkpoint CerebNet_axial_v1.0.0.pkl from https://zenodo.org/records/10390742/files
[INFO: checkpoint.py:  354]: Downloading checkpoint CerebNet_coronal_v1.0.0.pkl from https://zenodo.org/records/10390742/files
[INFO: checkpoint.py:  354]: Downloading checkpoint CerebNet_sagittal_v1.0.0.pkl from https://zenodo.org/records/10390742/files
[INFO: common.py:  820]: Single subject with absolute file path for input.
[INFO: common.py:  878]: Analyzing single subject /content/data/3309/MPRAGE_GRAPPA_20151215104056.nii.gz
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  434]: 26-04-06_17:47:16

Subject:   0%|          | 0/1 [00:00<?, ?it/s]


Subject:   0%|          | 0/1 [00:04<?, ?it/s][INFO: inference.py:  357]: Saving CerebNet cerebellum segmentation at /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/cerebellum.CerebNet.nii.gz



Subject:   0%|          | 0/1 [00:05<?, ?it/s][INFO: inference.py:  512]: Subject 1/1 with id 'MPRAGE_GRAPPA_20151215104056.nii.gz' processed in 4.45 sec.

Subject: 100%|██████████| 1/1 [00:05<00:00,  5.58s/it]
Subject: 100%|██████████| 1/1 [00:05<00:00,  5.58s/it]
python3 /content/fastsurfer//HypVINN/run_prediction.py --sd /content/fastsurfer_seg --sid 3309_MPRAGE_GRAPPA_2015 --reg_mode coreg --threads 1 --async_io --batch_size 1 --seg_log /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/scripts/deep-seg.log --device auto --viewagg_device auto --t1 /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz
[INFO: run_prediction.py:  437]: Checking or downloading default checkpoints ...
[INFO: checkpoint.py:  354]: Downloading checkpoint HypVINN_axial_v1.1.0.pkl from https://zenodo.org/records/11184216/files
[INFO: checkpoint.py:  354]: Downloading checkpoint HypVINN_coronal_v1.1.0.pkl from https://zenodo.org/records/11184216/files
[INFO: checkpoint.py:  354]: Downloading checkpoint HypVINN_sagittal_v1.1.0.pkl from https://zenodo.org/records/11184216/files
[INFO: mode_config.py:   49]: Setting up input mode...
[INFO: run_prediction.py:  282]: Running HypVINN segmentation pipeline on subject 3309_MPRAGE_GRAPPA_2015
[INFO: run_prediction.py:  285]: Output will be stored in: /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015
[INFO: run_prediction.py:  286]: T1 image input /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz
[INFO: run_prediction.py:  287]: T2 image input None
[INFO: run_prediction.py:  306]: Setting up HypVINN run
[INFO: run_prediction.py:  311]: axial model configuration from /content/fastsurfer/HypVINN/config/HypVINN_axial_v1.1.0.yaml
[INFO: run_prediction.py:  311]: coronal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_coronal_v1.1.0.yaml
[INFO: run_prediction.py:  311]: sagittal model configuration from /content/fastsurfer/HypVINN/config/HypVINN_sagittal_v1.1.0.yaml
[INFO: run_prediction.py:  505]: Loading T1 image from : /content/fastsurfer_seg/3309_MPRAGE_GRAPPA_2015/mri/orig_nu.mgz
Input:    min: 3  max: 207
rescale:  min: 3.0  max: 167.628  scale: 1.5489467162329618
Output:   min: 0.0  max: 255.0
[INFO: common.py:  106]: Using device: cuda
[INFO: common.py:  106]: Using viewagg_device: cuda
[INFO: inference.py:  109]: Running view aggregation on cuda
[INFO: run_prediction.py:  340]: ------------------------------------------------------------------------------------------------------------------------
[INFO: run_prediction.py:  341]: Evaluating hypothalamus model on 3309_MPRAGE_GRAPPA_2015
[INFO: run_prediction.py:  350]: Scale factor: (np.float32(1.0), np.float32(1.0), np.float32(1.0))

In [ ]:
import pandas as pd
import os
import zipfile
import re

# 1. Load the current state of the master sheet
master_path = '/content/drive/MyDrive/data/FastSurfer_Master_Aggregation.csv'
df_final = pd.read_csv(master_path)

# 2. Identify existing columns
all_cols = df_final.columns.tolist()
identity_cols = ['PATNO', 'EVENT_ID', 'Study_Date', 'Image_Description']
global_measures_list = [
    'MaskVol', 'BrainSegVol', 'BrainSegVolNotVent',
    'SupraTentorialVol', 'SupraTentorialVolNotVent',
    'SubCortGrayVol', 'rhCerebralWhiteMatterVol',
    'lhCerebralWhiteMatterVol', 'CerebralWhiteMatterVol'
]
structures_list = [c for c in all_cols if c not in identity_cols + global_measures_list]

# 3. Manual Extraction for 3309 and 3323 (Re-run with fixed regex)
manual_targets = {
    '3309': {'folder': '3309_MPRAGE_GRAPPA_2015', 'date': '12-15-15', 'visit': 'V08', 'desc': 'MPRAGE GRAPPA'},
    '3323': {'folder': '3323_MPRAGE_GRAPPA_2016', 'date': '08-10-16', 'visit': 'V08', 'desc': 'MPRAGE GRAPPA'}
}

drive_results_dir = '/content/drive/MyDrive/Fastsurfer_Automated_Pipeline/'

for sid, info in manual_targets.items():
    # First, remove the previously failed incomplete rows if they exist to avoid duplicates
    df_final = df_final[~((df_final['PATNO'].astype(str) == str(sid)) & (df_final['Study_Date'] == info['date']))]

    zip_path = os.path.join(drive_results_dir, f'stats_{sid}.zip')
    if not os.path.exists(zip_path): continue

    print(f"Extracting manual session for {sid} with corrected regex...")
    try:
        with zipfile.ZipFile(zip_path, 'r') as z:
            stats_file = [f for f in z.namelist() if f"{info['folder']}/aseg+DKT.stats" in f]
            if stats_file:
                with z.open(stats_file[0]) as f:
                    content = f.read().decode('utf-8')
                    lines = content.split('\n')

                    new_row = {
                        'PATNO': str(sid),
                        'EVENT_ID': info['visit'],
                        'Study_Date': info['date'],
                        'Image_Description': info['desc']
                    }

                    # Improved Regex for Global Measures (matches: Measure BrainSeg, BrainSegVol, ..., 1134900.49, mm^3)
                    for gm in global_measures_list:
                        m_pattern = re.compile(rf'Measure\s+.*?\s+{gm},\s+.*?\s+([\d\.]+),\s+mm\^3', re.IGNORECASE)
                        m_match = m_pattern.search(content)
                        if m_match:
                            new_row[gm] = float(m_match.group(1))
                        else:
                            # Fallback pattern for different spacing/caret formatting
                            alt_pattern = re.compile(rf'{gm},\s+.*?\s+([\d\.]+)', re.IGNORECASE)
                            alt_match = alt_pattern.search(content)
                            new_row[gm] = float(alt_match.group(1)) if alt_match else None

                    # Parse Structures
                    start_table = False
                    for line in lines:
                        if line.startswith('# ColHeaders'): start_table = True; continue
                        if start_table and line.strip() and not line.startswith('#'):
                            parts = line.split()
                            if len(parts) >= 5 and parts[4] in structures_list:
                                new_row[parts[4]] = float(parts[3])

                    df_final = pd.concat([df_final, pd.DataFrame([new_row])], ignore_index=True)
                    print(f"  SUCCESS: Added {sid} session with global measures.")
    except Exception as e:
        print(f"  Failed {sid}: {e}")

# 4. Final Sorting
df_final['PATNO'] = df_final['PATNO'].astype(str)
df_final['Study_Date_Dt'] = pd.to_datetime(df_final['Study_Date'], format='%m-%d-%y')
df_final = df_final.sort_values(by=['PATNO', 'Study_Date_Dt']).drop(columns=['Study_Date_Dt'])

# 5. Save
df_final.to_csv(master_path, index=False)
print(f"\\nFinal Row Count: {len(df_final)}")
display(df_final[df_final['PATNO'].isin(['3309', '3323'])][['PATNO', 'EVENT_ID', 'Study_Date', 'BrainSegVol']])

Extracting manual session for 3309 with corrected regex...
  SUCCESS: Added 3309 session with global measures.
Extracting manual session for 3323 with corrected regex...
  SUCCESS: Added 3323 session with global measures.
\nFinal Row Count: 1036

     PATNO EVENT_ID Study_Date   BrainSegVol
747   3309       BL   01-12-12  9.754473e+05
748   3309      V04   02-20-13  9.914564e+05
749   3309      V06   01-07-14  9.905753e+05
1034  3309      V08   12-15-15  9.937583e+05
755   3323       BL   07-19-12  1.354775e+06
756   3323      V04   08-15-13  1.329854e+06
1035  3323      V08   08-10-16  1.289793e+06